#!/usr/bin/env wish

# Generated by Kryon Tcl/Tk Codegen
# Window: app (800x600)

package require Tk
package require ttk

# Window configuration
wm title . {app}
wm geometry . 800x600

# UI Components

# Main event loop
update
focus -force .
