[package]
name = "Kryon"
module_roots = ["src/ui", "src/plot", "src/backend", "src/data_views", "src/kss", "src/syntax"]

[exports]
Kryon = "src/ui/Kryon/module.zi"
Widgets = "src/ui/Widgets/module.zi"
Page = "src/ui/page.zi"
Semantic = "src/ui/semantic.zi"
geometry = "src/ui/geometry.zi"
drawing_props = "src/ui/drawing_props.zi"
PlotWidget = "src/plot/PlotWidget/module.zi"
TableView = "src/data_views/TableView/module.zi"
TreeView = "src/data_views/TreeView/module.zi"
Kss = "src/kss/Kss/module.zi"
Syntax = "src/syntax/Syntax/module.zi"

[tool]
project = "build/bin/kryon"
