[package]
name = "widgets"
entry = "src/app.zi"
module_roots = ["src"]
bridge_modules = ["app"]

[toolchain]
git = "https://github.com/ziranlang/ziran.git"
ref = "master"

[tool.kryon]
default_profile = "web"

[tool.kryon.profiles.web]
backend = "canvas"

[dependencies.kryon]
git = "https://github.com/kryonlabs/kryon.git"
ref = "master"
