[package]
name = "widgets"
entry = "src/app.zi"
module_roots = ["src"]
bridge_modules = ["app"]

[toolchain]
git = "https://github.com/ziranlang/ziran.git"
ref = "c0e0e9847d9bf7c5e4368ec2745c3e7262323b50"

[tool.kryon]
default_profile = "web"

[tool.kryon.profiles.web]
backend = "canvas"

[dependencies.kryon]
git = "https://github.com/kryonlabs/kryon.git"
ref = "eba5a07370e6fb8260274a867e8cc7edcd67b89c"
