FLINT_DIR ?= vendor/flint
CMAKE ?= cmake
FLINT_VENDOR_BUILD_DIR ?= build/vendor
FLINT_VENDOR_ORDER_ONLY ?=

FLINT_LIBOQS_DIR ?= $(FLINT_DIR)/vendor/liboqs
FLINT_LIBOQS_BUILD_DIR ?= $(FLINT_VENDOR_BUILD_DIR)/liboqs
FLINT_LIBOQS_A ?= $(FLINT_LIBOQS_BUILD_DIR)/lib/liboqs.a
FLINT_LIBOQS_INCLUDE ?= -I$(FLINT_LIBOQS_BUILD_DIR)/include
FLINT_LIBOQS_BUILD_TYPE ?= MinSizeRel
FLINT_LIBOQS_MINIMAL_BUILD ?= SIG_ml_dsa_44

FLINT_WEB_LIBOQS_BUILD_DIR ?= $(FLINT_VENDOR_BUILD_DIR)/web-liboqs
FLINT_WEB_LIBOQS_A ?= $(FLINT_WEB_LIBOQS_BUILD_DIR)/lib/liboqs.a

FLINT_LIBRESSL_DIR ?= $(FLINT_DIR)/vendor/libressl
FLINT_LIBRESSL_OPENBSD_DIR ?= $(FLINT_DIR)/vendor/openbsd
FLINT_LIBRESSL_BUILD_DIR ?= $(FLINT_VENDOR_BUILD_DIR)/libressl
FLINT_LIBRESSL_SOURCE_DIR ?= $(FLINT_LIBRESSL_BUILD_DIR)-src
FLINT_LIBRESSL_SOURCE_STAMP ?= $(FLINT_LIBRESSL_SOURCE_DIR)/.prepared
FLINT_LIBRESSL_LIB_DIR ?= $(FLINT_LIBRESSL_BUILD_DIR)/lib
FLINT_LIBRESSL_SSL_SO ?= $(FLINT_LIBRESSL_LIB_DIR)/libssl.so
FLINT_LIBRESSL_CRYPTO_SO ?= $(FLINT_LIBRESSL_LIB_DIR)/libcrypto.so
FLINT_LIBRESSL_INSTALL_STAMP ?= $(FLINT_LIBRESSL_BUILD_DIR)/.installed
FLINT_LIBRESSL_BUILD_TYPE ?= MinSizeRel

FLINT_CURL_DIR ?= $(FLINT_DIR)/vendor/curl
FLINT_CURL_BUILD_DIR ?= $(FLINT_VENDOR_BUILD_DIR)/curl
FLINT_CURL_INCLUDE_DIR ?= $(FLINT_CURL_BUILD_DIR)/include
FLINT_CURL_LIB_DIR ?= $(FLINT_CURL_BUILD_DIR)/lib64
FLINT_CURL_SO ?= $(FLINT_CURL_LIB_DIR)/libcurl.so
FLINT_CURL_PROTOCOL_CHECK ?= $(FLINT_CURL_BUILD_DIR)/.protocols-ok
FLINT_CURL_BUILD_TYPE ?= MinSizeRel
FLINT_CURL_INSTALL_LIBDIR ?= lib64
FLINT_CURL_EXTRA_CMAKE_FLAGS ?=
FLINT_CURL_REQUIRE_WEBSOCKETS ?= 0

FLINT_OPENSSL_ROOT_DIR := $(abspath $(FLINT_LIBRESSL_BUILD_DIR))
FLINT_OPENSSL_INCLUDE_DIR := $(abspath $(FLINT_LIBRESSL_BUILD_DIR))/include
FLINT_OPENSSL_SSL_LIBRARY := $(abspath $(FLINT_LIBRESSL_SSL_SO))
FLINT_OPENSSL_CRYPTO_LIBRARY := $(abspath $(FLINT_LIBRESSL_CRYPTO_SO))
FLINT_OPENSSL_LIB_DIR := $(patsubst %/,%,$(dir $(FLINT_OPENSSL_SSL_LIBRARY)))

FLINT_CURL_CFLAGS ?= -I$(FLINT_CURL_INCLUDE_DIR)
FLINT_CURL_LDLIBS ?= -L$(FLINT_CURL_LIB_DIR) -Wl,-rpath,$(abspath $(FLINT_CURL_LIB_DIR)) -lcurl -Xlinker -rpath -Xlinker $(FLINT_OPENSSL_LIB_DIR) $(FLINT_OPENSSL_SSL_LIBRARY) $(FLINT_OPENSSL_CRYPTO_LIBRARY)

$(FLINT_LIBOQS_A): $(FLINT_LIBOQS_DIR)/CMakeLists.txt | $(FLINT_VENDOR_ORDER_ONLY)
	@if [ -f "$(FLINT_LIBOQS_BUILD_DIR)/CMakeCache.txt" ] && ! grep -q "CMAKE_HOME_DIRECTORY:INTERNAL=$(abspath $(FLINT_LIBOQS_DIR))" "$(FLINT_LIBOQS_BUILD_DIR)/CMakeCache.txt"; then \
		rm -rf "$(FLINT_LIBOQS_BUILD_DIR)"; \
	fi
	$(CMAKE) -S $(FLINT_LIBOQS_DIR) -B $(FLINT_LIBOQS_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(FLINT_LIBOQS_BUILD_TYPE) \
		-DBUILD_SHARED_LIBS=OFF \
		-DOQS_BUILD_ONLY_LIB=ON \
		-DOQS_USE_OPENSSL=OFF \
		-DOQS_MINIMAL_BUILD=$(FLINT_LIBOQS_MINIMAL_BUILD)
	$(CMAKE) --build $(FLINT_LIBOQS_BUILD_DIR) --target oqs

$(FLINT_WEB_LIBOQS_A): $(FLINT_LIBOQS_DIR)/CMakeLists.txt | $(FLINT_VENDOR_ORDER_ONLY)
	@if [ -f "$(FLINT_WEB_LIBOQS_BUILD_DIR)/CMakeCache.txt" ] && ! grep -q "CMAKE_HOME_DIRECTORY:INTERNAL=$(abspath $(FLINT_LIBOQS_DIR))" "$(FLINT_WEB_LIBOQS_BUILD_DIR)/CMakeCache.txt"; then \
		rm -rf "$(FLINT_WEB_LIBOQS_BUILD_DIR)"; \
	fi
	emcmake $(CMAKE) -S $(FLINT_LIBOQS_DIR) -B $(FLINT_WEB_LIBOQS_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(FLINT_LIBOQS_BUILD_TYPE) \
		-DBUILD_SHARED_LIBS=OFF \
		-DOQS_BUILD_ONLY_LIB=ON \
		-DOQS_USE_OPENSSL=OFF \
		-DOQS_DIST_BUILD=OFF \
		-DOQS_OPT_TARGET=generic \
		-DOQS_MINIMAL_BUILD=$(FLINT_LIBOQS_MINIMAL_BUILD)
	$(CMAKE) --build $(FLINT_WEB_LIBOQS_BUILD_DIR) --target oqs

$(FLINT_LIBRESSL_SOURCE_STAMP): $(FLINT_LIBRESSL_DIR)/CMakeLists.txt $(FLINT_LIBRESSL_DIR)/update.sh $(FLINT_LIBRESSL_OPENBSD_DIR)/.git | $(FLINT_VENDOR_ORDER_ONLY)
	rm -rf "$(FLINT_LIBRESSL_SOURCE_DIR)"
	git clone --local --no-hardlinks "$(abspath $(FLINT_LIBRESSL_DIR))" "$(FLINT_LIBRESSL_SOURCE_DIR)"
	cd "$(FLINT_LIBRESSL_SOURCE_DIR)" && git checkout --detach "$$(git -C "$(abspath $(FLINT_LIBRESSL_DIR))" rev-parse HEAD)"
	@if [ ! -f "$(FLINT_LIBRESSL_SOURCE_DIR)/VERSION" ]; then \
		cd "$(FLINT_LIBRESSL_SOURCE_DIR)" && LIBRESSL_GIT="file://$(abspath $(dir $(FLINT_LIBRESSL_OPENBSD_DIR)))" ./update.sh; \
	fi
	touch "$(FLINT_LIBRESSL_SOURCE_STAMP)"

$(FLINT_LIBRESSL_INSTALL_STAMP): $(FLINT_LIBRESSL_SOURCE_STAMP)
	@if [ -f "$(FLINT_LIBRESSL_BUILD_DIR)/CMakeCache.txt" ] && ! grep -q "CMAKE_HOME_DIRECTORY:INTERNAL=$(abspath $(FLINT_LIBRESSL_SOURCE_DIR))" "$(FLINT_LIBRESSL_BUILD_DIR)/CMakeCache.txt"; then \
		rm -rf "$(FLINT_LIBRESSL_BUILD_DIR)"; \
	fi
	$(CMAKE) -S $(FLINT_LIBRESSL_SOURCE_DIR) -B $(FLINT_LIBRESSL_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(FLINT_LIBRESSL_BUILD_TYPE) \
		-DCMAKE_INSTALL_PREFIX=$(abspath $(FLINT_LIBRESSL_BUILD_DIR)) \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_SHARED_LIBS=ON \
		-DLIBRESSL_APPS=OFF \
		-DLIBRESSL_TESTS=OFF \
		-DENABLE_NC=OFF
	$(CMAKE) --build $(FLINT_LIBRESSL_BUILD_DIR) --target install
	touch $(FLINT_LIBRESSL_INSTALL_STAMP)

$(FLINT_LIBRESSL_SSL_SO) $(FLINT_LIBRESSL_CRYPTO_SO): $(FLINT_LIBRESSL_INSTALL_STAMP)

$(FLINT_CURL_SO): $(FLINT_CURL_DIR)/CMakeLists.txt $(FLINT_LIBRESSL_SSL_SO) $(FLINT_LIBRESSL_CRYPTO_SO) | $(FLINT_VENDOR_ORDER_ONLY)
	@if [ -f "$(FLINT_CURL_BUILD_DIR)/CMakeCache.txt" ] && ! grep -q "CMAKE_HOME_DIRECTORY:INTERNAL=$(abspath $(FLINT_CURL_DIR))" "$(FLINT_CURL_BUILD_DIR)/CMakeCache.txt"; then \
		rm -rf "$(FLINT_CURL_BUILD_DIR)"; \
	fi
	$(CMAKE) -S $(FLINT_CURL_DIR) -B $(FLINT_CURL_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(FLINT_CURL_BUILD_TYPE) \
		-DCMAKE_INSTALL_PREFIX=$(abspath $(FLINT_CURL_BUILD_DIR)) \
		-DCMAKE_INSTALL_LIBDIR=$(FLINT_CURL_INSTALL_LIBDIR) \
		-DCMAKE_BUILD_RPATH=$(FLINT_OPENSSL_LIB_DIR) \
		-DCMAKE_INSTALL_RPATH=$(FLINT_OPENSSL_LIB_DIR) \
		-DBUILD_CURL_EXE=OFF \
		-DBUILD_SHARED_LIBS=ON \
		-DBUILD_STATIC_LIBS=OFF \
		-DCURL_USE_OPENSSL=ON \
		-DOPENSSL_ROOT_DIR=$(FLINT_OPENSSL_ROOT_DIR) \
		-DOPENSSL_INCLUDE_DIR=$(FLINT_OPENSSL_INCLUDE_DIR) \
		-DOPENSSL_SSL_LIBRARY=$(FLINT_OPENSSL_SSL_LIBRARY) \
		-DOPENSSL_CRYPTO_LIBRARY=$(FLINT_OPENSSL_CRYPTO_LIBRARY) \
		-DCURL_USE_LIBPSL=OFF \
		-DCURL_USE_LIBSSH2=OFF \
		-DCURL_USE_GSSAPI=OFF \
		-DUSE_NGHTTP2=OFF \
		-DUSE_LIBIDN2=OFF \
		-DCURL_DISABLE_LDAP=ON \
		-DCURL_DISABLE_LDAPS=ON \
		-DCURL_DISABLE_SMB=ON \
		-DENABLE_CURL_MANUAL=OFF \
		-DBUILD_EXAMPLES=OFF \
		-DBUILD_LIBCURL_DOCS=OFF \
		-DBUILD_MISC_DOCS=OFF \
		-DBUILD_TESTING=OFF \
		$(FLINT_CURL_EXTRA_CMAKE_FLAGS)
	$(CMAKE) --build $(FLINT_CURL_BUILD_DIR) --target install

$(FLINT_CURL_PROTOCOL_CHECK): $(FLINT_CURL_SO)
	@if [ "$(FLINT_CURL_REQUIRE_WEBSOCKETS)" = "1" ]; then \
		$(FLINT_CURL_BUILD_DIR)/bin/curl-config --protocols | grep -Eq '(^|[[:space:]])WS([[:space:]]|$$)' || { echo "vendored libcurl was built without WS protocol support"; exit 1; }; \
		$(FLINT_CURL_BUILD_DIR)/bin/curl-config --protocols | grep -Eq '(^|[[:space:]])WSS([[:space:]]|$$)' || { echo "vendored libcurl was built without WSS protocol support"; exit 1; }; \
	fi
	@touch $@
