KRYON_DIR ?= vendor/kryon
CMAKE ?= cmake
KRYON_VENDOR_BUILD_DIR ?= build/vendor
KRYON_VENDOR_ORDER_ONLY ?=

KRYON_LIBOQS_DIR ?= $(KRYON_DIR)/vendor/liboqs
KRYON_LIBOQS_BUILD_DIR ?= $(KRYON_VENDOR_BUILD_DIR)/liboqs
KRYON_LIBOQS_A ?= $(KRYON_LIBOQS_BUILD_DIR)/lib/liboqs.a
KRYON_LIBOQS_INCLUDE ?= -I$(KRYON_LIBOQS_BUILD_DIR)/include
KRYON_LIBOQS_BUILD_TYPE ?= MinSizeRel
KRYON_LIBOQS_MINIMAL_BUILD ?= SIG_ml_dsa_44
KRYON_LIBOQS_CPU_FEATURE_CMAKE_FLAGS ?= \
	-DOQS_USE_ADX_INSTRUCTIONS=OFF \
	-DOQS_USE_AES_INSTRUCTIONS=OFF \
	-DOQS_USE_AVX_INSTRUCTIONS=OFF \
	-DOQS_USE_AVX2_INSTRUCTIONS=OFF \
	-DOQS_USE_AVX512_INSTRUCTIONS=OFF \
	-DOQS_USE_AVX512BW_INSTRUCTIONS=OFF \
	-DOQS_USE_AVX512DQ_INSTRUCTIONS=OFF \
	-DOQS_USE_AVX512F_INSTRUCTIONS=OFF \
	-DOQS_USE_BMI1_INSTRUCTIONS=OFF \
	-DOQS_USE_BMI2_INSTRUCTIONS=OFF \
	-DOQS_USE_FMA_INSTRUCTIONS=OFF \
	-DOQS_USE_PCLMULQDQ_INSTRUCTIONS=OFF \
	-DOQS_USE_POPCNT_INSTRUCTIONS=OFF \
	-DOQS_USE_SSE_INSTRUCTIONS=OFF \
	-DOQS_USE_SSE2_INSTRUCTIONS=OFF \
	-DOQS_USE_SSE3_INSTRUCTIONS=OFF \
	-DOQS_USE_VPCLMULQDQ_INSTRUCTIONS=OFF

KRYON_WEB_LIBOQS_BUILD_DIR ?= $(KRYON_VENDOR_BUILD_DIR)/web-liboqs
KRYON_WEB_LIBOQS_A ?= $(KRYON_WEB_LIBOQS_BUILD_DIR)/lib/liboqs.a

KRYON_CURL_DIR ?= $(KRYON_DIR)/vendor/curl
KRYON_CURL_BUILD_DIR ?= $(KRYON_VENDOR_BUILD_DIR)/curl
KRYON_CURL_INCLUDE_DIR ?= $(KRYON_CURL_BUILD_DIR)/include
KRYON_VENDOR_UNAME_S := $(shell uname -s 2>/dev/null)
ifeq ($(KRYON_VENDOR_UNAME_S),FreeBSD)
KRYON_CURL_INSTALL_LIBDIR ?= lib
else
KRYON_CURL_INSTALL_LIBDIR ?= lib64
endif
KRYON_CURL_LIB_DIR ?= $(KRYON_CURL_BUILD_DIR)/$(KRYON_CURL_INSTALL_LIBDIR)
KRYON_CURL_A ?= $(KRYON_CURL_LIB_DIR)/libcurl.a
KRYON_CURL_SO ?= $(KRYON_CURL_A)
KRYON_CURL_PROTOCOL_CHECK ?= $(KRYON_CURL_BUILD_DIR)/.protocols-ok
KRYON_CURL_BUILD_TYPE ?= MinSizeRel
KRYON_CURL_EXTRA_CMAKE_FLAGS ?=
KRYON_CURL_REQUIRE_WEBSOCKETS ?= 0


KRYON_CMARK_GFM_DIR ?= $(KRYON_DIR)/vendor/cmark-gfm
KRYON_CMARK_GFM_BUILD_DIR ?= $(KRYON_VENDOR_BUILD_DIR)/cmark-gfm
KRYON_CMARK_GFM_A ?= $(KRYON_CMARK_GFM_BUILD_DIR)/src/libcmark-gfm.a
KRYON_CMARK_GFM_EXTENSIONS_A ?= $(KRYON_CMARK_GFM_BUILD_DIR)/extensions/libcmark-gfm-extensions.a
KRYON_CMARK_GFM_INCLUDE ?= -I$(KRYON_CMARK_GFM_DIR)/src -I$(KRYON_CMARK_GFM_DIR)/extensions -I$(KRYON_CMARK_GFM_BUILD_DIR)/src -I$(KRYON_CMARK_GFM_BUILD_DIR)/extensions
KRYON_CMARK_GFM_BUILD_TYPE ?= MinSizeRel
KRYON_MARKDOWN_DEPS ?= $(KRYON_CMARK_GFM_A) $(KRYON_CMARK_GFM_EXTENSIONS_A)
KRYON_MARKDOWN_CFLAGS ?= -DKRYON_HAS_CMARK_GFM=1 $(KRYON_CMARK_GFM_INCLUDE)
KRYON_MARKDOWN_LDLIBS ?= $(KRYON_CMARK_GFM_EXTENSIONS_A) $(KRYON_CMARK_GFM_A)

$(KRYON_CMARK_GFM_A) $(KRYON_CMARK_GFM_EXTENSIONS_A): $(KRYON_CMARK_GFM_DIR)/CMakeLists.txt | $(KRYON_VENDOR_ORDER_ONLY)
	@if [ -f "$(KRYON_CMARK_GFM_BUILD_DIR)/CMakeCache.txt" ] && ! grep -q "CMAKE_HOME_DIRECTORY:INTERNAL=$(abspath $(KRYON_CMARK_GFM_DIR))" "$(KRYON_CMARK_GFM_BUILD_DIR)/CMakeCache.txt"; then \
		rm -rf "$(KRYON_CMARK_GFM_BUILD_DIR)"; \
	fi
	$(CMAKE) -S $(KRYON_CMARK_GFM_DIR) -B $(KRYON_CMARK_GFM_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(KRYON_CMARK_GFM_BUILD_TYPE) \
		-DBUILD_SHARED_LIBS=OFF \
		-DCMARK_TESTS=OFF \
		-DCMARK_SHARED=OFF \
		-DCMARK_STATIC=ON
	$(CMAKE) --build $(KRYON_CMARK_GFM_BUILD_DIR) --target libcmark-gfm_static libcmark-gfm-extensions_static

KRYON_OPENSSL_ROOT_DIR ?= $(OPENSSL_ROOT_DIR)
KRYON_OPENSSL_INCLUDE_DIR ?= $(OPENSSL_INCLUDE_DIR)
KRYON_OPENSSL_SSL_LIBRARY ?= $(OPENSSL_SSL_LIBRARY)
KRYON_OPENSSL_CRYPTO_LIBRARY ?= $(OPENSSL_CRYPTO_LIBRARY)
KRYON_OPENSSL_CMAKE_FLAGS :=
ifneq ($(strip $(KRYON_OPENSSL_ROOT_DIR)),)
KRYON_OPENSSL_CMAKE_FLAGS += -DOPENSSL_ROOT_DIR=$(KRYON_OPENSSL_ROOT_DIR)
endif
ifneq ($(strip $(KRYON_OPENSSL_INCLUDE_DIR)),)
KRYON_OPENSSL_CMAKE_FLAGS += -DOPENSSL_INCLUDE_DIR=$(KRYON_OPENSSL_INCLUDE_DIR)
endif
ifneq ($(strip $(KRYON_OPENSSL_SSL_LIBRARY)),)
KRYON_OPENSSL_CMAKE_FLAGS += -DOPENSSL_SSL_LIBRARY=$(KRYON_OPENSSL_SSL_LIBRARY)
endif
ifneq ($(strip $(KRYON_OPENSSL_CRYPTO_LIBRARY)),)
KRYON_OPENSSL_CMAKE_FLAGS += -DOPENSSL_CRYPTO_LIBRARY=$(KRYON_OPENSSL_CRYPTO_LIBRARY)
endif

KRYON_OPENSSL_SSL_LDLIB ?= $(if $(strip $(KRYON_OPENSSL_SSL_LIBRARY)),$(KRYON_OPENSSL_SSL_LIBRARY),-lssl)
KRYON_OPENSSL_CRYPTO_LDLIB ?= $(if $(strip $(KRYON_OPENSSL_CRYPTO_LIBRARY)),$(KRYON_OPENSSL_CRYPTO_LIBRARY),-lcrypto)
KRYON_CURL_CFLAGS ?= -DCURL_STATICLIB -I$(KRYON_CURL_INCLUDE_DIR)
KRYON_CURL_LDLIBS ?= $(KRYON_CURL_A) $(KRYON_OPENSSL_SSL_LDLIB) $(KRYON_OPENSSL_CRYPTO_LDLIB) -lpthread

$(KRYON_LIBOQS_A): $(KRYON_LIBOQS_DIR)/CMakeLists.txt | $(KRYON_VENDOR_ORDER_ONLY)
	@if [ -f "$(KRYON_LIBOQS_BUILD_DIR)/CMakeCache.txt" ] && ! grep -q "CMAKE_HOME_DIRECTORY:INTERNAL=$(abspath $(KRYON_LIBOQS_DIR))" "$(KRYON_LIBOQS_BUILD_DIR)/CMakeCache.txt"; then \
		rm -rf "$(KRYON_LIBOQS_BUILD_DIR)"; \
	fi
	$(CMAKE) -S $(KRYON_LIBOQS_DIR) -B $(KRYON_LIBOQS_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(KRYON_LIBOQS_BUILD_TYPE) \
		-DBUILD_SHARED_LIBS=OFF \
		-DOQS_BUILD_ONLY_LIB=ON \
		-DOQS_USE_OPENSSL=OFF \
		-DOQS_DIST_BUILD=OFF \
		-DOQS_OPT_TARGET=generic \
		$(KRYON_LIBOQS_CPU_FEATURE_CMAKE_FLAGS) \
		-DOQS_MINIMAL_BUILD=$(KRYON_LIBOQS_MINIMAL_BUILD)
	$(CMAKE) --build $(KRYON_LIBOQS_BUILD_DIR) --target oqs

$(KRYON_WEB_LIBOQS_A): $(KRYON_LIBOQS_DIR)/CMakeLists.txt | $(KRYON_VENDOR_ORDER_ONLY)
	@if [ -f "$(KRYON_WEB_LIBOQS_BUILD_DIR)/CMakeCache.txt" ] && ! grep -q "CMAKE_HOME_DIRECTORY:INTERNAL=$(abspath $(KRYON_LIBOQS_DIR))" "$(KRYON_WEB_LIBOQS_BUILD_DIR)/CMakeCache.txt"; then \
		rm -rf "$(KRYON_WEB_LIBOQS_BUILD_DIR)"; \
	fi
	emcmake $(CMAKE) -S $(KRYON_LIBOQS_DIR) -B $(KRYON_WEB_LIBOQS_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(KRYON_LIBOQS_BUILD_TYPE) \
		-DBUILD_SHARED_LIBS=OFF \
		-DOQS_BUILD_ONLY_LIB=ON \
		-DOQS_USE_OPENSSL=OFF \
		-DOQS_DIST_BUILD=OFF \
		-DOQS_OPT_TARGET=generic \
		$(KRYON_LIBOQS_CPU_FEATURE_CMAKE_FLAGS) \
		-DOQS_MINIMAL_BUILD=$(KRYON_LIBOQS_MINIMAL_BUILD)
	$(CMAKE) --build $(KRYON_WEB_LIBOQS_BUILD_DIR) --target oqs

$(KRYON_CURL_SO): $(KRYON_CURL_DIR)/CMakeLists.txt | $(KRYON_VENDOR_ORDER_ONLY)
	@if [ -f "$(KRYON_CURL_BUILD_DIR)/CMakeCache.txt" ] && ! grep -q "CMAKE_HOME_DIRECTORY:INTERNAL=$(abspath $(KRYON_CURL_DIR))" "$(KRYON_CURL_BUILD_DIR)/CMakeCache.txt"; then \
		rm -rf "$(KRYON_CURL_BUILD_DIR)"; \
	fi
	$(CMAKE) -S $(KRYON_CURL_DIR) -B $(KRYON_CURL_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(KRYON_CURL_BUILD_TYPE) \
		-DCMAKE_INSTALL_PREFIX=$(abspath $(KRYON_CURL_BUILD_DIR)) \
		-DCMAKE_INSTALL_LIBDIR=$(KRYON_CURL_INSTALL_LIBDIR) \
		-DCMAKE_LINK_DEPENDS_USE_LINKER=FALSE \
		-DBUILD_CURL_EXE=OFF \
		-DBUILD_SHARED_LIBS=OFF \
		-DBUILD_STATIC_LIBS=ON \
		-DCURL_USE_OPENSSL=ON \
		$(KRYON_OPENSSL_CMAKE_FLAGS) \
		-DCURL_USE_LIBPSL=OFF \
		-DCURL_USE_LIBSSH2=OFF \
		-DCURL_USE_GSSAPI=OFF \
		-DUSE_NGHTTP2=OFF \
		-DUSE_LIBIDN2=OFF \
		-DCURL_DISABLE_LDAP=ON \
		-DCURL_DISABLE_LDAPS=ON \
		-DCURL_DISABLE_SMB=ON \
		-DENABLE_CURL_MANUAL=OFF \
		-DBUILD_EXAMPLES=OFF \
		-DBUILD_LIBCURL_DOCS=OFF \
		-DBUILD_MISC_DOCS=OFF \
		-DBUILD_TESTING=OFF \
		$(KRYON_CURL_EXTRA_CMAKE_FLAGS)
	$(CMAKE) --build $(KRYON_CURL_BUILD_DIR) --target libcurl_static
	$(CMAKE) --build $(KRYON_CURL_BUILD_DIR) --target install

$(KRYON_CURL_PROTOCOL_CHECK): $(KRYON_CURL_SO)
	@if [ "$(KRYON_CURL_REQUIRE_WEBSOCKETS)" = "1" ]; then \
		sh $(KRYON_CURL_BUILD_DIR)/curl-config --protocols | grep -Eq '(^|[[:space:]])WS([[:space:]]|$$)' || { echo "vendored libcurl was built without WS protocol support"; exit 1; }; \
		sh $(KRYON_CURL_BUILD_DIR)/curl-config --protocols | grep -Eq '(^|[[:space:]])WSS([[:space:]]|$$)' || { echo "vendored libcurl was built without WSS protocol support"; exit 1; }; \
	fi
	@touch $@
