FLINT_DIR ?= vendor/flint
CMAKE ?= cmake
FLINT_VENDOR_BUILD_DIR ?= build/vendor
FLINT_VENDOR_ORDER_ONLY ?=

FLINT_LIBOQS_DIR ?= $(FLINT_DIR)/vendor/liboqs
FLINT_LIBOQS_BUILD_DIR ?= $(FLINT_VENDOR_BUILD_DIR)/liboqs
FLINT_LIBOQS_A ?= $(FLINT_LIBOQS_BUILD_DIR)/lib/liboqs.a
FLINT_LIBOQS_INCLUDE ?= -I$(FLINT_LIBOQS_BUILD_DIR)/include
FLINT_LIBOQS_BUILD_TYPE ?= MinSizeRel
FLINT_LIBOQS_MINIMAL_BUILD ?= SIG_ml_dsa_44
FLINT_LIBOQS_CPU_FEATURE_CMAKE_FLAGS ?= \
	-DOQS_USE_ADX_INSTRUCTIONS=OFF \
	-DOQS_USE_AES_INSTRUCTIONS=OFF \
	-DOQS_USE_AVX_INSTRUCTIONS=OFF \
	-DOQS_USE_AVX2_INSTRUCTIONS=OFF \
	-DOQS_USE_AVX512_INSTRUCTIONS=OFF \
	-DOQS_USE_AVX512BW_INSTRUCTIONS=OFF \
	-DOQS_USE_AVX512DQ_INSTRUCTIONS=OFF \
	-DOQS_USE_AVX512F_INSTRUCTIONS=OFF \
	-DOQS_USE_BMI1_INSTRUCTIONS=OFF \
	-DOQS_USE_BMI2_INSTRUCTIONS=OFF \
	-DOQS_USE_FMA_INSTRUCTIONS=OFF \
	-DOQS_USE_PCLMULQDQ_INSTRUCTIONS=OFF \
	-DOQS_USE_POPCNT_INSTRUCTIONS=OFF \
	-DOQS_USE_SSE_INSTRUCTIONS=OFF \
	-DOQS_USE_SSE2_INSTRUCTIONS=OFF \
	-DOQS_USE_SSE3_INSTRUCTIONS=OFF \
	-DOQS_USE_VPCLMULQDQ_INSTRUCTIONS=OFF

FLINT_WEB_LIBOQS_BUILD_DIR ?= $(FLINT_VENDOR_BUILD_DIR)/web-liboqs
FLINT_WEB_LIBOQS_A ?= $(FLINT_WEB_LIBOQS_BUILD_DIR)/lib/liboqs.a

FLINT_CURL_DIR ?= $(FLINT_DIR)/vendor/curl
FLINT_CURL_BUILD_DIR ?= $(FLINT_VENDOR_BUILD_DIR)/curl
FLINT_CURL_INCLUDE_DIR ?= $(FLINT_CURL_BUILD_DIR)/include
FLINT_VENDOR_UNAME_S := $(shell uname -s 2>/dev/null)
ifeq ($(FLINT_VENDOR_UNAME_S),FreeBSD)
FLINT_CURL_INSTALL_LIBDIR ?= lib
else
FLINT_CURL_INSTALL_LIBDIR ?= lib64
endif
FLINT_CURL_LIB_DIR ?= $(FLINT_CURL_BUILD_DIR)/$(FLINT_CURL_INSTALL_LIBDIR)
FLINT_CURL_A ?= $(FLINT_CURL_LIB_DIR)/libcurl.a
FLINT_CURL_SO ?= $(FLINT_CURL_A)
FLINT_CURL_PROTOCOL_CHECK ?= $(FLINT_CURL_BUILD_DIR)/.protocols-ok
FLINT_CURL_BUILD_TYPE ?= MinSizeRel
FLINT_CURL_EXTRA_CMAKE_FLAGS ?=
FLINT_CURL_REQUIRE_WEBSOCKETS ?= 0

FLINT_OPENSSL_ROOT_DIR ?= $(OPENSSL_ROOT_DIR)
FLINT_OPENSSL_INCLUDE_DIR ?= $(OPENSSL_INCLUDE_DIR)
FLINT_OPENSSL_SSL_LIBRARY ?= $(OPENSSL_SSL_LIBRARY)
FLINT_OPENSSL_CRYPTO_LIBRARY ?= $(OPENSSL_CRYPTO_LIBRARY)
FLINT_OPENSSL_CMAKE_FLAGS :=
ifneq ($(strip $(FLINT_OPENSSL_ROOT_DIR)),)
FLINT_OPENSSL_CMAKE_FLAGS += -DOPENSSL_ROOT_DIR=$(FLINT_OPENSSL_ROOT_DIR)
endif
ifneq ($(strip $(FLINT_OPENSSL_INCLUDE_DIR)),)
FLINT_OPENSSL_CMAKE_FLAGS += -DOPENSSL_INCLUDE_DIR=$(FLINT_OPENSSL_INCLUDE_DIR)
endif
ifneq ($(strip $(FLINT_OPENSSL_SSL_LIBRARY)),)
FLINT_OPENSSL_CMAKE_FLAGS += -DOPENSSL_SSL_LIBRARY=$(FLINT_OPENSSL_SSL_LIBRARY)
endif
ifneq ($(strip $(FLINT_OPENSSL_CRYPTO_LIBRARY)),)
FLINT_OPENSSL_CMAKE_FLAGS += -DOPENSSL_CRYPTO_LIBRARY=$(FLINT_OPENSSL_CRYPTO_LIBRARY)
endif

FLINT_OPENSSL_SSL_LDLIB ?= $(if $(strip $(FLINT_OPENSSL_SSL_LIBRARY)),$(FLINT_OPENSSL_SSL_LIBRARY),-lssl)
FLINT_OPENSSL_CRYPTO_LDLIB ?= $(if $(strip $(FLINT_OPENSSL_CRYPTO_LIBRARY)),$(FLINT_OPENSSL_CRYPTO_LIBRARY),-lcrypto)
FLINT_CURL_CFLAGS ?= -DCURL_STATICLIB -I$(FLINT_CURL_INCLUDE_DIR)
FLINT_CURL_LDLIBS ?= $(FLINT_CURL_A) $(FLINT_OPENSSL_SSL_LDLIB) $(FLINT_OPENSSL_CRYPTO_LDLIB) -lpthread

$(FLINT_LIBOQS_A): $(FLINT_LIBOQS_DIR)/CMakeLists.txt | $(FLINT_VENDOR_ORDER_ONLY)
	@if [ -f "$(FLINT_LIBOQS_BUILD_DIR)/CMakeCache.txt" ] && ! grep -q "CMAKE_HOME_DIRECTORY:INTERNAL=$(abspath $(FLINT_LIBOQS_DIR))" "$(FLINT_LIBOQS_BUILD_DIR)/CMakeCache.txt"; then \
		rm -rf "$(FLINT_LIBOQS_BUILD_DIR)"; \
	fi
	$(CMAKE) -S $(FLINT_LIBOQS_DIR) -B $(FLINT_LIBOQS_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(FLINT_LIBOQS_BUILD_TYPE) \
		-DBUILD_SHARED_LIBS=OFF \
		-DOQS_BUILD_ONLY_LIB=ON \
		-DOQS_USE_OPENSSL=OFF \
		-DOQS_DIST_BUILD=OFF \
		-DOQS_OPT_TARGET=generic \
		$(FLINT_LIBOQS_CPU_FEATURE_CMAKE_FLAGS) \
		-DOQS_MINIMAL_BUILD=$(FLINT_LIBOQS_MINIMAL_BUILD)
	$(CMAKE) --build $(FLINT_LIBOQS_BUILD_DIR) --target oqs

$(FLINT_WEB_LIBOQS_A): $(FLINT_LIBOQS_DIR)/CMakeLists.txt | $(FLINT_VENDOR_ORDER_ONLY)
	@if [ -f "$(FLINT_WEB_LIBOQS_BUILD_DIR)/CMakeCache.txt" ] && ! grep -q "CMAKE_HOME_DIRECTORY:INTERNAL=$(abspath $(FLINT_LIBOQS_DIR))" "$(FLINT_WEB_LIBOQS_BUILD_DIR)/CMakeCache.txt"; then \
		rm -rf "$(FLINT_WEB_LIBOQS_BUILD_DIR)"; \
	fi
	emcmake $(CMAKE) -S $(FLINT_LIBOQS_DIR) -B $(FLINT_WEB_LIBOQS_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(FLINT_LIBOQS_BUILD_TYPE) \
		-DBUILD_SHARED_LIBS=OFF \
		-DOQS_BUILD_ONLY_LIB=ON \
		-DOQS_USE_OPENSSL=OFF \
		-DOQS_DIST_BUILD=OFF \
		-DOQS_OPT_TARGET=generic \
		$(FLINT_LIBOQS_CPU_FEATURE_CMAKE_FLAGS) \
		-DOQS_MINIMAL_BUILD=$(FLINT_LIBOQS_MINIMAL_BUILD)
	$(CMAKE) --build $(FLINT_WEB_LIBOQS_BUILD_DIR) --target oqs

$(FLINT_CURL_SO): $(FLINT_CURL_DIR)/CMakeLists.txt | $(FLINT_VENDOR_ORDER_ONLY)
	@if [ -f "$(FLINT_CURL_BUILD_DIR)/CMakeCache.txt" ] && ! grep -q "CMAKE_HOME_DIRECTORY:INTERNAL=$(abspath $(FLINT_CURL_DIR))" "$(FLINT_CURL_BUILD_DIR)/CMakeCache.txt"; then \
		rm -rf "$(FLINT_CURL_BUILD_DIR)"; \
	fi
	$(CMAKE) -S $(FLINT_CURL_DIR) -B $(FLINT_CURL_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(FLINT_CURL_BUILD_TYPE) \
		-DCMAKE_INSTALL_PREFIX=$(abspath $(FLINT_CURL_BUILD_DIR)) \
		-DCMAKE_INSTALL_LIBDIR=$(FLINT_CURL_INSTALL_LIBDIR) \
		-DCMAKE_LINK_DEPENDS_USE_LINKER=FALSE \
		-DBUILD_CURL_EXE=OFF \
		-DBUILD_SHARED_LIBS=OFF \
		-DBUILD_STATIC_LIBS=ON \
		-DCURL_USE_OPENSSL=ON \
		$(FLINT_OPENSSL_CMAKE_FLAGS) \
		-DCURL_USE_LIBPSL=OFF \
		-DCURL_USE_LIBSSH2=OFF \
		-DCURL_USE_GSSAPI=OFF \
		-DUSE_NGHTTP2=OFF \
		-DUSE_LIBIDN2=OFF \
		-DCURL_DISABLE_LDAP=ON \
		-DCURL_DISABLE_LDAPS=ON \
		-DCURL_DISABLE_SMB=ON \
		-DENABLE_CURL_MANUAL=OFF \
		-DBUILD_EXAMPLES=OFF \
		-DBUILD_LIBCURL_DOCS=OFF \
		-DBUILD_MISC_DOCS=OFF \
		-DBUILD_TESTING=OFF \
		$(FLINT_CURL_EXTRA_CMAKE_FLAGS)
	$(CMAKE) --build $(FLINT_CURL_BUILD_DIR) --target libcurl_static
	$(CMAKE) --build $(FLINT_CURL_BUILD_DIR) --target install

$(FLINT_CURL_PROTOCOL_CHECK): $(FLINT_CURL_SO)
	@if [ "$(FLINT_CURL_REQUIRE_WEBSOCKETS)" = "1" ]; then \
		$(FLINT_CURL_BUILD_DIR)/bin/curl-config --protocols | grep -Eq '(^|[[:space:]])WS([[:space:]]|$$)' || { echo "vendored libcurl was built without WS protocol support"; exit 1; }; \
		$(FLINT_CURL_BUILD_DIR)/bin/curl-config --protocols | grep -Eq '(^|[[:space:]])WSS([[:space:]]|$$)' || { echo "vendored libcurl was built without WSS protocol support"; exit 1; }; \
	fi
	@touch $@
