#!/usr/bin/env sh
set -eu

root="${1:-.}"
cd "$root"

status=0

require_first_line() {
    file=$1
    pattern=$2
    if ! head -n 1 "$file" | grep -Eq "$pattern"; then
        echo "missing generated provenance in first line of $file" >&2
        status=1
    fi
}

require_contains() {
    file=$1
    pattern=$2
    if ! grep -Eq "$pattern" "$file"; then
        echo "missing generated provenance marker in $file" >&2
        status=1
    fi
}

require_first_line include/ui_icon_types.h 'Generated by scripts/embed-icon-sheets\.py'
require_first_line src/ui/ui_icon_names.c 'Generated by scripts/embed-icon-sheets\.py'
require_first_line src/ui/ui_icon_assets.c 'Generated by scripts/embed-icon-sheets\.py'
require_contains src/ui/ui_icon_assets.c 'const unsigned char ui_icon_atlas_png\[\]'
require_contains src/ui/ui_icon_assets.c 'const unsigned char ui_pfp_atlas_png\[\]'
require_contains src/ui/ui_icon_assets.c 'const unsigned char ui_platforms_atlas_png\[\]'
require_contains src/ui/ui_icon_assets.c 'const unsigned char ui_payments_atlas_png\[\]'
require_contains src/ui/ui_icon_assets.c 'const unsigned char ui_language_atlas_png\[\]'
require_contains src/ui/ui_icon_assets.c 'const unsigned char ui_tiles_atlas_png\[\]'
require_contains src/ui/ui_icon_assets.c 'const unsigned char ui_logos_atlas_png\[\]'
require_contains src/ui/ui_icon_assets.c 'const UIIconAsset ui_icon_assets\[\]'
require_contains src/ui/ui_icon_assets.c 'UI_ICON_SHEET_PFP'
require_contains src/ui/ui_icon_assets.c 'UI_ICON_SHEET_LOGOS'
require_contains icons/pfp.json '"icon_count": 25'
require_contains icons/pfp.json '"style": "full-color"'
require_contains icons/ui.json '"style": "mingcute-core-filled"'
require_contains icons/ui.json '"license": "Apache-2.0"'
require_contains icons/ui.json '"upstream_revision"'

icon_output_count=$(find icons -mindepth 1 -maxdepth 1 -type f | wc -l | tr -d ' ')
if [ "$icon_output_count" -ne 14 ]; then
    echo "icons/ must contain exactly 7 spritesheets and 7 manifests" >&2
    status=1
fi
require_first_line docs/PUBLIC_API_SNAPSHOT.txt 'Generated by scripts/public-api-snapshot\.py'
require_contains docs/FEATURE_MATRIX.html 'Generated by scripts/feature-matrix-html\.py'
require_contains docs/site/conformance-matrix.json '"source": "scripts/conformance-matrix.py"'

if [ "$status" -eq 0 ]; then
    echo "generated provenance ok"
fi

exit "$status"
