import assert from "node:assert/strict";
import {createRuntime, beginFrame, endFrame, widget} from "./kryon-runtime.js";

const rt = createRuntime();
const state = {a: "a界β", ca: 6, b: "", cb: 0, readonly: false, commit: false};
let secure = false;
const field = (key, cursor, id) => widget(rt, "TextField",
  `(TextFieldProps){.text = ${key}, .cursor_position = &${cursor}, .focus_id = ${id}, .text_size = 64, .max_codepoints = 6, .secure = ${secure}, .read_only = readonly, .commit_pressed = &commit}`, state);
function draw() {
  beginFrame(rt);
  field("a", "ca", 1);
  field("b", "cb", 2);
  endFrame(rt);
}
rt.SetFocus(1);
draw();
rt.QueueShortcut(65);
rt.QueueShiftKey(263);
draw();
assert.equal(state.ca, 4);
assert.deepEqual(rt.input.selections.get(1), {anchor: 0, cursor: 4});
rt.QueueText("日");
draw();
assert.equal(state.a, "日β");
assert.equal(state.ca, 3);
rt.QueueKey(258);
rt.QueueText("second");
draw();
assert.equal(state.b, "second");
rt.QueueShiftKey(258);
rt.QueueText("界");
draw();
draw();
assert.equal(state.a, "日界β");
assert.equal(state.ca, 6);
// Insertion capacity preserves the existing suffix.
rt.QueueText("12345");
draw();
assert.equal(state.a, "日界123β");
assert.equal(state.ca, 9);
rt.QueueShortcut(65);
rt.QueueShortcut(67);
draw();
assert.equal(rt.ClipboardText(), "日界123β");
secure = true;
rt.SetClipboardText("sentinel");
rt.QueueShortcut(67);
rt.QueueShortcut(88);
draw();
assert.equal(rt.ClipboardText(), "sentinel");
assert.equal(state.a, "日界123β");
state.readonly = true;
rt.QueueText("blocked");
rt.QueueKey(261);
rt.QueueKey(257);
rt.SubmitTextComposition(3, "你", 3, 0);
draw();
assert.equal(state.a, "日界123β");
assert.equal(state.commit, false);
state.readonly = false;
secure = false;
rt.QueueText("base");
draw();
assert.equal(state.a, "base");
rt.SubmitTextComposition(2, "ni", 2, 0);
draw();
assert.equal(state.a, "base");
assert.equal(rt.input.preedit.get(1).text, "ni");
rt.SubmitTextComposition(3, "日本", 6, 0);
draw();
assert.equal(state.a, "base日本");
assert.equal(state.ca, 10);
rt.SubmitTextComposition(2, "ni", 2, 0);
draw();
rt.SubmitTextComposition(4, "", 0, 0);
draw();
assert.equal(state.a, "base日本");
assert.equal(rt.input.preedit.size, 0);
rt.QueueKey(258);
rt.SubmitTextComposition(3, "wrong owner", 0, 0);
draw();
assert.equal(state.b, "second");
rt.QueueKey(256);
rt.QueueText("blocked");
draw();
assert.equal(rt.Focus(), 0);
assert.equal(state.b, "second");

// Multiline movement and word deletion use the same generated intents as native.
const area = {text: "a0\nb1\nc2\nd3\ne4\nf5", cursor: 4};
const drawArea = () => {
  beginFrame(rt);
  widget(rt, "TextArea", "(TextAreaProps){.text = text, .cursor_position = &cursor, .focus_id = 3, .bounds = {0,0,160,60}}", area);
  endFrame(rt);
};
rt.SetFocus(3);
rt.QueueKey(264);
drawArea();
assert.equal(area.cursor, 7);
rt.QueueKey(267);
drawArea();
assert.equal(area.cursor, 13);
rt.QueueKey(266);
drawArea();
assert.equal(area.cursor, 7);
rt.QueueKey(257);
drawArea();
assert.equal(area.text, "a0\nb1\nc\n2\nd3\ne4\nf5");
rt.QueueShortcut(65);
rt.QueueText("alpha beta.gamma");
drawArea();
rt.QueueShortcut(263);
drawArea();
assert.equal(area.cursor, 11);
rt.QueueShortcut(259);
drawArea();
assert.equal(area.text, "alpha betagamma");

// Deferred events must be dropped if focus changes before the destination frame.
rt.SetFocus(2);
draw();
rt.QueueShiftKey(258);
rt.QueueText("stale");
draw();
rt.SetFocus(3);
rt.QueueText("!");
drawArea();
assert.equal(area.text, "alpha beta!gamma");

console.log("web text editing behavior passed");
