# DIS Bytecode Compiler (TaijiOS mkfile)
# Generates DIS bytecode directly from KIR (Kryon Intermediate Representation)

<../../mkconfig

LIB=libdiscodegen.a

SRCS=\
	src/dis_codegen.c\
	src/module_builder.c\
	src/instruction_emitter.c\
	src/type_descriptor.c\
	src/data_section.c\
	src/link_section.c\
	src/kir_translator.c\

CFLAGS=$CFLAGS\
	-Iinclude\
	-Isrc\
	-I../ir/include\
	-I../third_party/cJSON\

LIBRARY=$ROOT/platforms/$OBJDIR/lib/$LIB

default:V: all

all install:V: $LIBRARY

$LIBRARY:V: $SRCS
	for i in $SRCS
	do
		echo "  Compiling $i..."
		$CC $CFLAGS $i || exit 1
	done
	echo "  Archiving into $LIBRARY..."
	$AR $ARFLAGS $LIBRARY *.o
	echo "  Installed $LIB"

clean:V:
	rm -f *.o src/*.o

nuke:V: clean
	rm -f $LIBRARY
