#ifndef KRYON_UI_TREE_KIND_INTERNAL_H
#define KRYON_UI_TREE_KIND_INTERNAL_H

enum {
    WIDGET_SCREEN,
    WIDGET_BACKGROUND,
    WIDGET_TEXT,
    WIDGET_BOX,
    WIDGET_CIRCLE,
    WIDGET_RING,
    WIDGET_LINE,
    WIDGET_TRIANGLE,
    WIDGET_BUTTON,
    WIDGET_TEXT_FIELD,
    WIDGET_TEXT_AREA,
    WIDGET_DROPDOWN,
    WIDGET_SLIDER,
    WIDGET_TOGGLE,
    WIDGET_CHECKBOX,
    WIDGET_PARAGRAPH,
    WIDGET_NAVIGATION_BAR,
    WIDGET_TAB_BAR,
    WIDGET_TITLE_BAR,
    WIDGET_GROUP,
    WIDGET_COLUMN,
    WIDGET_ROW,
    WIDGET_STACK,
    WIDGET_GRID,
    WIDGET_IMAGE,
    WIDGET_CUSTOM,
    WIDGET_DRAG,
    WIDGET_ROUTER,
    WIDGET_CARD,
    WIDGET_KIND_COUNT
};

#endif
