# Kryon CLI Tool (Plan 9 mkfile)
#
# Builds the Kryon CLI for Plan 9/9front
# Requires IR library to be built first

</$objtype/mkfile

TARG=kryon

# Core CLI source files
# Note: Reduced set for Plan 9 (excludes hot reload, web server, etc.)
OFILES=\
	src/main.$O\
	src/utils/string.$O\
	src/utils/file.$O\
	src/utils/args.$O\
	src/utils/paths.$O\
	src/config/config.$O\
	src/commands/cmd_compile.$O\
	src/commands/cmd_run.$O\
	src/commands/cmd_inspect.$O\

# Include directories
CFLAGS=\
	-I./include\
	-I./src\
	-I../ir\
	-I../third_party/cJSON\
	-I../backends/desktop\
	-I../backends/plan9\
	-DPLAN9\
	-DKRYON_PLAN9_BUILD\

# Libraries to link against
# Note: Plan 9 uses different linking than POSIX
LDFLAGS=\
	../ir/libkryon_ir.a\
	../backends/plan9/libplan9_backend.a\

# Standard Plan 9 mkone include for single-target programs
</sys/src/cmd/mkone

# Additional dependencies
src/main.$O: src/main.c
	$CC $CFLAGS src/main.c

src/utils/string.$O: src/utils/string.c
	$CC $CFLAGS src/utils/string.c

src/utils/file.$O: src/utils/file.c
	$CC $CFLAGS src/utils/file.c

src/utils/args.$O: src/utils/args.c
	$CC $CFLAGS src/utils/args.c

src/utils/paths.$O: src/utils/paths.c
	$CC $CFLAGS src/utils/paths.c

src/config/config.$O: src/config/config.c
	$CC $CFLAGS src/config/config.c

src/commands/cmd_compile.$O: src/commands/cmd_compile.c
	$CC $CFLAGS src/commands/cmd_compile.c

src/commands/cmd_run.$O: src/commands/cmd_run.c
	$CC $CFLAGS src/commands/cmd_run.c

src/commands/cmd_inspect.$O: src/commands/cmd_inspect.c
	$CC $CFLAGS src/commands/cmd_inspect.c

# Clean target
clean:V:
	rm -f src/*.$O
	rm -f src/utils/*.$O
	rm -f src/config/*.$O
	rm -f src/commands/*.$O
	rm -f $TARG

# Install target
install:V: $TARG
	cp $TARG /bin/kryon
	echo 'Kryon CLI installed to /bin/kryon'
