# Kryon CLI Tool (TaijiOS mkfile)
# Main kryon command-line tool that orchestrates compilation and execution

<../../mkconfig

TARG=kryon

# All source files
SRCS=\
	src/main.c\
	src/utils/string.c\
	src/utils/file.c\
	src/utils/file_discovery.c\
	src/utils/file_watcher.c\
	src/utils/ws_reload.c\
	src/utils/args.c\
	src/utils/process.c\
	src/utils/json.c\
	src/utils/dev_server.c\
	src/utils/paths.c\
	src/utils/build.c\
	src/utils/plugin_installer.c\
	src/utils/limbo_modules.c\
	src/config/toml_parser.c\
	src/config/config.c\
	src/config/target_handlers.c\
	src/commands/cmd_stubs.c\
	src/commands/cmd_test.c\
	src/commands/cmd_config.c\
	src/commands/cmd_build.c\
	src/commands/cmd_compile.c\
	src/commands/cmd_run.c\
	src/commands/cmd_codegen.c\
	src/commands/cmd_new.c\
	src/commands/cmd_inspect.c\
	src/commands/cmd_diff.c\
	src/commands/cmd_doctor.c\
	src/commands/cmd_plugin.c\
	src/commands/cmd_install.c\
	src/commands/cmd_uninstall.c\
	src/commands/cmd_targets.c\
	src/build/embed_bytecode.c\
	src/build/plugin_discovery.c\
	src/build/c_desktop.c\
	src/template/docs_template.c\

# Compiler flags
CFLAGS=$CFLAGS\
	-I./include\
	-I./src\
	-I../ir/include\
	-I../include\
	-I../third_party/cJSON\
	-I../codegens\
	-I../codegens/web\
	-I../codegens/c\
	-I../codegens/limbo\
	-I../codegens/tcltk\
	-I../dis/include\
	-D__TAIJIOS__\

# Libraries to link against (in correct dependency order)
LIBS=\
	kryon_codegen_limbo\
	kryon_codegen_tcltk\
	kryon_codegen_web\
	kryon_codegen_c\
	kryon_codegen_kry\
	kryon_codegen_markdown\
	kryon_codegen_common\
	discodegen\
	kryon_ir\
	cJSON\
	tomlc99\
	bio\
	9\

BIN=$ROOT/$OBJDIR/bin

# Build the kryon binary
$O.out:V: $SRCS
	echo "  Compiling CLI sources..."
	for i in $SRCS
	do
		$CC $CFLAGS $i || exit 1
	done
	echo "  Linking kryon binary..."
	$LD $LDFLAGS -o $O.out *.o $ROOT/$OBJDIR/lib/libkryon_codegen_limbo.a $ROOT/$OBJDIR/lib/libkryon_codegen_tcltk.a $ROOT/$OBJDIR/lib/libkryon_codegen_web.a $ROOT/$OBJDIR/lib/libkryon_codegen_c.a $ROOT/$OBJDIR/lib/libkryon_codegen_kry.a $ROOT/$OBJDIR/lib/libkryon_codegen_markdown.a $ROOT/$OBJDIR/lib/libkryon_codegen_common.a $ROOT/$OBJDIR/lib/libdiscodegen.a $ROOT/$OBJDIR/lib/libkryon_ir.a $ROOT/$OBJDIR/lib/libcJSON.a $ROOT/$OBJDIR/lib/libtomlc99.a $ROOT/$OBJDIR/lib/libbio.a $ROOT/$OBJDIR/lib/lib9.a -lm -lpthread -ldl
	echo "  Built kryon"

$BIN/$TARG: $O.out
	rm -f $BIN/$TARG && cp $O.out $BIN/$TARG

all:V: $O.out

install:V: $BIN/$TARG
	echo "  Installed kryon to $BIN/$TARG"

clean:V:
	rm -f *.o src/*.o src/*/*.o $O.out

nuke:V: clean
	rm -f $BIN/$TARG
