# Limbo Codegen (TaijiOS mkfile)
# Generates Limbo source code from Kryon IR via TKIR

<../../../mkconfig

LIB=libkryon_codegen_limbo.a

OFILES=\
	limbo_codegen.$O\
	limbo_from_wir.$O\

HFILES=\
	limbo_codegen.h\
	../codegen_common.h\
	../wir/wir.h\
	../wir/wir_builder.h\
	../wir/wir_emitter.h\

CFLAGS=$CFLAGS\
	-I../../include\
	-I../../ir/include\
	-I../../third_party/cJSON\
	-I..\
	-I../wir\

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
