# Limbo Codegen (TaijiOS mkfile)
# Generates Limbo source code from Kryon IR via TKIR

<../../../mkconfig

LIB=libkryon_codegen_limbo.a

OFILES=\
	limbo_codegen.$O\
	limbo_from_tkir.$O\

HFILES=\
	limbo_codegen.h\
	../codegen_common.h\
	../tkir/tkir.h\
	../tkir/tkir_builder.h\
	../tkir/tkir_emitter.h\

CFLAGS=$CFLAGS\
	-I../../include\
	-I../../ir/include\
	-I../../third_party/cJSON\
	-I..\
	-I../tkir\

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
