# TKIR Codegen (TaijiOS mkfile)
# Toolkit Intermediate Representation

<../../../mkconfig

LIB=libkryon_tkir.a

OFILES=\
	tkir.$O\
	tkir_builder.$O\
	tkir_emitter.$O\

HFILES=\
	tkir.h\
	tkir_builder.h\
	tkir_emitter.h\
	../codegen_common.h\

CFLAGS=$CFLAGS\
	-I../../include\
	-I../../ir/include\
	-I../../third_party/cJSON\
	-I..\

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
