// Code generated by k2go from runtime/app_host_props.kry. DO NOT EDIT.
package kryon

// #import kryon_compat.generated.h
type KryonInputOverride struct {
	Enabled       int32
	MouseInside   int32
	PassButtons   int32
	PassKeyboard  int32
	MousePosition Vector2
	MouseDelta    Vector2
}

const APPHOSTABIVERSION = 6
