// Code generated by k2go from runtime/core_props.kry. DO NOT EDIT.
package kryon

// #import kryon_compat.generated.h
// #import ui_input_props.generated.h
var UiViewWidth int32 = 320
var UiViewHeight int32 = 560
