// Code generated by k2go from runtime/drag_drop.kry. DO NOT EDIT.
package kryon

type DragDropSourceDecision struct {
	ClearSource   bool
	Valid         bool
	StartSource   bool
	ReturnsActive bool
}

type DragDropTargetDecision struct {
	Accepted       bool
	CopySize       int32
	ClearSource    bool
	ConsumeRelease bool
}

func DragDrop_DragDropShouldClearSource(active bool, active_source_id int32, source_id int32, mouse_down bool, mouse_released bool) bool {
	var value_0 bool = active
	if value_0 {
		value_0 = (active_source_id == source_id)
	}
	var value_1 bool = value_0
	if value_1 {
		value_1 = !mouse_down
	}
	var value_2 bool = value_1
	if value_2 {
		value_2 = !mouse_released
	}
	return value_2
}

func DragDrop_DragDropSourceValid(disabled bool, content_disabled bool, has_type bool, data_size int32, max_size int32, has_data bool) bool {
	var value_0 bool = disabled
	if !value_0 {
		value_0 = content_disabled
	}
	var value_1 bool = value_0
	if !value_1 {
		value_1 = !has_type
	}
	if value_1 {
		return false
	}
	var value_2 bool = (max_size >= 0)
	if value_2 {
		value_2 = (data_size > max_size)
	}
	if value_2 {
		return false
	}
	if data_size < 0 {
		return false
	}
	var value_3 bool = (data_size > 0)
	if value_3 {
		value_3 = !has_data
	}
	if value_3 {
		return false
	}
	return true
}

func DragDrop_DragDropSourceStarts(valid bool, hot bool, mouse_pressed bool) bool {
	var value_0 bool = valid
	if value_0 {
		value_0 = hot
	}
	var value_1 bool = value_0
	if value_1 {
		value_1 = mouse_pressed
	}
	return value_1
}

func DragDrop_DragDropSourceReturnsActive(active bool, active_source_id int32, source_id int32, mouse_down bool, mouse_released bool) bool {
	var value_0 bool = active
	if value_0 {
		value_0 = (active_source_id == source_id)
	}
	var value_1 bool = value_0
	if value_1 {
		var value_2 bool = mouse_down
		if !value_2 {
			value_2 = mouse_released
		}
		value_1 = value_2
	}
	return value_1
}

func DragDrop_DragDropTargetMatches(active bool, has_type bool, same_type bool) bool {
	var value_0 bool = active
	if value_0 {
		value_0 = has_type
	}
	var value_1 bool = value_0
	if value_1 {
		value_1 = same_type
	}
	return value_1
}

func DragDrop_DragDropTargetHot(disabled bool, content_disabled bool, pointer_hot bool) bool {
	var value_0 bool = !disabled
	if value_0 {
		value_0 = !content_disabled
	}
	var value_1 bool = value_0
	if value_1 {
		value_1 = pointer_hot
	}
	return value_1
}

func DragDrop_DragDropTargetAccepts(disabled bool, content_disabled bool, matches bool, hot bool, mouse_released bool) bool {
	var value_0 bool = !disabled
	if value_0 {
		value_0 = !content_disabled
	}
	var value_1 bool = value_0
	if value_1 {
		value_1 = matches
	}
	var value_2 bool = value_1
	if value_2 {
		value_2 = hot
	}
	var value_3 bool = value_2
	if value_3 {
		value_3 = mouse_released
	}
	return value_3
}

func DragDrop_DragDropCopySize(data_size int32, output_size int32) int32 {
	if data_size < 0 {
		data_size = 0
	}
	if output_size < 0 {
		output_size = 0
	}
	if data_size < output_size {
		return data_size
	}
	return output_size
}

func DragDrop_DragDropSourceDecisionFor(active bool, active_source_id int32, source_id int32, disabled bool, content_disabled bool, has_type bool, data_size int32, max_size int32, has_data bool, hot bool, mouse_pressed bool, mouse_down bool, mouse_released bool) DragDropSourceDecision {
	var decision DragDropSourceDecision = DragDropSourceDecision{}
	var value_0 bool = DragDrop_DragDropShouldClearSource(active, active_source_id, source_id, mouse_down, mouse_released)
	decision.ClearSource = value_0
	var value_1 bool = DragDrop_DragDropSourceValid(disabled, content_disabled, has_type, data_size, max_size, has_data)
	decision.Valid = value_1
	var value_2 bool = decision.Valid
	var value_3 bool = DragDrop_DragDropSourceStarts(value_2, hot, mouse_pressed)
	decision.StartSource = value_3
	var value_4 bool = DragDrop_DragDropSourceReturnsActive(active, active_source_id, source_id, mouse_down, mouse_released)
	var value_5 bool = value_4
	if !value_5 {
		var value_6 bool = decision.StartSource
		var value_7 bool = DragDrop_DragDropSourceReturnsActive(value_6, source_id, source_id, mouse_down, mouse_released)
		value_5 = value_7
	}
	decision.ReturnsActive = value_5
	return decision
}

func DragDrop_DragDropTargetDecisionFor(disabled bool, content_disabled bool, active bool, has_type bool, same_type bool, hot bool, mouse_released bool, data_size int32, output_size int32) DragDropTargetDecision {
	var decision DragDropTargetDecision = DragDropTargetDecision{}
	var value_0 bool = DragDrop_DragDropTargetMatches(active, has_type, same_type)
	var matches bool = value_0
	var value_1 bool = DragDrop_DragDropTargetAccepts(disabled, content_disabled, matches, hot, mouse_released)
	decision.Accepted = value_1
	if decision.Accepted {
		var value_2 int32 = DragDrop_DragDropCopySize(data_size, output_size)
		decision.CopySize = value_2
		decision.ClearSource = true
		decision.ConsumeRelease = true
	}
	return decision
}
