// Code generated by k2go from runtime/drawing_props.kry. DO NOT EDIT.
package kryon

// #import kryon_compat.generated.h
type Vector2 struct {
	X float32
	Y float32
}

type Rectangle struct {
	X      float32
	Y      float32
	Width  float32
	Height float32
}

type Color struct {
	R uint8
	G uint8
	B uint8
	A uint8
}

type Texture2D struct {
	ID      uint32
	Width   int32
	Height  int32
	Mipmaps int32
	Format  int32
}
