// Code generated by k2go from runtime/dropdown.kry. DO NOT EDIT.
package kryon

// #import style
// #import button
// #import surface
// #import control_props
type ContentMetrics struct {
	Padding float32
	Gap     float32
	Icon    float32
	Font    float32
}

type DropdownTriggerMetrics struct {
	MinWidth         int32
	MinHeight        int32
	IndicatorPadding int32
	IndicatorSize    int32
	TextIndicatorGap int32
}

type DropdownTriggerContent struct {
	IconBounds       Rectangle
	TextBounds       Rectangle
	ClipBounds       Rectangle
	IndicatorCenterX int32
	IndicatorCenterY int32
}

type DropdownTriggerInput struct {
	Enter bool
	Space bool
	Down  bool
}

type DropdownMenuInput struct {
	Navigating bool
	Up         bool
	Down       bool
	Home       bool
	End        bool
	Commit     bool
	Escape     bool
}

type DropdownOpenDecision struct {
	Open    bool
	Changed bool
	Opened  bool
	Closed  bool
}

type DropdownIndicator struct {
	X1 int32
	Y1 int32
	X2 int32
	Y2 int32
	X3 int32
	Y3 int32
	X4 int32
	Y4 int32
}

type Navigation struct {
	Index     int32
	Previous  int32
	Count     int32
	Direction int32
	Phase     int32
	Searching bool
	Result    int32
}

type MenuLayout struct {
	ContentBounds   Rectangle
	ScrollbarBounds Rectangle
	OptionWidth     int32
	ContentHeight   int32
	MaxScroll       int32
}

type OptionPaint struct {
	OptionY         int32
	VisibleBounds   Rectangle
	HighlightBounds Rectangle
}

type DropdownOptionContent struct {
	IconBounds      Rectangle
	TextBounds      Rectangle
	ClipBounds      Rectangle
	CheckBounds     Rectangle
	SeparatorBounds Rectangle
}

type DropdownMenuMetrics struct {
	PaddingTop          int32
	PaddingBottom       int32
	ScrollbarWidth      int32
	ScrollbarGap        int32
	ScrollbarTrackInset int32
	HighlightInsetX     int32
	HighlightInsetY     int32
	SeparatorInset      int32
	DragThreshold       int32
}

type VisibleRows struct {
	First int32
	End   int32
}

type PopupGesture struct {
	Pressed      bool
	Dragging     bool
	OriginY      float32
	OriginOffset int32
	Offset       int32
}

func Dropdown_DropdownPanelRole() int32 {
	return 2
}

func Dropdown_DropdownOptionRole() int32 {
	return 26
}

func Dropdown_DropdownScrollbarRole() int32 {
	return 27
}

func Dropdown_Appearance(base StyleData, accent StyleData, role int32, state int32, selected bool) StyleData {
	var value_0 int32 = Dropdown_DropdownOptionRole()
	var value_1 bool = (role == value_0)
	if value_1 {
		value_1 = selected
	}
	var value_2 bool = value_1
	if value_2 {
		value_2 = (state != int32(ButtonStateDisabled))
	}
	if value_2 {
		return accent
	}
	return base
}

func Dropdown_Content(paint StyleData, scale float32) ContentMetrics {
	if scale <= 0.0 {
		scale = 1.0
	}
	var value_0 ContentMetrics = ContentMetrics{}
	value_0.Padding = (paint.PaddingX * scale)
	value_0.Gap = (paint.Gap * scale)
	value_0.Icon = (paint.IconSize * scale)
	value_0.Font = (paint.FontSize * scale)
	return value_0
}

func Dropdown_DropdownMetric(fields uint32, field uint32, value float32, fallback float32, scale float32, allow_zero bool) int32 {
	if scale <= 0.0 {
		scale = 1.0
	}
	var value_0 bool = (uint32(number_runtime_bits(uint64(fields), uint64(field), 32, false, 8))) == uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0))
	var value_1 bool = value_0
	if !value_1 {
		value_1 = (value < 0.0)
	}
	var value_2 bool = value_1
	if !value_2 {
		var value_3 bool = !allow_zero
		if value_3 {
			value_3 = (value <= 0.0)
		}
		value_2 = value_3
	}
	if value_2 {
		value = fallback
	}
	var value_4 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((value*scale)), 32, true)), uint64(0), 32, true, 0))
	return value_4
}

func Dropdown_DropdownTriggerMetricsFor(scale float32, trigger StyleFrame) DropdownTriggerMetrics {
	if scale <= 0.0 {
		scale = 1.0
	}
	var metrics DropdownTriggerMetrics = DropdownTriggerMetrics{}
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((32.0*scale)), 32, true)), uint64(0), 32, true, 0))
	metrics.MinWidth = value_0
	var value_1 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((24.0*scale)), 32, true)), uint64(0), 32, true, 0))
	metrics.MinHeight = value_1
	var value_2 uint32 = trigger.Value.Fields
	var value_3 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_4 float32 = trigger.Value.OffsetX
	var value_5 float32 = 24.0
	var value_6 int32 = Dropdown_DropdownMetric(value_2, value_3, value_4, value_5, scale, true)
	metrics.IndicatorPadding = value_6
	var value_7 uint32 = trigger.Value.Fields
	var value_8 uint32 = uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))
	var value_9 float32 = trigger.Value.IconSize
	var value_10 float32 = 10.0
	var value_11 int32 = Dropdown_DropdownMetric(value_7, value_8, value_9, value_10, scale, true)
	metrics.IndicatorSize = value_11
	var value_12 uint32 = trigger.Value.Fields
	var value_13 uint32 = uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))
	var value_14 float32 = trigger.Value.Gap
	var value_15 float32 = 8.0
	var value_16 int32 = Dropdown_DropdownMetric(value_12, value_13, value_14, value_15, scale, true)
	metrics.TextIndicatorGap = value_16
	return metrics
}

func Dropdown_DropdownIndicatorFor(center_x int32, center_y int32, size int32, open bool) DropdownIndicator {
	if size < 0 {
		size = 0
	}
	var half int32 = (int32(number_runtime_bits(uint64(size), uint64(2), 32, true, 4)))
	var left int32 = (int32(number_runtime_bits(uint64(center_x), uint64(half), 32, true, 2)))
	var right int32 = (int32(number_runtime_bits(uint64(center_x), uint64(half), 32, true, 1)))
	var value_0 int32 = int32(number_runtime_bits(uint64(center_y), uint64((int32(number_runtime_bits(uint64(half), uint64(2), 32, true, 4)))), 32, true, 2))
	var upper int32 = value_0
	var value_1 int32 = int32(number_runtime_bits(uint64(center_y), uint64((int32(number_runtime_bits(uint64(half), uint64(2), 32, true, 4)))), 32, true, 1))
	var lower int32 = value_1
	if open {
		var value_2 DropdownIndicator = DropdownIndicator{}
		value_2.X1 = left
		value_2.Y1 = lower
		value_2.X2 = center_x
		value_2.Y2 = upper
		value_2.X3 = center_x
		value_2.Y3 = upper
		value_2.X4 = right
		value_2.Y4 = lower
		return value_2
	}
	var value_3 DropdownIndicator = DropdownIndicator{}
	value_3.X1 = left
	value_3.Y1 = upper
	value_3.X2 = center_x
	value_3.Y2 = lower
	value_3.X3 = center_x
	value_3.Y3 = lower
	value_3.X4 = right
	value_3.Y4 = upper
	return value_3
}

func Dropdown_DropdownTriggerContentFor(bounds Rectangle, content ContentMetrics, metrics DropdownTriggerMetrics, has_icon bool) DropdownTriggerContent {
	var layout DropdownTriggerContent = DropdownTriggerContent{}
	var text_x float32 = (bounds.X + content.Padding)
	var text_right float32 = 0
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((bounds.X+bounds.Width)), 32, true)), uint64(0), 32, true, 0))
	layout.IndicatorCenterX = (int32(number_runtime_bits(uint64(value_0), uint64(metrics.IndicatorPadding), 32, true, 2)))
	var value_1 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(bounds.Y), 32, true)), uint64(0), 32, true, 0))
	var value_2 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(bounds.Height), 32, true)), uint64(0), 32, true, 0))
	var value_3 int32 = int32(number_runtime_bits(uint64(value_1), uint64((int32(number_runtime_bits(uint64(value_2), uint64(2), 32, true, 4)))), 32, true, 1))
	layout.IndicatorCenterY = value_3
	if has_icon {
		layout.IconBounds.X = text_x
		layout.IconBounds.Y = (bounds.Y + ((bounds.Height - content.Icon) / 2.0))
		layout.IconBounds.Width = content.Icon
		layout.IconBounds.Height = content.Icon
		var value_4 float32 = text_x
		text_x = value_4 + (content.Icon + content.Gap)
	}
	var value_5 int32 = int32(number_runtime_bits(uint64(layout.IndicatorCenterX), uint64(metrics.IndicatorSize), 32, true, 2))
	var value_6 float32 = float32((int32(number_runtime_bits(uint64(value_5), uint64(metrics.TextIndicatorGap), 32, true, 2))))
	text_right = value_6
	layout.ClipBounds.X = text_x
	layout.ClipBounds.Y = bounds.Y
	layout.ClipBounds.Width = (text_right - text_x)
	layout.ClipBounds.Height = bounds.Height
	if layout.ClipBounds.Width < 0.0 {
		layout.ClipBounds.Width = 0.0
	}
	layout.TextBounds = layout.ClipBounds
	return layout
}

func Dropdown_ClampIndex(value int32, count int32) int32 {
	if count <= 0 {
		return -1
	}
	if value < 0 {
		return 0
	}
	if value >= count {
		return (int32(number_runtime_bits(uint64(count), uint64(1), 32, true, 2)))
	}
	return value
}

func Dropdown_DropdownOptionCountFor(count int32) int32 {
	if count < 0 {
		return 0
	}
	return count
}

func Dropdown_DropdownCurrentIndexFor(selected int32, count int32) int32 {
	var value_0 int32 = Dropdown_ClampIndex(selected, count)
	var index int32 = value_0
	if index < 0 {
		return 0
	}
	return index
}

func Dropdown_Trigger(open bool, disabled bool, count int32, focused bool, keyboard bool, activated bool, enter bool, space bool, down bool) bool {
	var value_0 bool = disabled
	if !value_0 {
		value_0 = (count <= 0)
	}
	if value_0 {
		return false
	}
	if activated {
		return !open
	}
	var value_1 bool = !open
	if value_1 {
		value_1 = focused
	}
	var value_2 bool = value_1
	if value_2 {
		value_2 = keyboard
	}
	var value_3 bool = value_2
	if value_3 {
		var value_4 bool = enter
		if !value_4 {
			value_4 = space
		}
		var value_5 bool = value_4
		if !value_5 {
			value_5 = down
		}
		value_3 = value_5
	}
	if value_3 {
		return true
	}
	return open
}

func Dropdown_DropdownTriggerInputFor(enter_pressed bool, keypad_enter_pressed bool, space_pressed bool, down_pressed bool) DropdownTriggerInput {
	var input DropdownTriggerInput = DropdownTriggerInput{}
	var value_0 bool = enter_pressed
	if !value_0 {
		value_0 = keypad_enter_pressed
	}
	input.Enter = value_0
	input.Space = space_pressed
	input.Down = down_pressed
	return input
}

func Dropdown_DropdownMenuInputFor(keyboard_available bool, opening bool, up_pressed bool, down_pressed bool, home_pressed bool, end_pressed bool, enter_pressed bool, keypad_enter_pressed bool, escape_pressed bool) DropdownMenuInput {
	var input DropdownMenuInput = DropdownMenuInput{}
	if !keyboard_available {
		return input
	}
	input.Escape = escape_pressed
	if !opening {
		input.Up = up_pressed
		input.Down = down_pressed
		input.Home = home_pressed
		input.End = end_pressed
		var value_0 bool = input.Up
		if !value_0 {
			value_0 = input.Down
		}
		var value_1 bool = value_0
		if !value_1 {
			value_1 = input.Home
		}
		var value_2 bool = value_1
		if !value_2 {
			value_2 = input.End
		}
		input.Navigating = value_2
		var value_3 bool = enter_pressed
		if !value_3 {
			value_3 = keypad_enter_pressed
		}
		input.Commit = value_3
	}
	return input
}

func Dropdown_Dismiss(open bool, opening bool, count int32, height float32, escape bool, lost_focus bool, outside bool) bool {
	var value_0 bool = open
	if value_0 {
		var value_1 bool = (count <= 0)
		if !value_1 {
			value_1 = (height <= 0.0)
		}
		var value_2 bool = value_1
		if !value_2 {
			value_2 = escape
		}
		var value_3 bool = value_2
		if !value_3 {
			value_3 = lost_focus
		}
		var value_4 bool = value_3
		if !value_4 {
			var value_5 bool = !opening
			if value_5 {
				value_5 = outside
			}
			value_4 = value_5
		}
		value_0 = value_4
	}
	return value_0
}

func Dropdown_DropdownOpenDecisionFor(open bool, disabled bool, count int32, focused bool, keyboard bool, activated bool, trigger DropdownTriggerInput, height float32, escape bool, lost_focus bool, outside bool) DropdownOpenDecision {
	var decision DropdownOpenDecision = DropdownOpenDecision{}
	var value_0 bool = trigger.Enter
	var value_1 bool = trigger.Space
	var value_2 bool = trigger.Down
	var value_3 bool = Dropdown_Trigger(open, disabled, count, focused, keyboard, activated, value_0, value_1, value_2)
	var next bool = value_3
	var value_4 bool = (next != open)
	if value_4 {
		value_4 = next
	}
	var opening bool = value_4
	var value_5 bool = Dropdown_Dismiss(next, opening, count, height, escape, lost_focus, outside)
	if value_5 {
		next = false
	}
	decision.Open = next
	decision.Changed = (next != open)
	var value_6 bool = decision.Changed
	if value_6 {
		value_6 = next
	}
	decision.Opened = value_6
	var value_7 bool = decision.Changed
	if value_7 {
		value_7 = !next
	}
	decision.Closed = value_7
	return decision
}

func Dropdown_DropdownOpenAfterCommit(open bool, committed bool) DropdownOpenDecision {
	var decision DropdownOpenDecision = DropdownOpenDecision{}
	decision.Open = open
	if committed {
		decision.Open = false
	}
	decision.Changed = (decision.Open != open)
	var value_0 bool = decision.Changed
	if value_0 {
		value_0 = decision.Open
	}
	decision.Opened = value_0
	var value_1 bool = decision.Changed
	if value_1 {
		value_1 = !decision.Open
	}
	decision.Closed = value_1
	return decision
}

func Dropdown_StartNavigation(current int32, count int32, up bool, down bool, home bool, end bool) Navigation {
	var value_0 int32 = Dropdown_ClampIndex(current, count)
	current = value_0
	var value_1 Navigation = Navigation{}
	value_1.Index = current
	value_1.Previous = current
	value_1.Count = count
	value_1.Direction = 1
	value_1.Searching = (count > 0)
	value_1.Result = -1
	var nav Navigation = value_1
	if up {
		var value_2 int32 = (int32(number_runtime_bits(uint64(current), uint64(1), 32, true, 2)))
		var value_3 int32 = Dropdown_ClampIndex(value_2, count)
		nav.Index = value_3
		nav.Direction = -1
	} else {
		if down {
			var value_4 int32 = (int32(number_runtime_bits(uint64(current), uint64(1), 32, true, 1)))
			var value_5 int32 = Dropdown_ClampIndex(value_4, count)
			nav.Index = value_5
		} else {
			if home {
				nav.Index = 0
			} else {
				if end {
					nav.Index = (int32(number_runtime_bits(uint64(count), uint64(1), 32, true, 2)))
					nav.Direction = -1
				}
			}
		}
	}
	return nav
}

func Dropdown_ScanNavigation(nav Navigation, enabled bool) Navigation {
	if !nav.Searching {
		return nav
	}
	if enabled {
		nav.Result = nav.Index
		nav.Searching = false
		return nav
	}
	if nav.Phase == 1 {
		nav.Phase = 2
		nav.Direction = int32(number_runtime_bits(uint64(0), uint64(nav.Direction), 32, true, 2))
	}
	var value_0 int32 = nav.Index
	nav.Index = int32(number_runtime_bits(uint64(value_0), uint64(nav.Direction), 32, true, 1))
	var value_1 bool = (nav.Index < 0)
	if !value_1 {
		value_1 = (nav.Index >= nav.Count)
	}
	if value_1 {
		if nav.Phase == 0 {
			nav.Index = nav.Previous
			nav.Phase = 1
		} else {
			nav.Searching = false
			nav.Result = -1
		}
	}
	return nav
}

func Dropdown_CanCommit(enabled bool, opening bool, keyboard bool, enter bool, pointer bool, scrollbar bool, dragging bool, returned bool) bool {
	var value_0 bool = enabled
	if value_0 {
		value_0 = !opening
	}
	var value_1 bool = value_0
	if value_1 {
		var value_2 bool = keyboard
		if value_2 {
			value_2 = enter
		}
		var value_3 bool = value_2
		if !value_3 {
			var value_4 bool = pointer
			if value_4 {
				value_4 = !scrollbar
			}
			var value_5 bool = value_4
			if value_5 {
				var value_6 bool = !dragging
				if !value_6 {
					value_6 = returned
				}
				value_5 = value_6
			}
			value_3 = value_5
		}
		value_1 = value_3
	}
	return value_1
}

func Dropdown_ContentHeight(count int32, row float32, padding float32) int32 {
	var height float64 = ((float64(count) * float64(row)) + float64(padding))
	if height <= 0.0 {
		return 0
	}
	if height >= 2147483647.0 {
		return 2147483647
	}
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(height), 32, true)), uint64(0), 32, true, 0))
	return value_0
}

func Dropdown_DropdownMenuMetricsFor(scale float32, panel StyleFrame, option StyleFrame, scrollbar StyleFrame) DropdownMenuMetrics {
	var metrics DropdownMenuMetrics = DropdownMenuMetrics{}
	var value_0 uint32 = panel.Value.Fields
	var value_1 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0))
	var value_2 float32 = panel.Value.PaddingY
	var value_3 float32 = 4.0
	var value_4 int32 = Dropdown_DropdownMetric(value_0, value_1, value_2, value_3, scale, true)
	metrics.PaddingTop = value_4
	metrics.PaddingBottom = metrics.PaddingTop
	var value_5 uint32 = scrollbar.Value.Fields
	var value_6 uint32 = uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))
	var value_7 float32 = scrollbar.Value.IconSize
	var value_8 float32 = 8.0
	var value_9 int32 = Dropdown_DropdownMetric(value_5, value_6, value_7, value_8, scale, true)
	metrics.ScrollbarWidth = value_9
	var value_10 uint32 = scrollbar.Value.Fields
	var value_11 uint32 = uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))
	var value_12 float32 = scrollbar.Value.Gap
	var value_13 float32 = 2.0
	var value_14 int32 = Dropdown_DropdownMetric(value_10, value_11, value_12, value_13, scale, true)
	metrics.ScrollbarGap = value_14
	var value_15 uint32 = scrollbar.Value.Fields
	var value_16 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0))
	var value_17 float32 = scrollbar.Value.PaddingY
	var value_18 float32 = 2.0
	var value_19 int32 = Dropdown_DropdownMetric(value_15, value_16, value_17, value_18, scale, true)
	metrics.ScrollbarTrackInset = value_19
	var value_20 uint32 = option.Value.Fields
	var value_21 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))
	var value_22 float32 = option.Value.PaddingX
	var value_23 float32 = 4.0
	var value_24 int32 = Dropdown_DropdownMetric(value_20, value_21, value_22, value_23, scale, true)
	metrics.HighlightInsetX = value_24
	var value_25 uint32 = option.Value.Fields
	var value_26 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0))
	var value_27 float32 = option.Value.PaddingY
	var value_28 float32 = 2.0
	var value_29 int32 = Dropdown_DropdownMetric(value_25, value_26, value_27, value_28, scale, true)
	metrics.HighlightInsetY = value_29
	var value_30 uint32 = option.Value.Fields
	var value_31 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_32 float32 = option.Value.OffsetX
	var value_33 float32 = 16.0
	var value_34 int32 = Dropdown_DropdownMetric(value_30, value_31, value_32, value_33, scale, true)
	metrics.SeparatorInset = value_34
	var value_35 uint32 = scrollbar.Value.Fields
	var value_36 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_37 float32 = scrollbar.Value.OffsetX
	var value_38 float32 = 8.0
	var value_39 int32 = Dropdown_DropdownMetric(value_35, value_36, value_37, value_38, scale, false)
	metrics.DragThreshold = value_39
	return metrics
}

func Dropdown_MenuLayoutFor(bounds Rectangle, count int32, row_height int32, padding_top int32, padding_bottom int32, scrollbar_width int32, scrollbar_gap int32) MenuLayout {
	var layout MenuLayout = MenuLayout{}
	var value_0 float32 = float32(row_height)
	var value_1 float32 = float32((int32(number_runtime_bits(uint64(padding_top), uint64(padding_bottom), 32, true, 1))))
	var value_2 int32 = Dropdown_ContentHeight(count, value_0, value_1)
	layout.ContentHeight = value_2
	var value_3 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(bounds.Height), 32, true)), uint64(0), 32, true, 0))
	layout.MaxScroll = (int32(number_runtime_bits(uint64(layout.ContentHeight), uint64(value_3), 32, true, 2)))
	if layout.MaxScroll < 0 {
		layout.MaxScroll = 0
	}
	var value_4 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(bounds.Width), 32, true)), uint64(0), 32, true, 0))
	layout.OptionWidth = value_4
	if layout.MaxScroll > 0 {
		var value_5 int32 = layout.OptionWidth
		layout.OptionWidth = int32(number_runtime_bits(uint64(value_5), uint64((int32(number_runtime_bits(uint64(scrollbar_width), uint64(scrollbar_gap), 32, true, 1)))), 32, true, 2))
		if layout.OptionWidth < 0 {
			layout.OptionWidth = 0
		}
	}
	layout.ContentBounds.X = bounds.X
	layout.ContentBounds.Y = (bounds.Y + float32(padding_top))
	layout.ContentBounds.Width = float32(layout.OptionWidth)
	var value_6 float32 = bounds.Height - float32((int32(number_runtime_bits(uint64(padding_top), uint64(padding_bottom), 32, true, 1))))
	layout.ContentBounds.Height = value_6
	if layout.ContentBounds.Height < 0.0 {
		layout.ContentBounds.Height = 0.0
	}
	layout.ScrollbarBounds.X = ((bounds.X + bounds.Width) - float32(scrollbar_width))
	layout.ScrollbarBounds.Y = bounds.Y
	layout.ScrollbarBounds.Width = float32(scrollbar_width)
	layout.ScrollbarBounds.Height = bounds.Height
	if layout.ScrollbarBounds.Width < 0.0 {
		layout.ScrollbarBounds.Width = 0.0
	}
	if layout.ScrollbarBounds.Height < 0.0 {
		layout.ScrollbarBounds.Height = 0.0
	}
	return layout
}

func Dropdown_ScrollbarTrackBounds(scrollbar Rectangle, inset int32) Rectangle {
	var track Rectangle = scrollbar
	var value_0 float32 = track.Y
	track.Y = value_0 + float32(inset)
	var value_1 float32 = track.Height
	track.Height = value_1 - float32((int32(number_runtime_bits(uint64(inset), uint64(2), 32, true, 3))))
	if track.Height < 0.0 {
		track.Height = 0.0
	}
	return track
}

func Dropdown_OptionPaintFor(menu Rectangle, option_width int32, index int32, row_height int32, scroll_offset int32, padding_top int32, padding_bottom int32, highlight_inset_x int32, highlight_inset_y int32) OptionPaint {
	var paint OptionPaint = OptionPaint{}
	var option_bottom int32 = 0
	var visible_bottom int32 = 0
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(menu.Y), 32, true)), uint64(0), 32, true, 0))
	var content_top int32 = (int32(number_runtime_bits(uint64(value_0), uint64(padding_top), 32, true, 1)))
	var value_1 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((menu.Y+menu.Height)), 32, true)), uint64(0), 32, true, 0))
	var content_bottom int32 = (int32(number_runtime_bits(uint64(value_1), uint64(padding_bottom), 32, true, 2)))
	var value_2 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(menu.Y), 32, true)), uint64(0), 32, true, 0))
	var value_3 int64 = int64(number_runtime_bits(uint64(int64(number_runtime_bits(uint64(value_2), uint64(0), 64, true, 0))), uint64(int64(number_runtime_bits(uint64(padding_top), uint64(0), 64, true, 0))), 64, true, 1))
	var value_4 int64 = int64(number_runtime_bits(uint64(int64(number_runtime_bits(uint64(index), uint64(0), 64, true, 0))), uint64(int64(number_runtime_bits(uint64(row_height), uint64(0), 64, true, 0))), 64, true, 3))
	var value_5 int64 = int64(number_runtime_bits(uint64((int64(number_runtime_bits(uint64(value_3), uint64(value_4), 64, true, 1)))), uint64(int64(number_runtime_bits(uint64(scroll_offset), uint64(0), 64, true, 0))), 64, true, 2))
	paint.OptionY = int32(number_runtime_bits(uint64(value_5), uint64(0), 32, true, 0))
	option_bottom = (int32(number_runtime_bits(uint64(paint.OptionY), uint64(row_height), 32, true, 1)))
	paint.VisibleBounds.X = menu.X
	paint.VisibleBounds.Y = float32(paint.OptionY)
	var value_6 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(paint.VisibleBounds.Y), 32, true)), uint64(0), 32, true, 0))
	if value_6 < content_top {
		paint.VisibleBounds.Y = float32(content_top)
	}
	visible_bottom = option_bottom
	if visible_bottom > content_bottom {
		visible_bottom = content_bottom
	}
	paint.VisibleBounds.Width = float32(option_width)
	paint.VisibleBounds.Height = (float32(visible_bottom) - paint.VisibleBounds.Y)
	if paint.VisibleBounds.Height < 0.0 {
		paint.VisibleBounds.Height = 0.0
	}
	paint.HighlightBounds.X = (menu.X + float32(highlight_inset_x))
	paint.HighlightBounds.Y = float32((int32(number_runtime_bits(uint64(paint.OptionY), uint64(highlight_inset_y), 32, true, 1))))
	var value_7 int32 = int32(number_runtime_bits(uint64(option_width), uint64((int32(number_runtime_bits(uint64(highlight_inset_x), uint64(2), 32, true, 3)))), 32, true, 2))
	paint.HighlightBounds.Width = float32(value_7)
	var value_8 int32 = int32(number_runtime_bits(uint64(row_height), uint64((int32(number_runtime_bits(uint64(highlight_inset_y), uint64(2), 32, true, 3)))), 32, true, 2))
	paint.HighlightBounds.Height = float32(value_8)
	if paint.HighlightBounds.Width < 0.0 {
		paint.HighlightBounds.Width = 0.0
	}
	if paint.HighlightBounds.Height < 0.0 {
		paint.HighlightBounds.Height = 0.0
	}
	return paint
}

func Dropdown_DropdownOptionContentFor(row Rectangle, visible Rectangle, content ContentMetrics, metrics DropdownMenuMetrics, has_icon bool) DropdownOptionContent {
	var layout DropdownOptionContent = DropdownOptionContent{}
	var text_x float32 = (row.X + content.Padding)
	var text_right float32 = ((((row.X + row.Width) - content.Padding) - content.Icon) - content.Gap)
	layout.SeparatorBounds.X = (row.X + float32(metrics.SeparatorInset))
	layout.SeparatorBounds.Y = row.Y
	var value_0 float32 = row.Width - float32((int32(number_runtime_bits(uint64(metrics.SeparatorInset), uint64(2), 32, true, 3))))
	layout.SeparatorBounds.Width = value_0
	if layout.SeparatorBounds.Width < 0.0 {
		layout.SeparatorBounds.Width = 0.0
	}
	if has_icon {
		layout.IconBounds.X = text_x
		layout.IconBounds.Y = (row.Y + ((row.Height - content.Icon) / 2.0))
		layout.IconBounds.Width = content.Icon
		layout.IconBounds.Height = content.Icon
		var value_1 float32 = text_x
		text_x = value_1 + (content.Icon + content.Gap)
	}
	layout.ClipBounds.X = text_x
	layout.ClipBounds.Y = visible.Y
	layout.ClipBounds.Width = (text_right - text_x)
	layout.ClipBounds.Height = visible.Height
	if layout.ClipBounds.Width < 0.0 {
		layout.ClipBounds.Width = 0.0
	}
	if layout.ClipBounds.Height < 0.0 {
		layout.ClipBounds.Height = 0.0
	}
	layout.TextBounds = layout.ClipBounds
	layout.TextBounds.Y = row.Y
	layout.TextBounds.Height = row.Height
	layout.CheckBounds.X = (((row.X + row.Width) - content.Padding) - content.Icon)
	layout.CheckBounds.Y = (row.Y + ((row.Height - content.Icon) / 2.0))
	layout.CheckBounds.Width = content.Icon
	layout.CheckBounds.Height = content.Icon
	return layout
}

func Dropdown_PopupBounds(button Rectangle, view Rectangle, count int32, scale float32, panel StyleFrame) Rectangle {
	if scale <= 0.0 {
		scale = 1.0
	}
	var value_0 uint32 = panel.Value.Fields
	var value_1 uint32 = uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))
	var value_2 float32 = panel.Value.Gap
	var value_3 float32 = 4.0
	var value_4 int32 = Dropdown_DropdownMetric(value_0, value_1, value_2, value_3, scale, true)
	var gap float32 = float32(value_4)
	var value_5 uint32 = panel.Value.Fields
	var value_6 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0))
	var value_7 float32 = panel.Value.PaddingY
	var value_8 float32 = 8.0
	var value_9 int32 = Dropdown_DropdownMetric(value_5, value_6, value_7, value_8, scale, true)
	var padding float32 = float32(value_9)
	var value_10 uint32 = panel.Value.Fields
	var value_11 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_12 float32 = panel.Value.OffsetY
	var value_13 float32 = 16.0
	var value_14 int32 = Dropdown_DropdownMetric(value_10, value_11, value_12, value_13, scale, true)
	var margin float32 = float32(value_14)
	var bottom float32 = (view.Y + view.Height)
	var below_y float32 = ((button.Y + button.Height) + gap)
	if below_y < view.Y {
		below_y = view.Y
	}
	var below float32 = ((bottom - below_y) - margin)
	var above float32 = ((button.Y - view.Y) - margin)
	if below < 0.0 {
		below = 0.0
	}
	if above < 0.0 {
		above = 0.0
	}
	var available float32 = below
	if above > available {
		available = above
	}
	var value_15 float32 = button.Height
	var value_16 int32 = Dropdown_ContentHeight(count, value_15, padding)
	var height float32 = float32(value_16)
	var value_17 bool = (height > available)
	if value_17 {
		value_17 = (button.Height > 0.0)
	}
	if value_17 {
		var value_18 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(((available-padding)/button.Height)), 32, true)), uint64(0), 32, true, 0))
		var rows int32 = value_18
		if rows < 1 {
			rows = 1
		}
		var value_19 float32 = button.Height
		var value_20 int32 = Dropdown_ContentHeight(rows, value_19, padding)
		height = float32(value_20)
	}
	var y float32 = below_y
	var value_21 bool = (height > below)
	if value_21 {
		value_21 = (above > below)
	}
	if value_21 {
		y = ((button.Y - gap) - height)
	}
	if height > view.Height {
		height = view.Height
	}
	if height < 0.0 {
		height = 0.0
	}
	if y > (bottom - height) {
		y = (bottom - height)
	}
	if y < view.Y {
		y = view.Y
	}
	var width float32 = button.Width
	if width > view.Width {
		width = view.Width
	}
	if width < 0.0 {
		width = 0.0
	}
	var x float32 = button.X
	if x > ((view.X + view.Width) - width) {
		x = ((view.X + view.Width) - width)
	}
	if x < view.X {
		x = view.X
	}
	var value_22 Rectangle = Rectangle{}
	value_22.X = x
	value_22.Y = y
	value_22.Width = width
	value_22.Height = height
	return value_22
}

func Dropdown_ScrollOffset(offset float64, maximum int32) int32 {
	if maximum < 0 {
		maximum = 0
	}
	if offset <= 0.0 {
		return 0
	}
	if offset >= float64(maximum) {
		return maximum
	}
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(offset), 32, true)), uint64(0), 32, true, 0))
	return value_0
}

func Dropdown_RevealRow(offset int32, index int32, row float32, viewport float32, maximum int32) int32 {
	if index < 0 {
		var value_0 float64 = float64(offset)
		var value_1 int32 = Dropdown_ScrollOffset(value_0, maximum)
		return value_1
	}
	var top float64 = (float64(index) * float64(row))
	var next float64 = float64(offset)
	if top < next {
		next = top
	}
	if (top + float64(row)) > (next + float64(viewport)) {
		next = ((top + float64(row)) - float64(viewport))
	}
	var value_2 int32 = Dropdown_ScrollOffset(next, maximum)
	return value_2
}

func Dropdown_WheelOffset(offset int32, wheel float32, row float32, maximum int32) int32 {
	var value_0 float64 = (float64(offset) - (float64(wheel) * float64(row)))
	var value_1 int32 = Dropdown_ScrollOffset(value_0, maximum)
	return value_1
}

func Dropdown_Rows(count int32, offset int32, viewport float32, row float32) VisibleRows {
	var result VisibleRows = VisibleRows{}
	var value_0 bool = (count <= 0)
	if !value_0 {
		value_0 = (row <= 0.0)
	}
	var value_1 bool = value_0
	if !value_1 {
		value_1 = (viewport <= 0.0)
	}
	if value_1 {
		return result
	}
	var value_2 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((float32(offset)/row)), 32, true)), uint64(0), 32, true, 0))
	result.First = value_2
	if result.First < 0 {
		result.First = 0
	}
	if result.First > count {
		result.First = count
	}
	var bottom float64 = ((float64(offset) + float64(viewport)) / float64(row))
	if bottom >= float64(count) {
		result.End = count
	} else {
		var value_3 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(bottom), 32, true)), uint64(0), 32, true, 0))
		result.End = value_3
		if float64(result.End) < bottom {
			var value_4 int32 = result.End
			result.End = int32(number_runtime_bits(uint64(value_4), uint64(1), 32, true, 1))
		}
	}
	return result
}

func Dropdown_PopupDragGesture(gesture PopupGesture, offset int32, down bool, inside bool, scrollbar bool, y float32, maximum int32, threshold float32) PopupGesture {
	var value_0 float64 = float64(offset)
	var value_1 int32 = Dropdown_ScrollOffset(value_0, maximum)
	gesture.Offset = value_1
	var value_2 bool = down
	if value_2 {
		value_2 = !scrollbar
	}
	if value_2 {
		var value_3 bool = !gesture.Pressed
		if value_3 {
			value_3 = inside
		}
		if value_3 {
			gesture.Pressed = true
			gesture.OriginY = y
			gesture.OriginOffset = gesture.Offset
			gesture.Dragging = false
		} else {
			var value_4 bool = gesture.Pressed
			if value_4 {
				value_4 = !gesture.Dragging
			}
			if value_4 {
				var delta float32 = (y - gesture.OriginY)
				var value_5 bool = (maximum > 0)
				if value_5 {
					var value_6 bool = (delta > threshold)
					if !value_6 {
						value_6 = (delta < -threshold)
					}
					value_5 = value_6
				}
				if value_5 {
					gesture.Dragging = true
				}
			}
		}
		var value_7 bool = gesture.Dragging
		if value_7 {
			value_7 = (maximum > 0)
		}
		if value_7 {
			var value_8 float64 = (float64(gesture.Offset) - float64((y - gesture.OriginY)))
			var value_9 int32 = Dropdown_ScrollOffset(value_8, maximum)
			gesture.Offset = value_9
			gesture.OriginY = y
		}
	} else {
		gesture.Pressed = false
	}
	return gesture
}

func Dropdown_DropdownJustOpenedNext(just_opened bool, pointer_pressed bool) bool {
	var value_0 bool = just_opened
	if value_0 {
		value_0 = pointer_pressed
	}
	return value_0
}

func Dropdown_DropdownScrollbarPressedNext(pressed bool, pointer_down bool, pointer_pressed bool, max_scroll int32, pointer_over_scrollbar bool) bool {
	if !pointer_down {
		return false
	}
	var value_0 bool = pressed
	if !value_0 {
		var value_1 bool = (max_scroll > 0)
		if value_1 {
			value_1 = pointer_pressed
		}
		var value_2 bool = value_1
		if value_2 {
			value_2 = pointer_over_scrollbar
		}
		value_0 = value_2
	}
	return value_0
}
