// Code generated by k2go from runtime/instance.kry. DO NOT EDIT.
package kryon

func Instance_InstanceExpired(age int64) bool {
	var value_0 bool = (age < 0)
	if !value_0 {
		value_0 = (age > 12)
	}
	return value_0
}
