// Code generated by k2go from runtime/layout.kry. DO NOT EDIT.
package kryon

// #import drawing_props
// #import layout_props
type LayoutMetrics struct {
	Content Rectangle
	Gap     int32
	Padding int32
}

type CenteredColumnLayout struct {
	X     int32
	Width int32
}

func Layout_LayoutClamp(value int32, min_value int32, max_value int32) int32 {
	var out int32 = value
	if out < min_value {
		out = min_value
	}
	if out > max_value {
		out = max_value
	}
	return out
}

func Layout_CenteredColumnFor(view_width int32, max_width int32, side_padding int32) CenteredColumnLayout {
	var layout CenteredColumnLayout = CenteredColumnLayout{}
	if view_width < 0 {
		view_width = 0
	}
	if max_width < 0 {
		max_width = 0
	}
	if side_padding < 0 {
		side_padding = 0
	}
	var value_0 int32 = int32(number_runtime_bits(uint64(view_width), uint64((int32(number_runtime_bits(uint64(side_padding), uint64(2), 32, true, 3)))), 32, true, 2))
	var available int32 = value_0
	if available < 0 {
		available = 0
	}
	layout.Width = max_width
	if layout.Width > available {
		layout.Width = available
	}
	var value_1 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(view_width), uint64(layout.Width), 32, true, 2)))), uint64(2), 32, true, 4))
	layout.X = value_1
	return layout
}

func Layout_PageSidePaddingFor(view_width int32) int32 {
	var padding int32 = (int32(number_runtime_bits(uint64(view_width), uint64(50), 32, true, 4)))
	var value_0 int32 = 12
	var value_1 int32 = 24
	var value_2 int32 = Layout_LayoutClamp(padding, value_0, value_1)
	return value_2
}

func Layout_DesktopWidthThresholdFor(scale float32) int32 {
	if scale <= 0.0 {
		scale = 1.0
	}
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(((500.0*scale)+0.5)), 32, true)), uint64(0), 32, true, 0))
	return value_0
}

func Layout_IsDesktopWidth(view_width int32, scale float32) bool {
	var value_0 int32 = Layout_DesktopWidthThresholdFor(scale)
	return (view_width >= value_0)
}

func Layout_LayoutMetricsFor(bounds Rectangle, gap int32, padding int32) LayoutMetrics {
	var metrics LayoutMetrics = LayoutMetrics{}
	if gap < 0 {
		gap = 0
	}
	if padding < 0 {
		padding = 0
	}
	metrics.Gap = gap
	metrics.Padding = padding
	metrics.Content.X = (bounds.X + float32(padding))
	metrics.Content.Y = (bounds.Y + float32(padding))
	metrics.Content.Width = (bounds.Width - float32((int32(number_runtime_bits(uint64(padding), uint64(2), 32, true, 3)))))
	metrics.Content.Height = (bounds.Height - float32((int32(number_runtime_bits(uint64(padding), uint64(2), 32, true, 3)))))
	if metrics.Content.Width < 0.0 {
		metrics.Content.Width = 0.0
	}
	if metrics.Content.Height < 0.0 {
		metrics.Content.Height = 0.0
	}
	return metrics
}

func Layout_LayoutScopeBounds(bounds Rectangle, fallback_width int32, fallback_height int32) Rectangle {
	var out Rectangle = bounds
	if out.Width <= 0.0 {
		out.Width = float32(fallback_width)
	}
	if out.Height <= 0.0 {
		out.Height = float32(fallback_height)
	}
	if out.Width < 0.0 {
		out.Width = 0.0
	}
	if out.Height < 0.0 {
		out.Height = 0.0
	}
	return out
}

func Layout_LayoutCursorForChild(metrics LayoutMetrics, horizontal bool, child_index int32, previous_extent_sum float32) float32 {
	if child_index < 0 {
		child_index = 0
	}
	var base float32 = metrics.Content.Y
	if horizontal {
		base = metrics.Content.X
	}
	var value_0 float32 = (base + previous_extent_sum) + float32((int32(number_runtime_bits(uint64(child_index), uint64(metrics.Gap), 32, true, 3))))
	return value_0
}

func Layout_LayoutChildBounds(declared Rectangle, current Rectangle, metrics LayoutMetrics, horizontal bool, cursor float32) Rectangle {
	var out Rectangle = current
	if horizontal {
		out.X = cursor
		out.Y = metrics.Content.Y
		if out.Height <= 0.0 {
			out.Height = metrics.Content.Height
		}
	} else {
		out.X = metrics.Content.X
		out.Y = cursor
		if out.Width <= 0.0 {
			out.Width = metrics.Content.Width
		}
	}
	var value_0 bool = (declared.X != 0.0)
	if !value_0 {
		value_0 = (declared.Y != 0.0)
	}
	if value_0 {
		return current
	}
	return out
}

func Layout_StackChildBounds(declared Rectangle, current Rectangle, metrics LayoutMetrics) Rectangle {
	var out Rectangle = current
	var value_0 bool = (declared.X != 0.0)
	if !value_0 {
		value_0 = (declared.Y != 0.0)
	}
	if value_0 {
		return current
	}
	out.X = metrics.Content.X
	out.Y = metrics.Content.Y
	if out.Width <= 0.0 {
		out.Width = metrics.Content.Width
	}
	if out.Height <= 0.0 {
		out.Height = metrics.Content.Height
	}
	return out
}

func Layout_BeginFlexCursor(props FlexProps, count int32, total_item_extent float32) FlexCursor {
	var cursor FlexCursor = FlexCursor{}
	var value_0 Rectangle = props.Bounds
	var value_1 int32 = props.Gap
	var value_2 int32 = props.Padding
	var value_3 LayoutMetrics = Layout_LayoutMetricsFor(value_0, value_1, value_2)
	var metrics LayoutMetrics = value_3
	var value_4 bool = FlexDirection(props.Direction) != FlexDirection(int32(number_runtime_bits(uint64(int32(FlexColumn)), uint64(0), 32, true, 0)))
	var horizontal bool = value_4
	var value_5 float32 = 0
	if horizontal {
		value_5 = metrics.Content.Width
	} else {
		value_5 = metrics.Content.Height
	}
	var available float32 = value_5
	cursor.Content = metrics.Content
	cursor.Direction = FlexDirection(props.Direction)
	cursor.AlignItems = AlignItems(props.AlignItems)
	cursor.Gap = float32(metrics.Gap)
	var value_6 float32 = 0
	if horizontal {
		value_6 = metrics.Content.X
	} else {
		value_6 = metrics.Content.Y
	}
	cursor.Position = value_6
	if count <= 0 {
		return cursor
	}
	cursor.Remaining = count
	if total_item_extent < 0.0 {
		total_item_extent = 0.0
	}
	var value_7 float32 = (available - total_item_extent) - (cursor.Gap * float32((int32(number_runtime_bits(uint64(count), uint64(1), 32, true, 2)))))
	var remaining float32 = value_7
	if remaining < 0.0 {
		remaining = 0.0
	}
	var offset float32 = 0.0
	var value_8 bool = JustifyContent(props.JustifyContent) == JustifyContent(int32(number_runtime_bits(uint64(int32(JustifyCenter)), uint64(0), 32, true, 0)))
	if value_8 {
		offset = (remaining / 2.0)
	} else {
		var value_9 bool = JustifyContent(props.JustifyContent) == JustifyContent(int32(number_runtime_bits(uint64(int32(JustifyEnd)), uint64(0), 32, true, 0)))
		if value_9 {
			offset = remaining
		} else {
			var value_10 bool = JustifyContent(props.JustifyContent) == JustifyContent(int32(number_runtime_bits(uint64(int32(JustifySpaceBetween)), uint64(0), 32, true, 0)))
			var value_11 bool = value_10
			if value_11 {
				value_11 = (count > 1)
			}
			if value_11 {
				var value_12 float32 = cursor.Gap
				cursor.Gap = value_12 + (remaining / float32((int32(number_runtime_bits(uint64(count), uint64(1), 32, true, 2)))))
			} else {
				var value_13 bool = JustifyContent(props.JustifyContent) == JustifyContent(int32(number_runtime_bits(uint64(int32(JustifySpaceAround)), uint64(0), 32, true, 0)))
				if value_13 {
					offset = ((remaining / float32(count)) / 2.0)
					var value_14 float32 = cursor.Gap
					cursor.Gap = value_14 + (remaining / float32(count))
				} else {
					var value_15 bool = JustifyContent(props.JustifyContent) == JustifyContent(int32(number_runtime_bits(uint64(int32(JustifySpaceEvenly)), uint64(0), 32, true, 0)))
					if value_15 {
						offset = (remaining / (float32(count) + 1.0))
						var value_16 float32 = cursor.Gap
						cursor.Gap = value_16 + offset
					}
				}
			}
		}
	}
	var value_17 float32 = cursor.Position
	cursor.Position = value_17 + offset
	return cursor
}

func Layout_FlexStep(cursor FlexCursor, width float32, height float32) FlexCursor {
	var value_0 Rectangle = Rectangle{}
	value_0.X = 0.0
	value_0.Y = 0.0
	value_0.Width = 0.0
	value_0.Height = 0.0
	cursor.Item = value_0
	if cursor.Remaining <= 0 {
		return cursor
	}
	if width < 0.0 {
		width = 0.0
	}
	if height < 0.0 {
		height = 0.0
	}
	var value_1 bool = FlexDirection(cursor.Direction) != FlexDirection(int32(number_runtime_bits(uint64(int32(FlexColumn)), uint64(0), 32, true, 0)))
	var horizontal bool = value_1
	var value_2 float32 = 0
	if horizontal {
		value_2 = cursor.Content.Height
	} else {
		value_2 = cursor.Content.Width
	}
	var cross_size float32 = value_2
	var value_3 float32 = 0
	if horizontal {
		value_3 = height
	} else {
		value_3 = width
	}
	var extent float32 = value_3
	var value_4 bool = AlignItems(cursor.AlignItems) == AlignItems(int32(number_runtime_bits(uint64(int32(AlignStretch)), uint64(0), 32, true, 0)))
	var value_5 bool = value_4
	if value_5 {
		value_5 = (extent <= 0.0)
	}
	if value_5 {
		extent = cross_size
	}
	var cross_remaining float32 = (cross_size - extent)
	if cross_remaining < 0.0 {
		cross_remaining = 0.0
	}
	var cross_offset float32 = 0.0
	var value_6 bool = AlignItems(cursor.AlignItems) == AlignItems(int32(number_runtime_bits(uint64(int32(AlignCenter)), uint64(0), 32, true, 0)))
	if value_6 {
		cross_offset = (cross_remaining / 2.0)
	} else {
		var value_7 bool = AlignItems(cursor.AlignItems) == AlignItems(int32(number_runtime_bits(uint64(int32(AlignEnd)), uint64(0), 32, true, 0)))
		if value_7 {
			cross_offset = cross_remaining
		}
	}
	if horizontal {
		var value_8 Rectangle = Rectangle{}
		value_8.X = cursor.Position
		value_8.Y = (cursor.Content.Y + cross_offset)
		value_8.Width = width
		value_8.Height = extent
		cursor.Item = value_8
		var value_9 float32 = cursor.Position
		cursor.Position = value_9 + (width + cursor.Gap)
	} else {
		var value_10 Rectangle = Rectangle{}
		value_10.X = (cursor.Content.X + cross_offset)
		value_10.Y = cursor.Position
		value_10.Width = extent
		value_10.Height = height
		cursor.Item = value_10
		var value_11 float32 = cursor.Position
		cursor.Position = value_11 + (height + cursor.Gap)
	}
	var value_12 int32 = cursor.Remaining
	cursor.Remaining = int32(number_runtime_bits(uint64(value_12), uint64(1), 32, true, 2))
	return cursor
}
