// Code generated by k2go from runtime/link_props.kry. DO NOT EDIT.
package kryon

// #import kryon_compat.generated.h
type LinkProps struct {
	Bounds     Rectangle
	ClassName  int32
	Text       string
	Link       string
	Font       int32
	FocusID    int32
	Disabled   bool
	Color      Color
	HoverColor Color
}
