// Code generated by k2go from runtime/menu.kry. DO NOT EDIT.
package kryon

// #import drawing_props
// #import style
// #import control_props
type MenuMetrics struct {
	RowHeight             int32
	PanelMinWidth         int32
	PanelPadding          int32
	PanelMargin           int32
	AcceleratorGap        int32
	SeparatorInset        int32
	CheckedMarkInset      int32
	LabelInset            int32
	SubmenuIndicatorInset int32
	BarItemMinWidth       int32
	BarItemPadding        int32
	BarItemGap            int32
	BarItemYPadding       int32
	BarLabelInset         int32
}

type MenuLine struct {
	X1 int32
	Y1 int32
	X2 int32
	Y2 int32
}

type MenuGroupPointerDecision struct {
	ChangedOpen     bool
	NextOpenId      int32
	ClearSubmenu    bool
	ConsumeRelease  bool
	SetFocus        bool
	ResetNavigation bool
	NavigationTop   int32
}

type MenuItemPointerDecision struct {
	ConsumeRelease       bool
	SetFocus             bool
	ResetNavigation      bool
	SetNavigationPath    bool
	NavigationDepth      int32
	NavigationIndex      int32
	ClearChildNavigation bool
	SetSubmenu           bool
	SubmenuId            int32
	Activate             bool
	ActivatedID          int32
	CloseOpen            bool
}

type MenuKeyboardInput struct {
	Up     bool
	Down   bool
	Home   bool
	End    bool
	Left   bool
	Right  bool
	Enter  bool
	Space  bool
	Escape bool
}

type MenuKeyboardDecision struct {
	KeyHandled     bool
	MoveDelta      int32
	First          bool
	Last           bool
	CloseParent    bool
	OpenOrActivate bool
}

type MenuBarKeyboardDecision struct {
	MoveTopDelta             int32
	FirstTop                 bool
	LastTop                  bool
	OpenTop                  bool
	CloseOpen                bool
	MoveOpenDelta            int32
	MoveOpenIfNoSubmenuDelta int32
}

type MenuOutsideCloseDecision struct {
	CloseOpen      bool
	ClearSubmenu   bool
	ConsumeRelease bool
	OpenIndex      int32
}

type MenuContextOutsideCloseDecision struct {
	CloseOpen      bool
	ConsumeRelease bool
}

type MenuContextOpenResult struct {
	Open    bool
	Changed bool
}

func Menu_MenuBarRole() int32 {
	return 1
}

func Menu_MenuPopupRole() int32 {
	return 2
}

func Menu_MenuContextRole() int32 {
	return 3
}

func Menu_MenuHas(fields uint32, field uint32) bool {
	var value_0 bool = (uint32(number_runtime_bits(uint64(fields), uint64(field), 32, false, 8))) != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0))
	return value_0
}

func Menu_MenuKindSeparator() int32 {
	return 3
}

func Menu_MenuKindSubmenu() int32 {
	return 4
}

func Menu_MenuMetric(fields uint32, field uint32, value float32, fallback float32, scale float32, allow_zero bool) int32 {
	var value_0 bool = Menu_MenuHas(fields, field)
	var value_1 bool = !value_0
	if !value_1 {
		value_1 = (value < 0.0)
	}
	var value_2 bool = value_1
	if !value_2 {
		var value_3 bool = !allow_zero
		if value_3 {
			value_3 = (value <= 0.0)
		}
		value_2 = value_3
	}
	if value_2 {
		value = fallback
	}
	var value_4 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((value*scale)), 32, true)), uint64(0), 32, true, 0))
	return value_4
}

func Menu_MenuWrappedItemIndex(start int32, direction int32, item_count int32) int32 {
	if item_count <= 0 {
		return -1
	}
	if direction == 0 {
		direction = 1
	}
	var value_0 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(start), uint64(direction), 32, true, 1)))), uint64(item_count), 32, true, 1))
	return (int32(number_runtime_bits(uint64(value_0), uint64(item_count), 32, true, 5)))
}

func Menu_MenuItemSelectable(kind int32, disabled bool) bool {
	var value_0 int32 = Menu_MenuKindSeparator()
	var value_1 bool = (kind != value_0)
	if value_1 {
		value_1 = !disabled
	}
	return value_1
}

func Menu_MenuItemIsSeparator(kind int32) bool {
	var value_0 int32 = Menu_MenuKindSeparator()
	return (kind == value_0)
}

func Menu_MenuItemShowsSubmenu(kind int32) bool {
	var value_0 int32 = Menu_MenuKindSubmenu()
	return (kind == value_0)
}

func Menu_MenuItemCanOpenSubmenu(kind int32, disabled bool, has_submenu bool, submenu_count int32, depth int32, max_depth int32) bool {
	var value_0 int32 = Menu_MenuKindSubmenu()
	var value_1 bool = (kind != value_0)
	if !value_1 {
		value_1 = disabled
	}
	if value_1 {
		return false
	}
	var value_2 bool = !has_submenu
	if !value_2 {
		value_2 = (submenu_count <= 0)
	}
	if value_2 {
		return false
	}
	return ((int32(number_runtime_bits(uint64(depth), uint64(1), 32, true, 1))) < max_depth)
}

func Menu_MenuItemKeyboardActivates(kind int32, disabled bool, opens_submenu bool) bool {
	var value_0 int32 = Menu_MenuKindSeparator()
	var value_1 bool = (kind != value_0)
	if value_1 {
		value_1 = !disabled
	}
	var value_2 bool = value_1
	if value_2 {
		value_2 = !opens_submenu
	}
	return value_2
}

func Menu_MenuKeyboardInputFor(up bool, down bool, home bool, end bool, left bool, right bool, enter bool, space bool, escape bool) MenuKeyboardInput {
	var input MenuKeyboardInput = MenuKeyboardInput{}
	input.Up = up
	input.Down = down
	input.Home = home
	input.End = end
	input.Left = left
	input.Right = right
	input.Enter = enter
	input.Space = space
	input.Escape = escape
	return input
}

func Menu_MenuKeyboardDecisionFor(input MenuKeyboardInput, depth int32, selected int32) MenuKeyboardDecision {
	var decision MenuKeyboardDecision = MenuKeyboardDecision{}
	if selected < 0 {
		return decision
	}
	if input.Up {
		decision.KeyHandled = true
		decision.MoveDelta = -1
		return decision
	}
	if input.Down {
		decision.KeyHandled = true
		decision.MoveDelta = 1
		return decision
	}
	if input.Home {
		decision.KeyHandled = true
		decision.First = true
		return decision
	}
	if input.End {
		decision.KeyHandled = true
		decision.Last = true
		return decision
	}
	var value_0 bool = input.Left
	if value_0 {
		value_0 = (depth > 0)
	}
	if value_0 {
		decision.KeyHandled = true
		decision.CloseParent = true
		return decision
	}
	var value_1 bool = input.Right
	if !value_1 {
		value_1 = input.Enter
	}
	var value_2 bool = value_1
	if !value_2 {
		value_2 = input.Space
	}
	if value_2 {
		decision.KeyHandled = true
		decision.OpenOrActivate = true
	}
	return decision
}

func Menu_MenuBarKeyboardDecisionFor(input MenuKeyboardInput, open bool, depth int32) MenuBarKeyboardDecision {
	var decision MenuBarKeyboardDecision = MenuBarKeyboardDecision{}
	if !open {
		if input.Left {
			decision.MoveTopDelta = -1
			return decision
		}
		if input.Right {
			decision.MoveTopDelta = 1
			return decision
		}
		if input.Home {
			decision.FirstTop = true
			return decision
		}
		if input.End {
			decision.LastTop = true
			return decision
		}
		var value_0 bool = input.Enter
		if !value_0 {
			value_0 = input.Space
		}
		var value_1 bool = value_0
		if !value_1 {
			value_1 = input.Down
		}
		if value_1 {
			decision.OpenTop = true
		}
		return decision
	}
	if input.Escape {
		decision.CloseOpen = true
		return decision
	}
	var value_2 bool = (depth == 0)
	if value_2 {
		value_2 = input.Left
	}
	if value_2 {
		decision.MoveOpenDelta = -1
		return decision
	}
	var value_3 bool = (depth == 0)
	if value_3 {
		value_3 = input.Right
	}
	if value_3 {
		decision.MoveOpenIfNoSubmenuDelta = 1
	}
	return decision
}

func Menu_MenuItemPointerActivates(kind int32, disabled bool) bool {
	var value_0 int32 = Menu_MenuKindSeparator()
	var value_1 bool = (kind != value_0)
	if value_1 {
		var value_2 int32 = Menu_MenuKindSubmenu()
		value_1 = (kind != value_2)
	}
	var value_3 bool = value_1
	if value_3 {
		value_3 = !disabled
	}
	return value_3
}

func Menu_MenuBarCountFor(count int32, limit int32) int32 {
	if count < 0 {
		return 0
	}
	var value_0 bool = (limit >= 0)
	if value_0 {
		value_0 = (count > limit)
	}
	if value_0 {
		return limit
	}
	return count
}

func Menu_MenuBarOpenIndexFor(bar_id int32, open_id int32, menu_count int32) int32 {
	var value_0 bool = (bar_id <= 0)
	if !value_0 {
		value_0 = (menu_count <= 0)
	}
	if value_0 {
		return -1
	}
	var value_1 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(open_id), uint64(bar_id), 32, true, 2)))), uint64(1), 32, true, 2))
	var index int32 = value_1
	var value_2 bool = (index < 0)
	if !value_2 {
		value_2 = (index >= menu_count)
	}
	if value_2 {
		return -1
	}
	return index
}

func Menu_MenuBarOpenIdFor(bar_id int32, index int32, menu_count int32) int32 {
	var value_0 bool = (bar_id <= 0)
	if !value_0 {
		value_0 = (index < 0)
	}
	var value_1 bool = value_0
	if !value_1 {
		value_1 = (index >= menu_count)
	}
	if value_1 {
		return 0
	}
	var value_2 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(bar_id), uint64(1), 32, true, 1)))), uint64(index), 32, true, 1))
	return value_2
}

func Menu_MenuBarTopIndexFor(top int32, menu_count int32) int32 {
	if menu_count <= 0 {
		return -1
	}
	var value_0 bool = (top < 0)
	if !value_0 {
		value_0 = (top >= menu_count)
	}
	if value_0 {
		return 0
	}
	return top
}

func Menu_MenuBarMoveTopIndex(top int32, menu_count int32, direction int32) int32 {
	if menu_count <= 0 {
		return -1
	}
	var value_0 int32 = Menu_MenuBarTopIndexFor(top, menu_count)
	top = value_0
	if direction == 0 {
		return top
	}
	var value_1 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(top), uint64(direction), 32, true, 1)))), uint64(menu_count), 32, true, 1))
	return (int32(number_runtime_bits(uint64(value_1), uint64(menu_count), 32, true, 5)))
}

func Menu_MenuGroupPointerDecisionFor(menu_id int32, index int32, open_id int32, hot bool, mouse_released bool) MenuGroupPointerDecision {
	var decision MenuGroupPointerDecision = MenuGroupPointerDecision{}
	decision.NextOpenId = open_id
	decision.NavigationTop = index
	var open bool = (open_id == menu_id)
	var value_0 bool = hot
	if value_0 {
		value_0 = mouse_released
	}
	if value_0 {
		decision.ConsumeRelease = true
		decision.SetFocus = true
		decision.ChangedOpen = true
		if open {
			decision.NextOpenId = 0
			decision.ClearSubmenu = true
		} else {
			decision.NextOpenId = menu_id
			decision.ResetNavigation = true
		}
		return decision
	}
	var value_1 bool = hot
	if value_1 {
		value_1 = (open_id != 0)
	}
	var value_2 bool = value_1
	if value_2 {
		value_2 = !open
	}
	if value_2 {
		decision.ChangedOpen = true
		decision.NextOpenId = menu_id
		decision.ClearSubmenu = true
	}
	return decision
}

func Menu_MenuItemPointerDecisionFor(hot bool, mouse_released bool, same_focus bool, kind int32, disabled bool, item_id int32, index int32, depth int32, max_depth int32) MenuItemPointerDecision {
	var decision MenuItemPointerDecision = MenuItemPointerDecision{}
	decision.NavigationDepth = depth
	decision.NavigationIndex = index
	var value_0 bool = !hot
	if !value_0 {
		value_0 = !mouse_released
	}
	if value_0 {
		return decision
	}
	decision.ConsumeRelease = true
	decision.SetFocus = true
	decision.ResetNavigation = !same_focus
	if depth < max_depth {
		decision.SetNavigationPath = true
		decision.ClearChildNavigation = true
	}
	var value_1 bool = Menu_MenuItemShowsSubmenu(kind)
	if value_1 {
		decision.SetSubmenu = true
		decision.SubmenuId = item_id
	} else {
		var value_2 bool = Menu_MenuItemPointerActivates(kind, disabled)
		if value_2 {
			decision.Activate = true
			decision.ActivatedID = item_id
			decision.CloseOpen = true
		}
	}
	return decision
}

func Menu_MenuOutsideCloseDecisionFor(open_id int32, mouse_released bool, contains_bar bool, panel_valid bool, contains_panel bool) MenuOutsideCloseDecision {
	var decision MenuOutsideCloseDecision = MenuOutsideCloseDecision{}
	decision.OpenIndex = -1
	var value_0 bool = (open_id != 0)
	if value_0 {
		value_0 = mouse_released
	}
	var value_1 bool = value_0
	if value_1 {
		value_1 = !contains_bar
	}
	var value_2 bool = value_1
	if value_2 {
		var value_3 bool = !panel_valid
		if !value_3 {
			value_3 = !contains_panel
		}
		value_2 = value_3
	}
	if value_2 {
		decision.CloseOpen = true
		decision.ClearSubmenu = true
		decision.ConsumeRelease = true
	}
	return decision
}

func Menu_MenuContextOutsideCloseDecisionFor(open_id int32, menu_id int32, suppress_close bool, mouse_released bool, panel_valid bool, contains_panel bool) MenuContextOutsideCloseDecision {
	var decision MenuContextOutsideCloseDecision = MenuContextOutsideCloseDecision{}
	var value_0 bool = (open_id == menu_id)
	if value_0 {
		value_0 = !suppress_close
	}
	var value_1 bool = value_0
	if value_1 {
		value_1 = mouse_released
	}
	var value_2 bool = value_1
	if value_2 {
		var value_3 bool = !panel_valid
		if !value_3 {
			value_3 = !contains_panel
		}
		value_2 = value_3
	}
	if value_2 {
		decision.CloseOpen = true
		decision.ConsumeRelease = true
	}
	return decision
}

func Menu_MenuContextOpenFor(open bool, open_requested bool, close_requested bool, has_open bool) MenuContextOpenResult {
	var result MenuContextOpenResult = MenuContextOpenResult{}
	result.Open = open
	if !has_open {
		return result
	}
	if open_requested {
		result.Open = true
	}
	if close_requested {
		result.Open = false
	}
	result.Changed = (result.Open != open)
	return result
}

func Menu_MenuEscapeShouldClose(focused bool, focus_captured bool, escape_pressed bool) bool {
	var value_0 bool = focused
	if value_0 {
		value_0 = !focus_captured
	}
	var value_1 bool = value_0
	if value_1 {
		value_1 = escape_pressed
	}
	return value_1
}

func Menu_MenuContextShouldSuppressClose(opened bool, contains_trigger bool, mouse_released bool) bool {
	var value_0 bool = opened
	if !value_0 {
		var value_1 bool = contains_trigger
		if value_1 {
			value_1 = mouse_released
		}
		value_0 = value_1
	}
	return value_0
}

func Menu_MenuMetricsFor(scale float32, panel StyleFrame, item StyleFrame, bar StyleFrame) MenuMetrics {
	if scale <= 0.0 {
		scale = 1.0
	}
	var metrics MenuMetrics = MenuMetrics{}
	var row_height float32 = 30.0
	var value_0 uint32 = item.Value.Fields
	var value_1 uint32 = uint32(number_runtime_bits(uint64(int32(StyleFontSize)), uint64(0), 32, false, 0))
	var value_2 bool = Menu_MenuHas(value_0, value_1)
	var value_3 bool = value_2
	if value_3 {
		var value_4 uint32 = item.Value.Fields
		var value_5 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0))
		var value_6 bool = Menu_MenuHas(value_4, value_5)
		value_3 = value_6
	}
	if value_3 {
		row_height = (item.Value.FontSize + (item.Value.PaddingY * 2.0))
	}
	var value_7 uint32 = item.Value.Fields
	var value_8 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_9 float32 = item.Value.OffsetY
	var value_10 int32 = Menu_MenuMetric(value_7, value_8, value_9, row_height, scale, false)
	metrics.RowHeight = value_10
	var value_11 uint32 = panel.Value.Fields
	var value_12 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_13 float32 = panel.Value.OffsetX
	var value_14 float32 = 180.0
	var value_15 int32 = Menu_MenuMetric(value_11, value_12, value_13, value_14, scale, false)
	metrics.PanelMinWidth = value_15
	var value_16 uint32 = panel.Value.Fields
	var value_17 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))
	var value_18 float32 = panel.Value.PaddingX
	var value_19 float32 = 12.0
	var value_20 int32 = Menu_MenuMetric(value_16, value_17, value_18, value_19, scale, true)
	metrics.PanelPadding = value_20
	var value_21 uint32 = panel.Value.Fields
	var value_22 uint32 = uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))
	var value_23 float32 = panel.Value.Gap
	var value_24 float32 = 4.0
	var value_25 int32 = Menu_MenuMetric(value_21, value_22, value_23, value_24, scale, true)
	metrics.PanelMargin = value_25
	var value_26 uint32 = item.Value.Fields
	var value_27 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_28 float32 = item.Value.OffsetX
	var value_29 float32 = 88.0
	var value_30 int32 = Menu_MenuMetric(value_26, value_27, value_28, value_29, scale, true)
	metrics.AcceleratorGap = value_30
	var value_31 uint32 = item.Value.Fields
	var value_32 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))
	var value_33 float32 = item.Value.PaddingX
	var value_34 float32 = 8.0
	var value_35 int32 = Menu_MenuMetric(value_31, value_32, value_33, value_34, scale, true)
	metrics.SeparatorInset = value_35
	metrics.CheckedMarkInset = metrics.SeparatorInset
	var value_36 uint32 = item.Value.Fields
	var value_37 uint32 = uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))
	var value_38 float32 = item.Value.IconSize
	var value_39 float32 = 28.0
	var value_40 int32 = Menu_MenuMetric(value_36, value_37, value_38, value_39, scale, true)
	metrics.LabelInset = value_40
	var value_41 uint32 = item.Value.Fields
	var value_42 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0))
	var value_43 float32 = item.Value.PaddingY
	var value_44 float32 = 18.0
	var value_45 int32 = Menu_MenuMetric(value_41, value_42, value_43, value_44, scale, true)
	metrics.SubmenuIndicatorInset = value_45
	metrics.BarItemMinWidth = 0
	var value_46 uint32 = bar.Value.Fields
	var value_47 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))
	var value_48 float32 = (bar.Value.PaddingX * 2.0)
	var value_49 float32 = 24.0
	var value_50 int32 = Menu_MenuMetric(value_46, value_47, value_48, value_49, scale, true)
	metrics.BarItemPadding = value_50
	var value_51 uint32 = bar.Value.Fields
	var value_52 uint32 = uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))
	var value_53 float32 = bar.Value.Gap
	var value_54 float32 = 2.0
	var value_55 int32 = Menu_MenuMetric(value_51, value_52, value_53, value_54, scale, true)
	metrics.BarItemGap = value_55
	var value_56 uint32 = bar.Value.Fields
	var value_57 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0))
	var value_58 float32 = bar.Value.PaddingY
	var value_59 float32 = 3.0
	var value_60 int32 = Menu_MenuMetric(value_56, value_57, value_58, value_59, scale, true)
	metrics.BarItemYPadding = value_60
	var value_61 uint32 = bar.Value.Fields
	var value_62 uint32 = uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))
	var value_63 float32 = bar.Value.IconSize
	var value_64 float32 = 12.0
	var value_65 int32 = Menu_MenuMetric(value_61, value_62, value_63, value_64, scale, true)
	metrics.BarLabelInset = value_65
	return metrics
}

func Menu_MenuGroupItemWidth(label_width int32, metrics MenuMetrics) int32 {
	var width int32 = (int32(number_runtime_bits(uint64(label_width), uint64(metrics.BarItemPadding), 32, true, 1)))
	if width < metrics.BarItemMinWidth {
		width = metrics.BarItemMinWidth
	}
	return width
}

func Menu_MenuPanelWidthStep(current_width int32, label_width int32, accelerator_width int32, has_accelerator bool, metrics MenuMetrics) int32 {
	var width int32 = current_width
	if width <= 0 {
		width = metrics.PanelMinWidth
	}
	var accel int32 = 0
	if has_accelerator {
		accel = (int32(number_runtime_bits(uint64(accelerator_width), uint64(metrics.AcceleratorGap), 32, true, 1)))
	}
	var value_0 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(label_width), uint64(accel), 32, true, 1)))), uint64((int32(number_runtime_bits(uint64(metrics.PanelPadding), uint64(2), 32, true, 3)))), 32, true, 1))
	var candidate int32 = value_0
	if candidate > width {
		width = candidate
	}
	return width
}

func Menu_MenuPanelBounds(x int32, y int32, width int32, item_count int32, metrics MenuMetrics) Rectangle {
	var bounds Rectangle = Rectangle{}
	if item_count < 0 {
		item_count = 0
	}
	if width < 0 {
		width = 0
	}
	bounds.X = float32(x)
	bounds.Y = float32(y)
	bounds.Width = float32(width)
	var value_0 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(metrics.RowHeight), uint64(item_count), 32, true, 3)))), uint64((int32(number_runtime_bits(uint64(metrics.PanelMargin), uint64(2), 32, true, 3)))), 32, true, 1))
	bounds.Height = float32(value_0)
	return bounds
}

func Menu_MenuRowBounds(panel Rectangle, index int32, metrics MenuMetrics) Rectangle {
	var row Rectangle = Rectangle{}
	if index < 0 {
		index = 0
	}
	row.X = (panel.X + float32(metrics.PanelMargin))
	var value_0 int32 = int32(number_runtime_bits(uint64(metrics.PanelMargin), uint64((int32(number_runtime_bits(uint64(index), uint64(metrics.RowHeight), 32, true, 3)))), 32, true, 1))
	row.Y = (panel.Y + float32(value_0))
	var value_1 float32 = panel.Width - float32((int32(number_runtime_bits(uint64(metrics.PanelMargin), uint64(2), 32, true, 3))))
	row.Width = value_1
	row.Height = float32(metrics.RowHeight)
	if row.Width < 0.0 {
		row.Width = 0.0
	}
	return row
}

func Menu_MenuSubmenuX(row Rectangle) int32 {
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((row.X+row.Width)), 32, true)), uint64(0), 32, true, 0))
	return value_0
}

func Menu_MenuSubmenuOrigin(row Rectangle) Vector2 {
	var origin Vector2 = Vector2{}
	origin.X = (row.X + row.Width)
	origin.Y = row.Y
	return origin
}

func Menu_MenuSeparatorLineFor(row Rectangle, metrics MenuMetrics) MenuLine {
	var line MenuLine = MenuLine{}
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(row.X), 32, true)), uint64(0), 32, true, 0))
	line.X1 = (int32(number_runtime_bits(uint64(value_0), uint64(metrics.SeparatorInset), 32, true, 1)))
	var value_1 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((row.Y+(row.Height/2.0))), 32, true)), uint64(0), 32, true, 0))
	line.Y1 = value_1
	var value_2 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((row.X+row.Width)), 32, true)), uint64(0), 32, true, 0))
	line.X2 = (int32(number_runtime_bits(uint64(value_2), uint64(metrics.SeparatorInset), 32, true, 2)))
	line.Y2 = line.Y1
	if line.X2 < line.X1 {
		line.X2 = line.X1
	}
	return line
}

func Menu_MenuTextY(row Rectangle, line_height int32) int32 {
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(row.Y), 32, true)), uint64(0), 32, true, 0))
	var value_1 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(row.Height), 32, true)), uint64(0), 32, true, 0))
	var value_2 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(value_1), uint64(line_height), 32, true, 2)))), uint64(2), 32, true, 4))
	return (int32(number_runtime_bits(uint64(value_0), uint64(value_2), 32, true, 1)))
}

func Menu_MenuCheckedMarkX(row Rectangle, metrics MenuMetrics) int32 {
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(row.X), 32, true)), uint64(0), 32, true, 0))
	return (int32(number_runtime_bits(uint64(value_0), uint64(metrics.CheckedMarkInset), 32, true, 1)))
}

func Menu_MenuLabelX(row Rectangle, metrics MenuMetrics) int32 {
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(row.X), 32, true)), uint64(0), 32, true, 0))
	return (int32(number_runtime_bits(uint64(value_0), uint64(metrics.LabelInset), 32, true, 1)))
}

func Menu_MenuAcceleratorX(row Rectangle, text_width int32, metrics MenuMetrics) int32 {
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((row.X+row.Width)), 32, true)), uint64(0), 32, true, 0))
	var value_1 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(value_0), uint64(text_width), 32, true, 2)))), uint64(metrics.PanelPadding), 32, true, 2))
	return value_1
}

func Menu_MenuAcceleratorShouldFire(keyboard_enabled bool, ctrl_required bool, ctrl_down bool, shift_required bool, shift_down bool, alt_required bool, alt_down bool, key_pressed bool) bool {
	if !keyboard_enabled {
		return false
	}
	var value_0 bool = ctrl_required
	if value_0 {
		value_0 = !ctrl_down
	}
	if value_0 {
		return false
	}
	var value_1 bool = shift_required
	if value_1 {
		value_1 = !shift_down
	}
	if value_1 {
		return false
	}
	var value_2 bool = alt_required
	if value_2 {
		value_2 = !alt_down
	}
	if value_2 {
		return false
	}
	return key_pressed
}

func Menu_MenuSubmenuIndicatorX(row Rectangle, metrics MenuMetrics) int32 {
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((row.X+row.Width)), 32, true)), uint64(0), 32, true, 0))
	return (int32(number_runtime_bits(uint64(value_0), uint64(metrics.SubmenuIndicatorInset), 32, true, 2)))
}

func Menu_MenuBarFirstItemX(bar Rectangle, metrics MenuMetrics) int32 {
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(bar.X), 32, true)), uint64(0), 32, true, 0))
	return (int32(number_runtime_bits(uint64(value_0), uint64(metrics.PanelMargin), 32, true, 1)))
}

func Menu_MenuBarNextItemX(x int32, width int32, metrics MenuMetrics) int32 {
	var value_0 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(x), uint64(width), 32, true, 1)))), uint64(metrics.BarItemGap), 32, true, 1))
	return value_0
}

func Menu_MenuBarLabelX(item Rectangle, metrics MenuMetrics) int32 {
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(item.X), 32, true)), uint64(0), 32, true, 0))
	return (int32(number_runtime_bits(uint64(value_0), uint64(metrics.BarLabelInset), 32, true, 1)))
}

func Menu_MenuBarLabelY(item Rectangle, line_height int32) int32 {
	var value_0 int32 = Menu_MenuTextY(item, line_height)
	return value_0
}

func Menu_MenuGroupItemBounds(x int32, bar Rectangle, width int32, metrics MenuMetrics) Rectangle {
	var item Rectangle = Rectangle{}
	item.X = float32(x)
	item.Y = (bar.Y + float32(metrics.BarItemYPadding))
	item.Width = float32(width)
	var value_0 float32 = bar.Height - float32((int32(number_runtime_bits(uint64(metrics.BarItemYPadding), uint64(2), 32, true, 3))))
	item.Height = value_0
	if item.Height < 0.0 {
		item.Height = 0.0
	}
	return item
}
