// Code generated by k2go from runtime/navigation_bar_props.kry. DO NOT EDIT.
package kryon

// #import kryon_compat.generated.h
type NavigationBarItem struct {
	Route    int32
	Label    string
	Icon     Texture2D
	IconType int32
	Active   bool
	Disabled bool
}

type NavigationBarProps struct {
	ViewWidth      int32
	ViewHeight     int32
	ClassName      int32
	Count          int32
	Items          []NavigationBarItem
	Height         int32
	IconSize       int32
	IconPadding    int32
	SideMargin     int32
	BottomMargin   int32
	MaxButtonWidth int32
	IconColor      Color
}

type NavigationBarResult struct {
	ClickedIndex int32
	ClickedRoute int32
	Y            int32
	Height       int32
}
