// Code generated by k2go from runtime/node_props.kry. DO NOT EDIT.
package kryon

// #import kryon_compat.generated.h
type KryonNodeKind int32

const (
	KRYONNODEKINDUNKNOWN KryonNodeKind = 0
	KRYONNODEKINDUI      KryonNodeKind = 1
	KRYONNODEKIND2D      KryonNodeKind = 2
	KRYONNODEKINDDATA    KryonNodeKind = 3
	KRYONNODEKINDGROUP   KryonNodeKind = 4
)

type KryonNodeFlags int32

const (
	KRYONNODEFLAGSELECTABLE KryonNodeFlags = 1
	KRYONNODEFLAGMOVABLE    KryonNodeFlags = 2
	KRYONNODEFLAGRESIZABLE  KryonNodeFlags = 4
	KRYONNODEFLAGDELETABLE  KryonNodeFlags = 8
	KRYONNODEFLAGINSERTABLE KryonNodeFlags = 16
	KRYONNODEFLAGREADONLY   KryonNodeFlags = 32
	KRYONNODEFLAGVISIBLE    KryonNodeFlags = 64
	KRYONNODEFLAGLOCKED     KryonNodeFlags = 128
)

type KryonNode struct {
	ID          [KRYONNODEIDMAX]byte
	Name        [KRYONNODENAMEMAX]byte
	Type        [KRYONNODETYPEMAX]byte
	BaseType    [KRYONNODETYPEMAX]byte
	ParentId    [KRYONNODEIDMAX]byte
	SourcePath  [KRYONNODEPATHMAX]byte
	Kind        KryonNodeKind
	Flags       uint32
	Bounds      Rectangle
	Position    Vector2
	Scale       Vector2
	Origin      Vector2
	Rotation    float32
	Layer       int32
	Order       int32
	SourceLine  int32
	SourceStart int32
	SourceEnd   int32
}

const KRYONNODEIDMAX = 96
const KRYONNODENAMEMAX = 128
const KRYONNODETYPEMAX = 64
const KRYONNODEPATHMAX = 512
