// Code generated by k2go from runtime/paint.kry. DO NOT EDIT.
package kryon

// #import drawing_props
// #import surface
// #import material
type DrawingKind int32

const (
	DrawingKindDrawingNone    = 0
	DrawingKindDrawingText    = 1
	DrawingKindDrawingIcon    = 2
	DrawingKindDrawingTexture = 3
	DrawingKindDrawingRing    = 4
	DrawingKindDrawingChevron = 5
)

type Drawing struct {
	Kind    int32
	Bounds  Rectangle
	Color   uint32
	Text    string
	Font    int32
	Icon    int32
	Texture Texture2D
	Ring    Ring
}

type Painter func(Drawing)

type SurfacePainter func(SurfaceDrawing)
