// Code generated by k2go from runtime/popup_props.kry. DO NOT EDIT.
package kryon

// #import kryon_compat.generated.h
type PopupFlags int32

const (
	PopupFlagsNone PopupFlags = 0
	PopupTooltip   PopupFlags = 1
	PopupModal     PopupFlags = 2
	PopupContext   PopupFlags = 4
)

type PopupProps struct {
	Bounds    Rectangle
	ID        int32
	ClassName int32
	Open      *bool
	Disabled  bool
	Trigger   Rectangle
	Flags     PopupFlags
}
