// Code generated by k2go from runtime/primitive.kry. DO NOT EDIT.
package kryon

// #import drawing_props
type LinePrimitive struct {
	Bounds Rectangle
	X1     int32
	Y1     int32
	X2     int32
	Y2     int32
}

func Primitive_PrimitiveBackgroundBounds(width int32, height int32) Rectangle {
	var bounds Rectangle = Rectangle{}
	var value_0 float32 = 0.0
	bounds.X = value_0
	var value_1 float32 = 0.0
	bounds.Y = value_1
	var value_2 int32 = width
	var value_3 float32 = float32(value_2)
	bounds.Width = value_3
	var value_4 int32 = height
	var value_5 float32 = float32(value_4)
	bounds.Height = value_5
	var value_6 Rectangle = bounds
	return value_6
}

func Primitive_PrimitiveRectBounds(x int32, y int32, width int32, height int32) Rectangle {
	var bounds Rectangle = Rectangle{}
	var value_0 int32 = x
	var value_1 float32 = float32(value_0)
	bounds.X = value_1
	var value_2 int32 = y
	var value_3 float32 = float32(value_2)
	bounds.Y = value_3
	var value_4 int32 = width
	var value_5 float32 = float32(value_4)
	bounds.Width = value_5
	var value_6 int32 = height
	var value_7 float32 = float32(value_6)
	bounds.Height = value_7
	var value_8 Rectangle = bounds
	return value_8
}

func Primitive_PrimitiveLineFor(x1 int32, y1 int32, x2 int32, y2 int32) LinePrimitive {
	var line LinePrimitive = LinePrimitive{}
	var value_0 int32 = x1
	line.X1 = value_0
	var value_1 int32 = y1
	line.Y1 = value_1
	var value_2 int32 = x2
	line.X2 = value_2
	var value_3 int32 = y2
	line.Y2 = value_3
	var value_4 int32 = x1
	var min_x int32 = value_4
	var value_5 int32 = x2
	var max_x int32 = value_5
	var value_6 int32 = x2
	var value_7 int32 = min_x
	var value_8 bool = value_6 < value_7
	if value_8 {
		var value_9 int32 = x2
		min_x = value_9
		var value_10 int32 = x1
		max_x = value_10
	}
	var value_11 int32 = y1
	var min_y int32 = value_11
	var value_12 int32 = y2
	var max_y int32 = value_12
	var value_13 int32 = y2
	var value_14 int32 = min_y
	var value_15 bool = value_13 < value_14
	if value_15 {
		var value_16 int32 = y2
		min_y = value_16
		var value_17 int32 = y1
		max_y = value_17
	}
	var value_18 int32 = min_x
	var value_19 float32 = float32(value_18)
	line.Bounds.X = value_19
	var value_20 int32 = min_y
	var value_21 float32 = float32(value_20)
	line.Bounds.Y = value_21
	var value_22 int32 = max_x
	var value_23 int32 = min_x
	var value_24 int32 = int32(number_runtime_bits(uint64(value_22), uint64(value_23), 32, true, 2))
	var value_25 float32 = float32(value_24)
	line.Bounds.Width = value_25
	var value_26 int32 = max_y
	var value_27 int32 = min_y
	var value_28 int32 = int32(number_runtime_bits(uint64(value_26), uint64(value_27), 32, true, 2))
	var value_29 float32 = float32(value_28)
	line.Bounds.Height = value_29
	var value_30 LinePrimitive = line
	return value_30
}
