// Code generated by k2go from runtime/profile_header.kry. DO NOT EDIT.
package kryon

// #import drawing_props
type ProfileHeaderLayout struct {
	Height           int32
	TopPad           int32
	AvatarRadius     int32
	AvatarSize       int32
	PaddingX         int32
	AvatarCenterX    int32
	AvatarCenterY    int32
	NameX            int32
	NameY            int32
	CountY           int32
	MaxNameWidth     int32
	ProfileBounds    Rectangle
	AvatarTileBounds Rectangle
	IconBounds       Rectangle
	UsernameBounds   Rectangle
	FriendsBounds    Rectangle
	HeaderBounds     Rectangle
}

type ProfilePickerLayout struct {
	Width         int32
	Gap           int32
	ContentWidth  int32
	Columns       int32
	Cell          int32
	Rows          int32
	GridWidth     int32
	ContentHeight int32
	Height        int32
	MaxHeight     int32
	IconInset     int32
}

type ProfilePickerCell struct {
	Row        int32
	Column     int32
	Bounds     Rectangle
	IconBounds Rectangle
}

func ProfileHeader_ProfileScale(scale float32) float32 {
	var value_0 float32 = scale
	var value_1 float32 = 0.0
	var value_2 bool = value_0 <= value_1
	if value_2 {
		var value_3 float32 = 1.0
		return value_3
	}
	var value_4 float32 = scale
	return value_4
}

func ProfileHeader_ProfilePx(value float32, scale float32) int32 {
	var value_0 float32 = value
	var value_1 float32 = scale
	var value_2 float32 = ProfileHeader_ProfileScale(value_1)
	var value_3 float32 = value_0 * value_2
	var value_4 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_3), 32, true)), uint64(0), 32, true, 0))
	return value_4
}

func ProfileHeader_ProfileHeaderLayoutFor(x int32, y int32, width int32, requested_height int32, requested_padding_x int32, username_width int32, username_height int32, scale float32) ProfileHeaderLayout {
	var layout ProfileHeaderLayout = ProfileHeaderLayout{}
	var value_0 int32 = requested_height
	layout.Height = value_0
	var value_1 int32 = layout.Height
	var value_2 int32 = 0
	var value_3 bool = value_1 <= value_2
	if value_3 {
		var value_4 float32 = 138.0
		var value_5 float32 = scale
		var value_6 int32 = ProfileHeader_ProfilePx(value_4, value_5)
		layout.Height = value_6
	}
	var value_7 float32 = 24.0
	var value_8 float32 = scale
	var value_9 int32 = ProfileHeader_ProfilePx(value_7, value_8)
	layout.TopPad = value_9
	var value_10 float32 = 28.0
	var value_11 float32 = scale
	var value_12 int32 = ProfileHeader_ProfilePx(value_10, value_11)
	layout.AvatarRadius = value_12
	var value_13 int32 = layout.AvatarRadius
	var value_14 int32 = 2
	var value_15 int32 = int32(number_runtime_bits(uint64(value_13), uint64(value_14), 32, true, 3))
	layout.AvatarSize = value_15
	var value_16 int32 = requested_padding_x
	layout.PaddingX = value_16
	var value_17 int32 = layout.PaddingX
	var value_18 int32 = 0
	var value_19 bool = value_17 <= value_18
	if value_19 {
		var value_20 float32 = 16.0
		var value_21 float32 = scale
		var value_22 int32 = ProfileHeader_ProfilePx(value_20, value_21)
		layout.PaddingX = value_22
	}
	var value_23 int32 = x
	var value_24 int32 = layout.PaddingX
	var value_25 int32 = int32(number_runtime_bits(uint64(value_23), uint64(value_24), 32, true, 1))
	var value_26 int32 = layout.AvatarRadius
	var value_27 int32 = int32(number_runtime_bits(uint64(value_25), uint64(value_26), 32, true, 1))
	layout.AvatarCenterX = value_27
	var value_28 int32 = y
	var value_29 int32 = layout.TopPad
	var value_30 int32 = int32(number_runtime_bits(uint64(value_28), uint64(value_29), 32, true, 1))
	var value_31 int32 = layout.AvatarRadius
	var value_32 int32 = int32(number_runtime_bits(uint64(value_30), uint64(value_31), 32, true, 1))
	layout.AvatarCenterY = value_32
	var value_33 int32 = layout.AvatarCenterX
	var value_34 int32 = layout.AvatarRadius
	var value_35 int32 = int32(number_runtime_bits(uint64(value_33), uint64(value_34), 32, true, 1))
	var value_36 float32 = 14.0
	var value_37 float32 = scale
	var value_38 int32 = ProfileHeader_ProfilePx(value_36, value_37)
	var value_39 int32 = int32(number_runtime_bits(uint64(value_35), uint64(value_38), 32, true, 1))
	layout.NameX = value_39
	var value_40 int32 = layout.AvatarCenterY
	var value_41 float32 = 14.0
	var value_42 float32 = scale
	var value_43 int32 = ProfileHeader_ProfilePx(value_41, value_42)
	var value_44 int32 = int32(number_runtime_bits(uint64(value_40), uint64(value_43), 32, true, 2))
	layout.NameY = value_44
	var value_45 int32 = layout.AvatarCenterY
	var value_46 int32 = layout.AvatarRadius
	var value_47 int32 = int32(number_runtime_bits(uint64(value_45), uint64(value_46), 32, true, 1))
	var value_48 float32 = 8.0
	var value_49 float32 = scale
	var value_50 int32 = ProfileHeader_ProfilePx(value_48, value_49)
	var value_51 int32 = int32(number_runtime_bits(uint64(value_47), uint64(value_50), 32, true, 1))
	layout.CountY = value_51
	var value_52 int32 = width
	var value_53 int32 = layout.NameX
	var value_54 int32 = x
	var value_55 int32 = int32(number_runtime_bits(uint64(value_53), uint64(value_54), 32, true, 2))
	var value_56 int32 = int32(number_runtime_bits(uint64(value_52), uint64(value_55), 32, true, 2))
	var value_57 float32 = 12.0
	var value_58 float32 = scale
	var value_59 int32 = ProfileHeader_ProfilePx(value_57, value_58)
	var value_60 int32 = int32(number_runtime_bits(uint64(value_56), uint64(value_59), 32, true, 2))
	layout.MaxNameWidth = value_60
	var value_61 int32 = layout.MaxNameWidth
	var value_62 float32 = 48.0
	var value_63 float32 = scale
	var value_64 int32 = ProfileHeader_ProfilePx(value_62, value_63)
	var value_65 bool = value_61 < value_64
	if value_65 {
		var value_66 float32 = 48.0
		var value_67 float32 = scale
		var value_68 int32 = ProfileHeader_ProfilePx(value_66, value_67)
		layout.MaxNameWidth = value_68
	}
	var value_69 int32 = username_width
	var value_70 int32 = layout.MaxNameWidth
	var value_71 bool = value_69 > value_70
	if value_71 {
		var value_72 int32 = layout.MaxNameWidth
		username_width = value_72
	}
	var value_73 Rectangle = Rectangle{}
	var value_74 int32 = layout.AvatarCenterX
	var value_75 int32 = layout.AvatarRadius
	var value_76 int32 = int32(number_runtime_bits(uint64(value_74), uint64(value_75), 32, true, 2))
	var value_77 float32 = 4.0
	var value_78 float32 = scale
	var value_79 int32 = ProfileHeader_ProfilePx(value_77, value_78)
	var value_80 int32 = int32(number_runtime_bits(uint64(value_76), uint64(value_79), 32, true, 2))
	var value_81 float32 = float32(value_80)
	value_73.X = value_81
	var value_82 int32 = layout.AvatarCenterY
	var value_83 int32 = layout.AvatarRadius
	var value_84 int32 = int32(number_runtime_bits(uint64(value_82), uint64(value_83), 32, true, 2))
	var value_85 float32 = 4.0
	var value_86 float32 = scale
	var value_87 int32 = ProfileHeader_ProfilePx(value_85, value_86)
	var value_88 int32 = int32(number_runtime_bits(uint64(value_84), uint64(value_87), 32, true, 2))
	var value_89 float32 = float32(value_88)
	value_73.Y = value_89
	var value_90 int32 = layout.AvatarSize
	var value_91 float32 = 8.0
	var value_92 float32 = scale
	var value_93 int32 = ProfileHeader_ProfilePx(value_91, value_92)
	var value_94 int32 = int32(number_runtime_bits(uint64(value_90), uint64(value_93), 32, true, 1))
	var value_95 float32 = float32(value_94)
	value_73.Width = value_95
	var value_96 int32 = layout.AvatarSize
	var value_97 float32 = 8.0
	var value_98 float32 = scale
	var value_99 int32 = ProfileHeader_ProfilePx(value_97, value_98)
	var value_100 int32 = int32(number_runtime_bits(uint64(value_96), uint64(value_99), 32, true, 1))
	var value_101 float32 = float32(value_100)
	value_73.Height = value_101
	layout.ProfileBounds = value_73
	var value_102 Rectangle = Rectangle{}
	var value_103 int32 = layout.AvatarCenterX
	var value_104 int32 = layout.AvatarRadius
	var value_105 int32 = int32(number_runtime_bits(uint64(value_103), uint64(value_104), 32, true, 2))
	var value_106 float32 = 3.0
	var value_107 float32 = scale
	var value_108 int32 = ProfileHeader_ProfilePx(value_106, value_107)
	var value_109 int32 = int32(number_runtime_bits(uint64(value_105), uint64(value_108), 32, true, 2))
	var value_110 float32 = float32(value_109)
	value_102.X = value_110
	var value_111 int32 = layout.AvatarCenterY
	var value_112 int32 = layout.AvatarRadius
	var value_113 int32 = int32(number_runtime_bits(uint64(value_111), uint64(value_112), 32, true, 2))
	var value_114 float32 = 3.0
	var value_115 float32 = scale
	var value_116 int32 = ProfileHeader_ProfilePx(value_114, value_115)
	var value_117 int32 = int32(number_runtime_bits(uint64(value_113), uint64(value_116), 32, true, 2))
	var value_118 float32 = float32(value_117)
	value_102.Y = value_118
	var value_119 int32 = layout.AvatarSize
	var value_120 float32 = 6.0
	var value_121 float32 = scale
	var value_122 int32 = ProfileHeader_ProfilePx(value_120, value_121)
	var value_123 int32 = int32(number_runtime_bits(uint64(value_119), uint64(value_122), 32, true, 1))
	var value_124 float32 = float32(value_123)
	value_102.Width = value_124
	var value_125 int32 = layout.AvatarSize
	var value_126 float32 = 6.0
	var value_127 float32 = scale
	var value_128 int32 = ProfileHeader_ProfilePx(value_126, value_127)
	var value_129 int32 = int32(number_runtime_bits(uint64(value_125), uint64(value_128), 32, true, 1))
	var value_130 float32 = float32(value_129)
	value_102.Height = value_130
	layout.AvatarTileBounds = value_102
	var value_131 Rectangle = Rectangle{}
	var value_132 int32 = layout.AvatarCenterX
	var value_133 int32 = layout.AvatarRadius
	var value_134 int32 = int32(number_runtime_bits(uint64(value_132), uint64(value_133), 32, true, 2))
	var value_135 float32 = 3.0
	var value_136 float32 = scale
	var value_137 int32 = ProfileHeader_ProfilePx(value_135, value_136)
	var value_138 int32 = int32(number_runtime_bits(uint64(value_134), uint64(value_137), 32, true, 1))
	var value_139 float32 = float32(value_138)
	value_131.X = value_139
	var value_140 int32 = layout.AvatarCenterY
	var value_141 int32 = layout.AvatarRadius
	var value_142 int32 = int32(number_runtime_bits(uint64(value_140), uint64(value_141), 32, true, 2))
	var value_143 float32 = 3.0
	var value_144 float32 = scale
	var value_145 int32 = ProfileHeader_ProfilePx(value_143, value_144)
	var value_146 int32 = int32(number_runtime_bits(uint64(value_142), uint64(value_145), 32, true, 1))
	var value_147 float32 = float32(value_146)
	value_131.Y = value_147
	var value_148 int32 = layout.AvatarSize
	var value_149 float32 = 6.0
	var value_150 float32 = scale
	var value_151 int32 = ProfileHeader_ProfilePx(value_149, value_150)
	var value_152 int32 = int32(number_runtime_bits(uint64(value_148), uint64(value_151), 32, true, 2))
	var value_153 float32 = float32(value_152)
	value_131.Width = value_153
	var value_154 int32 = layout.AvatarSize
	var value_155 float32 = 6.0
	var value_156 float32 = scale
	var value_157 int32 = ProfileHeader_ProfilePx(value_155, value_156)
	var value_158 int32 = int32(number_runtime_bits(uint64(value_154), uint64(value_157), 32, true, 2))
	var value_159 float32 = float32(value_158)
	value_131.Height = value_159
	layout.IconBounds = value_131
	var value_160 Rectangle = Rectangle{}
	var value_161 int32 = layout.NameX
	var value_162 float32 = float32(value_161)
	value_160.X = value_162
	var value_163 int32 = layout.NameY
	var value_164 float32 = 4.0
	var value_165 float32 = scale
	var value_166 int32 = ProfileHeader_ProfilePx(value_164, value_165)
	var value_167 int32 = int32(number_runtime_bits(uint64(value_163), uint64(value_166), 32, true, 2))
	var value_168 float32 = float32(value_167)
	value_160.Y = value_168
	var value_169 int32 = username_width
	var value_170 float32 = float32(value_169)
	value_160.Width = value_170
	var value_171 int32 = username_height
	var value_172 float32 = float32(value_171)
	value_160.Height = value_172
	layout.UsernameBounds = value_160
	var value_173 Rectangle = Rectangle{}
	var value_174 int32 = x
	var value_175 float32 = float32(value_174)
	value_173.X = value_175
	var value_176 int32 = layout.CountY
	var value_177 float32 = float32(value_176)
	value_173.Y = value_177
	var value_178 int32 = width
	var value_179 float32 = float32(value_178)
	value_173.Width = value_179
	var value_180 float32 = 36.0
	var value_181 float32 = scale
	var value_182 int32 = ProfileHeader_ProfilePx(value_180, value_181)
	var value_183 float32 = float32(value_182)
	value_173.Height = value_183
	layout.FriendsBounds = value_173
	var value_184 Rectangle = Rectangle{}
	var value_185 int32 = x
	var value_186 float32 = float32(value_185)
	value_184.X = value_186
	var value_187 int32 = y
	var value_188 float32 = float32(value_187)
	value_184.Y = value_188
	var value_189 int32 = width
	var value_190 float32 = float32(value_189)
	value_184.Width = value_190
	var value_191 int32 = layout.Height
	var value_192 float32 = float32(value_191)
	value_184.Height = value_192
	layout.HeaderBounds = value_184
	var value_193 ProfileHeaderLayout = layout
	return value_193
}

func ProfileHeader_ProfilePickerLayoutFor(view_width int32, view_height int32, requested_max_width int32, icon_count int32, scale float32) ProfilePickerLayout {
	var layout ProfilePickerLayout = ProfilePickerLayout{}
	var value_0 int32 = requested_max_width
	layout.Width = value_0
	var value_1 int32 = layout.Width
	var value_2 int32 = 0
	var value_3 bool = value_1 > value_2
	if value_3 {
		var value_4 int32 = layout.Width
		var value_5 float32 = float32(value_4)
		var value_6 float32 = scale
		var value_7 int32 = ProfileHeader_ProfilePx(value_5, value_6)
		layout.Width = value_7
	}
	var value_8 int32 = layout.Width
	var value_9 int32 = 0
	var value_10 bool = value_8 <= value_9
	if value_10 {
		var value_11 float32 = 520.0
		var value_12 float32 = scale
		var value_13 int32 = ProfileHeader_ProfilePx(value_11, value_12)
		layout.Width = value_13
	}
	var value_14 int32 = layout.Width
	var value_15 int32 = view_width
	var value_16 float32 = 24.0
	var value_17 float32 = scale
	var value_18 int32 = ProfileHeader_ProfilePx(value_16, value_17)
	var value_19 int32 = int32(number_runtime_bits(uint64(value_15), uint64(value_18), 32, true, 2))
	var value_20 bool = value_14 > value_19
	if value_20 {
		var value_21 int32 = view_width
		var value_22 float32 = 24.0
		var value_23 float32 = scale
		var value_24 int32 = ProfileHeader_ProfilePx(value_22, value_23)
		var value_25 int32 = int32(number_runtime_bits(uint64(value_21), uint64(value_24), 32, true, 2))
		layout.Width = value_25
	}
	var value_26 int32 = layout.Width
	var value_27 float32 = 240.0
	var value_28 float32 = scale
	var value_29 int32 = ProfileHeader_ProfilePx(value_27, value_28)
	var value_30 bool = value_26 < value_29
	if value_30 {
		var value_31 float32 = 240.0
		var value_32 float32 = scale
		var value_33 int32 = ProfileHeader_ProfilePx(value_31, value_32)
		layout.Width = value_33
	}
	var value_34 float32 = 8.0
	var value_35 float32 = scale
	var value_36 int32 = ProfileHeader_ProfilePx(value_34, value_35)
	layout.Gap = value_36
	var value_37 int32 = layout.Width
	var value_38 float32 = 36.0
	var value_39 float32 = scale
	var value_40 int32 = ProfileHeader_ProfilePx(value_38, value_39)
	var value_41 int32 = int32(number_runtime_bits(uint64(value_37), uint64(value_40), 32, true, 2))
	layout.ContentWidth = value_41
	var value_42 int32 = layout.ContentWidth
	var value_43 int32 = layout.Gap
	var value_44 int32 = int32(number_runtime_bits(uint64(value_42), uint64(value_43), 32, true, 1))
	var value_45 float32 = 64.0
	var value_46 float32 = scale
	var value_47 int32 = ProfileHeader_ProfilePx(value_45, value_46)
	var value_48 int32 = layout.Gap
	var value_49 int32 = int32(number_runtime_bits(uint64(value_47), uint64(value_48), 32, true, 1))
	var value_50 int32 = int32(number_runtime_bits(uint64(value_44), uint64(value_49), 32, true, 4))
	layout.Columns = value_50
	var value_51 int32 = layout.Columns
	var value_52 int32 = 3
	var value_53 bool = value_51 < value_52
	if value_53 {
		var value_54 int32 = 3
		layout.Columns = value_54
	}
	var value_55 int32 = layout.Columns
	var value_56 int32 = icon_count
	var value_57 bool = value_55 > value_56
	if value_57 {
		var value_58 int32 = icon_count
		layout.Columns = value_58
	}
	var value_59 int32 = layout.Columns
	var value_60 int32 = 1
	var value_61 bool = value_59 < value_60
	if value_61 {
		var value_62 int32 = 1
		layout.Columns = value_62
	}
	var value_63 int32 = layout.ContentWidth
	var value_64 int32 = layout.Columns
	var value_65 int32 = 1
	var value_66 int32 = int32(number_runtime_bits(uint64(value_64), uint64(value_65), 32, true, 2))
	var value_67 int32 = layout.Gap
	var value_68 int32 = int32(number_runtime_bits(uint64(value_66), uint64(value_67), 32, true, 3))
	var value_69 int32 = int32(number_runtime_bits(uint64(value_63), uint64(value_68), 32, true, 2))
	var value_70 int32 = layout.Columns
	var value_71 int32 = int32(number_runtime_bits(uint64(value_69), uint64(value_70), 32, true, 4))
	layout.Cell = value_71
	var value_72 int32 = layout.Cell
	var value_73 float32 = 64.0
	var value_74 float32 = scale
	var value_75 int32 = ProfileHeader_ProfilePx(value_73, value_74)
	var value_76 bool = value_72 > value_75
	if value_76 {
		var value_77 float32 = 64.0
		var value_78 float32 = scale
		var value_79 int32 = ProfileHeader_ProfilePx(value_77, value_78)
		layout.Cell = value_79
	}
	var value_80 int32 = layout.Cell
	var value_81 float32 = 52.0
	var value_82 float32 = scale
	var value_83 int32 = ProfileHeader_ProfilePx(value_81, value_82)
	var value_84 bool = value_80 < value_83
	if value_84 {
		var value_85 float32 = 52.0
		var value_86 float32 = scale
		var value_87 int32 = ProfileHeader_ProfilePx(value_85, value_86)
		layout.Cell = value_87
	}
	var value_88 int32 = layout.Columns
	var value_89 int32 = layout.Cell
	var value_90 int32 = int32(number_runtime_bits(uint64(value_88), uint64(value_89), 32, true, 3))
	var value_91 int32 = layout.Columns
	var value_92 int32 = 1
	var value_93 int32 = int32(number_runtime_bits(uint64(value_91), uint64(value_92), 32, true, 2))
	var value_94 int32 = layout.Gap
	var value_95 int32 = int32(number_runtime_bits(uint64(value_93), uint64(value_94), 32, true, 3))
	var value_96 int32 = int32(number_runtime_bits(uint64(value_90), uint64(value_95), 32, true, 1))
	layout.GridWidth = value_96
	var value_97 int32 = layout.Columns
	var value_98 int32 = 0
	var value_99 bool = value_97 > value_98
	if value_99 {
		var value_100 int32 = icon_count
		var value_101 int32 = layout.Columns
		var value_102 int32 = int32(number_runtime_bits(uint64(value_100), uint64(value_101), 32, true, 1))
		var value_103 int32 = 1
		var value_104 int32 = int32(number_runtime_bits(uint64(value_102), uint64(value_103), 32, true, 2))
		var value_105 int32 = layout.Columns
		var value_106 int32 = int32(number_runtime_bits(uint64(value_104), uint64(value_105), 32, true, 4))
		layout.Rows = value_106
	}
	var value_107 int32 = layout.Rows
	var value_108 int32 = 0
	var value_109 bool = value_107 > value_108
	if value_109 {
		var value_110 int32 = layout.Rows
		var value_111 int32 = layout.Cell
		var value_112 int32 = int32(number_runtime_bits(uint64(value_110), uint64(value_111), 32, true, 3))
		var value_113 int32 = layout.Rows
		var value_114 int32 = 1
		var value_115 int32 = int32(number_runtime_bits(uint64(value_113), uint64(value_114), 32, true, 2))
		var value_116 int32 = layout.Gap
		var value_117 int32 = int32(number_runtime_bits(uint64(value_115), uint64(value_116), 32, true, 3))
		var value_118 int32 = int32(number_runtime_bits(uint64(value_112), uint64(value_117), 32, true, 1))
		layout.ContentHeight = value_118
	}
	var value_119 float32 = 74.0
	var value_120 float32 = scale
	var value_121 int32 = ProfileHeader_ProfilePx(value_119, value_120)
	var value_122 int32 = layout.ContentHeight
	var value_123 int32 = int32(number_runtime_bits(uint64(value_121), uint64(value_122), 32, true, 1))
	var value_124 float32 = 18.0
	var value_125 float32 = scale
	var value_126 int32 = ProfileHeader_ProfilePx(value_124, value_125)
	var value_127 int32 = int32(number_runtime_bits(uint64(value_123), uint64(value_126), 32, true, 1))
	layout.Height = value_127
	var value_128 int32 = view_height
	var value_129 float32 = 24.0
	var value_130 float32 = scale
	var value_131 int32 = ProfileHeader_ProfilePx(value_129, value_130)
	var value_132 int32 = int32(number_runtime_bits(uint64(value_128), uint64(value_131), 32, true, 2))
	layout.MaxHeight = value_132
	var value_133 int32 = layout.Height
	var value_134 int32 = layout.MaxHeight
	var value_135 bool = value_133 > value_134
	if value_135 {
		var value_136 int32 = layout.MaxHeight
		layout.Height = value_136
	}
	var value_137 float32 = 6.0
	var value_138 float32 = scale
	var value_139 int32 = ProfileHeader_ProfilePx(value_137, value_138)
	layout.IconInset = value_139
	var value_140 ProfilePickerLayout = layout
	return value_140
}

func ProfileHeader_ProfilePickerCellFor(index int32, content_x int32, content_y int32, content_width int32, picker ProfilePickerLayout) ProfilePickerCell {
	var cell ProfilePickerCell = ProfilePickerCell{}
	var value_0 int32 = picker.Columns
	var value_1 int32 = 0
	var value_2 bool = value_0 <= value_1
	if value_2 {
		var value_3 ProfilePickerCell = cell
		return value_3
	}
	var value_4 int32 = index
	var value_5 int32 = picker.Columns
	var value_6 int32 = int32(number_runtime_bits(uint64(value_4), uint64(value_5), 32, true, 4))
	cell.Row = value_6
	var value_7 int32 = index
	var value_8 int32 = picker.Columns
	var value_9 int32 = int32(number_runtime_bits(uint64(value_7), uint64(value_8), 32, true, 5))
	cell.Column = value_9
	var value_10 int32 = content_x
	var value_11 int32 = content_width
	var value_12 int32 = picker.GridWidth
	var value_13 int32 = int32(number_runtime_bits(uint64(value_11), uint64(value_12), 32, true, 2))
	var value_14 int32 = 2
	var value_15 int32 = int32(number_runtime_bits(uint64(value_13), uint64(value_14), 32, true, 4))
	var value_16 int32 = int32(number_runtime_bits(uint64(value_10), uint64(value_15), 32, true, 1))
	var value_17 int32 = cell.Column
	var value_18 int32 = picker.Cell
	var value_19 int32 = picker.Gap
	var value_20 int32 = int32(number_runtime_bits(uint64(value_18), uint64(value_19), 32, true, 1))
	var value_21 int32 = int32(number_runtime_bits(uint64(value_17), uint64(value_20), 32, true, 3))
	var value_22 int32 = int32(number_runtime_bits(uint64(value_16), uint64(value_21), 32, true, 1))
	var x int32 = value_22
	var value_23 int32 = content_y
	var value_24 int32 = cell.Row
	var value_25 int32 = picker.Cell
	var value_26 int32 = picker.Gap
	var value_27 int32 = int32(number_runtime_bits(uint64(value_25), uint64(value_26), 32, true, 1))
	var value_28 int32 = int32(number_runtime_bits(uint64(value_24), uint64(value_27), 32, true, 3))
	var value_29 int32 = int32(number_runtime_bits(uint64(value_23), uint64(value_28), 32, true, 1))
	var y int32 = value_29
	var value_30 Rectangle = Rectangle{}
	var value_31 int32 = x
	var value_32 float32 = float32(value_31)
	value_30.X = value_32
	var value_33 int32 = y
	var value_34 float32 = float32(value_33)
	value_30.Y = value_34
	var value_35 int32 = picker.Cell
	var value_36 float32 = float32(value_35)
	value_30.Width = value_36
	var value_37 int32 = picker.Cell
	var value_38 float32 = float32(value_37)
	value_30.Height = value_38
	cell.Bounds = value_30
	var value_39 Rectangle = Rectangle{}
	var value_40 int32 = x
	var value_41 int32 = picker.IconInset
	var value_42 int32 = int32(number_runtime_bits(uint64(value_40), uint64(value_41), 32, true, 1))
	var value_43 float32 = float32(value_42)
	value_39.X = value_43
	var value_44 int32 = y
	var value_45 int32 = picker.IconInset
	var value_46 int32 = int32(number_runtime_bits(uint64(value_44), uint64(value_45), 32, true, 1))
	var value_47 float32 = float32(value_46)
	value_39.Y = value_47
	var value_48 int32 = picker.Cell
	var value_49 int32 = picker.IconInset
	var value_50 int32 = 2
	var value_51 int32 = int32(number_runtime_bits(uint64(value_49), uint64(value_50), 32, true, 3))
	var value_52 int32 = int32(number_runtime_bits(uint64(value_48), uint64(value_51), 32, true, 2))
	var value_53 float32 = float32(value_52)
	value_39.Width = value_53
	var value_54 int32 = picker.Cell
	var value_55 int32 = picker.IconInset
	var value_56 int32 = 2
	var value_57 int32 = int32(number_runtime_bits(uint64(value_55), uint64(value_56), 32, true, 3))
	var value_58 int32 = int32(number_runtime_bits(uint64(value_54), uint64(value_57), 32, true, 2))
	var value_59 float32 = float32(value_58)
	value_39.Height = value_59
	cell.IconBounds = value_39
	var value_60 ProfilePickerCell = cell
	return value_60
}
