// Code generated by k2go from runtime/profile_icon_props.kry. DO NOT EDIT.
package kryon

// #import ui_icon_types.h
type SyncProfileIcon int32

const (
	SYNCPROFILEICONNONE      SyncProfileIcon = 0
	SYNCPROFILEICONBIRD      SyncProfileIcon = 1
	SYNCPROFILEICONBOWL      SyncProfileIcon = 2
	SYNCPROFILEICONCACTUS    SyncProfileIcon = 3
	SYNCPROFILEICONHEART     SyncProfileIcon = 4
	SYNCPROFILEICONINCENSE   SyncProfileIcon = 5
	SYNCPROFILEICONLOTUS     SyncProfileIcon = 6
	SYNCPROFILEICONTREE1     SyncProfileIcon = 7
	SYNCPROFILEICONTREE2     SyncProfileIcon = 8
	SYNCPROFILEICONTREE3     SyncProfileIcon = 9
	SYNCPROFILEICONTREE4     SyncProfileIcon = 10
	SYNCPROFILEICONTREE5     SyncProfileIcon = 11
	SYNCPROFILEICONBAMBUS    SyncProfileIcon = 12
	SYNCPROFILEICONBUSH      SyncProfileIcon = 13
	SYNCPROFILEICONCOFFEE    SyncProfileIcon = 14
	SYNCPROFILEICONFLOWER1   SyncProfileIcon = 15
	SYNCPROFILEICONFLOWER2   SyncProfileIcon = 16
	SYNCPROFILEICONMOUNTAIN  SyncProfileIcon = 17
	SYNCPROFILEICONMUSHROOM  SyncProfileIcon = 18
	SYNCPROFILEICONPERSON1   SyncProfileIcon = 19
	SYNCPROFILEICONRAINBOW   SyncProfileIcon = 20
	SYNCPROFILEICONTENT      SyncProfileIcon = 21
	SYNCPROFILEICONBUTTERFLY SyncProfileIcon = 22
	SYNCPROFILEICONDRAGONFLY SyncProfileIcon = 23
	SYNCPROFILEICONFIREPLACE SyncProfileIcon = 24
	SYNCPROFILEICONFOX       SyncProfileIcon = 25
	SYNCPROFILEICONPALM      SyncProfileIcon = 26
	SYNCPROFILEICONCAT       SyncProfileIcon = 27
	SYNCPROFILEICONTURTLE    SyncProfileIcon = 28
	SYNCPROFILEICONMOON      SyncProfileIcon = 29
)
