// Code generated by k2go from runtime/progress_props.kry. DO NOT EDIT.
package kryon

// #import kryon_compat.generated.h
type ProgressProps struct {
	Bounds    Rectangle
	Min       int32
	Max       int32
	Value     int32
	Label     string
	ClassName int32
}
