// Code generated by k2go from runtime/rows.kry. DO NOT EDIT.
package kryon

// #import control_props
// #import style
type InfoRowsMetrics struct {
	RowHeight int32
	PaddingX  int32
}

type InfoRowsLayout struct {
	Background Rectangle
}

type InfoRowLayout struct {
	TextBounds Rectangle
	SeparatorY int32
}

type LabelTextFieldMetrics struct {
	LabelHeight int32
	FieldHeight int32
	Gap         int32
	BottomGap   int32
}

type LabelTextFieldLayout struct {
	LabelBounds Rectangle
	FieldBounds Rectangle
}

type SectionLabelMetrics struct {
	Height       int32
	IconDiameter int32
	InfoGap      int32
	InfoYOffset  int32
}

type CheckboxRowMetrics struct {
	Height int32
}

type ButtonRowMetrics struct {
	Height       int32
	Gap          int32
	ItemPaddingX int32
	MinWidth     int32
	MaxWidth     int32
}

type ButtonRowPlacement struct {
	StartX      int32
	ButtonWidth int32
	TotalWidth  int32
}

type ButtonRowWrapDecision struct {
	Wraps    bool
	RowWidth int32
}

type SpinboxRowMetrics struct {
	RowHeight          int32
	ControlWidth       int32
	LabelGap           int32
	ControlHeightInset int32
}

type FormRectResult struct {
	Bounds      Rectangle
	NextCursorY int32
}

type SpinboxRowLayout struct {
	LabelBounds   Rectangle
	SpinboxBounds Rectangle
	ControlWidth  int32
	LabelWidth    int32
}

func Rows_RowsMetric(fields uint32, field uint32, value float32, fallback float32, scale float32, allow_zero bool) int32 {
	if scale <= 0.0 {
		scale = 1.0
	}
	var value_0 bool = (uint32(number_runtime_bits(uint64(fields), uint64(field), 32, false, 8))) == uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0))
	var value_1 bool = value_0
	if !value_1 {
		value_1 = (value < 0.0)
	}
	var value_2 bool = value_1
	if !value_2 {
		var value_3 bool = !allow_zero
		if value_3 {
			value_3 = (value <= 0.0)
		}
		value_2 = value_3
	}
	if value_2 {
		value = fallback
	}
	var value_4 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((value*scale)), 32, true)), uint64(0), 32, true, 0))
	return value_4
}

func Rows_RowsRequestedMetric(requested int32, fields uint32, field uint32, value float32, fallback float32, scale float32, allow_zero bool) int32 {
	if requested > 0 {
		return requested
	}
	var value_0 int32 = Rows_RowsMetric(fields, field, value, fallback, scale, allow_zero)
	return value_0
}

func Rows_RowsMutedAlpha(alpha uint8) uint8 {
	var value_0 uint8 = uint8(number_runtime_bits(uint64(number_runtime_float(float64((float32(alpha)*0.72)), 8, false)), uint64(0), 8, false, 0))
	return value_0
}

func Rows_InfoRowsTextRole() int32 {
	return 0
}

func Rows_LabelTextFieldLabelRole() int32 {
	return 1
}

func Rows_LabelTextFieldFieldRole() int32 {
	return 2
}

func Rows_SectionLabelRole() int32 {
	return 3
}

func Rows_CheckboxRowRole() int32 {
	return 4
}

func Rows_ButtonRowPrimaryRole() int32 {
	return 5
}

func Rows_ButtonRowSecondaryRole() int32 {
	return 6
}

func Rows_SpinboxRowLabelRole() int32 {
	return 7
}

func Rows_SpinboxRowControlRole() int32 {
	return 8
}

func Rows_InfoRowsMetricsFor(row_height int32, padding_x int32, scale float32, row StyleFrame) InfoRowsMetrics {
	var metrics InfoRowsMetrics = InfoRowsMetrics{}
	var value_0 uint32 = row.Value.Fields
	var value_1 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_2 float32 = row.Value.OffsetY
	var value_3 float32 = 32.0
	var value_4 int32 = Rows_RowsRequestedMetric(row_height, value_0, value_1, value_2, value_3, scale, false)
	metrics.RowHeight = value_4
	var value_5 uint32 = row.Value.Fields
	var value_6 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))
	var value_7 float32 = row.Value.PaddingX
	var value_8 float32 = 10.0
	var value_9 int32 = Rows_RowsRequestedMetric(padding_x, value_5, value_6, value_7, value_8, scale, true)
	metrics.PaddingX = value_9
	return metrics
}

func Rows_InfoRowsLayoutFor(x int32, y int32, width int32, row_count int32, metrics InfoRowsMetrics) InfoRowsLayout {
	var layout InfoRowsLayout = InfoRowsLayout{}
	var h int32 = (int32(number_runtime_bits(uint64(row_count), uint64(metrics.RowHeight), 32, true, 3)))
	if width < 0 {
		width = 0
	}
	if h < 0 {
		h = 0
	}
	layout.Background.X = float32(x)
	layout.Background.Y = float32(y)
	layout.Background.Width = float32(width)
	layout.Background.Height = float32(h)
	return layout
}

func Rows_InfoRowLayoutFor(x int32, y int32, width int32, row_index int32, metrics InfoRowsMetrics) InfoRowLayout {
	var layout InfoRowLayout = InfoRowLayout{}
	if row_index < 0 {
		row_index = 0
	}
	var value_0 int32 = int32(number_runtime_bits(uint64(y), uint64((int32(number_runtime_bits(uint64(row_index), uint64(metrics.RowHeight), 32, true, 3)))), 32, true, 1))
	var row_y int32 = value_0
	var value_1 int32 = int32(number_runtime_bits(uint64(width), uint64((int32(number_runtime_bits(uint64(metrics.PaddingX), uint64(2), 32, true, 3)))), 32, true, 2))
	var text_width int32 = value_1
	if text_width < 0 {
		text_width = 0
	}
	layout.TextBounds.X = float32((int32(number_runtime_bits(uint64(x), uint64(metrics.PaddingX), 32, true, 1))))
	layout.TextBounds.Y = float32(row_y)
	layout.TextBounds.Width = float32(text_width)
	layout.TextBounds.Height = float32(metrics.RowHeight)
	layout.SeparatorY = row_y
	return layout
}

func Rows_LabelTextFieldMetricsFor(label_height int32, field_height int32, gap int32, bottom_gap int32, scale float32, label StyleFrame, field StyleFrame) LabelTextFieldMetrics {
	var metrics LabelTextFieldMetrics = LabelTextFieldMetrics{}
	var value_0 uint32 = label.Value.Fields
	var value_1 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_2 float32 = label.Value.OffsetY
	var value_3 float32 = 22.0
	var value_4 int32 = Rows_RowsRequestedMetric(label_height, value_0, value_1, value_2, value_3, scale, false)
	metrics.LabelHeight = value_4
	var value_5 uint32 = field.Value.Fields
	var value_6 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_7 float32 = field.Value.OffsetY
	var value_8 float32 = 40.0
	var value_9 int32 = Rows_RowsRequestedMetric(field_height, value_5, value_6, value_7, value_8, scale, false)
	metrics.FieldHeight = value_9
	if gap > 0 {
		metrics.Gap = gap
	} else {
		var value_10 uint32 = label.Value.Fields
		var value_11 uint32 = uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))
		var value_12 float32 = label.Value.Gap
		var value_13 float32 = 0.0
		var value_14 int32 = Rows_RowsMetric(value_10, value_11, value_12, value_13, scale, true)
		metrics.Gap = value_14
	}
	var value_15 uint32 = field.Value.Fields
	var value_16 uint32 = uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))
	var value_17 float32 = field.Value.Gap
	var value_18 float32 = 24.0
	var value_19 int32 = Rows_RowsRequestedMetric(bottom_gap, value_15, value_16, value_17, value_18, scale, true)
	metrics.BottomGap = value_19
	return metrics
}

func Rows_LabelTextFieldLayoutFor(x int32, y int32, width int32, requested_bounds Rectangle, metrics LabelTextFieldMetrics) LabelTextFieldLayout {
	var layout LabelTextFieldLayout = LabelTextFieldLayout{}
	layout.LabelBounds.X = float32(x)
	layout.LabelBounds.Y = float32(y)
	layout.LabelBounds.Width = float32(width)
	layout.LabelBounds.Height = float32(metrics.LabelHeight)
	var value_0 bool = (requested_bounds.Width > 0.0)
	if value_0 {
		value_0 = (requested_bounds.Height > 0.0)
	}
	if value_0 {
		layout.FieldBounds = requested_bounds
		return layout
	}
	layout.FieldBounds.X = float32(x)
	var value_1 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(y), uint64(metrics.LabelHeight), 32, true, 1)))), uint64(metrics.Gap), 32, true, 1))
	layout.FieldBounds.Y = float32(value_1)
	layout.FieldBounds.Width = float32(width)
	layout.FieldBounds.Height = float32(metrics.FieldHeight)
	return layout
}

func Rows_SectionLabelMetricsFor(height int32, icon_diameter int32, scale float32, label StyleFrame) SectionLabelMetrics {
	var metrics SectionLabelMetrics = SectionLabelMetrics{}
	var value_0 uint32 = label.Value.Fields
	var value_1 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_2 float32 = label.Value.OffsetY
	var value_3 float32 = 24.0
	var value_4 int32 = Rows_RowsRequestedMetric(height, value_0, value_1, value_2, value_3, scale, false)
	metrics.Height = value_4
	var value_5 uint32 = label.Value.Fields
	var value_6 uint32 = uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))
	var value_7 float32 = label.Value.IconSize
	var value_8 float32 = 18.0
	var value_9 int32 = Rows_RowsRequestedMetric(icon_diameter, value_5, value_6, value_7, value_8, scale, false)
	metrics.IconDiameter = value_9
	var value_10 uint32 = label.Value.Fields
	var value_11 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))
	var value_12 float32 = label.Value.PaddingX
	var value_13 float32 = 16.0
	var value_14 int32 = Rows_RowsMetric(value_10, value_11, value_12, value_13, scale, true)
	metrics.InfoGap = value_14
	var value_15 uint32 = label.Value.Fields
	var value_16 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0))
	var value_17 float32 = label.Value.PaddingY
	var value_18 float32 = 1.0
	var value_19 int32 = Rows_RowsMetric(value_15, value_16, value_17, value_18, scale, true)
	metrics.InfoYOffset = value_19
	return metrics
}

func Rows_CheckboxRowMetricsFor(height int32, scale float32, row StyleFrame) CheckboxRowMetrics {
	var metrics CheckboxRowMetrics = CheckboxRowMetrics{}
	var value_0 uint32 = row.Value.Fields
	var value_1 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_2 float32 = row.Value.OffsetY
	var value_3 float32 = 42.0
	var value_4 int32 = Rows_RowsRequestedMetric(height, value_0, value_1, value_2, value_3, scale, false)
	metrics.Height = value_4
	return metrics
}

func Rows_ButtonRowMetricsFor(height int32, gap int32, scale float32, row StyleFrame, item StyleFrame) ButtonRowMetrics {
	var metrics ButtonRowMetrics = ButtonRowMetrics{}
	var value_0 uint32 = row.Value.Fields
	var value_1 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_2 float32 = row.Value.OffsetY
	var value_3 float32 = 30.0
	var value_4 int32 = Rows_RowsRequestedMetric(height, value_0, value_1, value_2, value_3, scale, false)
	metrics.Height = value_4
	if gap > 0 {
		metrics.Gap = gap
	} else {
		var value_5 uint32 = row.Value.Fields
		var value_6 uint32 = uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))
		var value_7 float32 = row.Value.Gap
		var value_8 float32 = 6.0
		var value_9 int32 = Rows_RowsMetric(value_5, value_6, value_7, value_8, scale, true)
		metrics.Gap = value_9
	}
	var value_10 uint32 = item.Value.Fields
	var value_11 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))
	var value_12 float32 = item.Value.PaddingX
	var value_13 float32 = 10.0
	var value_14 int32 = Rows_RowsMetric(value_10, value_11, value_12, value_13, scale, true)
	metrics.ItemPaddingX = value_14
	var value_15 uint32 = item.Value.Fields
	var value_16 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_17 float32 = item.Value.OffsetX
	var value_18 float32 = 76.0
	var value_19 int32 = Rows_RowsMetric(value_15, value_16, value_17, value_18, scale, false)
	metrics.MinWidth = value_19
	var value_20 uint32 = item.Value.Fields
	var value_21 uint32 = uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))
	var value_22 float32 = item.Value.IconSize
	var value_23 float32 = 144.0
	var value_24 int32 = Rows_RowsMetric(value_20, value_21, value_22, value_23, scale, false)
	metrics.MaxWidth = value_24
	if metrics.MaxWidth < metrics.MinWidth {
		metrics.MaxWidth = metrics.MinWidth
	}
	return metrics
}

func Rows_ButtonRowItemWidth(label_width int32, metrics ButtonRowMetrics) int32 {
	var value_0 int32 = int32(number_runtime_bits(uint64(label_width), uint64((int32(number_runtime_bits(uint64(metrics.ItemPaddingX), uint64(2), 32, true, 3)))), 32, true, 1))
	var width int32 = value_0
	if width < metrics.MinWidth {
		width = metrics.MinWidth
	}
	if width > metrics.MaxWidth {
		width = metrics.MaxWidth
	}
	return width
}

func Rows_ButtonRowWrapFor(row_width int32, item_width int32, total_width int32, gap int32) ButtonRowWrapDecision {
	var decision ButtonRowWrapDecision = ButtonRowWrapDecision{}
	if item_width < 0 {
		item_width = 0
	}
	if gap < 0 {
		gap = 0
	}
	var next_width int32 = item_width
	if row_width > 0 {
		var value_0 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(row_width), uint64(gap), 32, true, 1)))), uint64(item_width), 32, true, 1))
		next_width = value_0
	}
	var value_1 bool = (row_width > 0)
	if value_1 {
		value_1 = (total_width > 0)
	}
	var value_2 bool = value_1
	if value_2 {
		value_2 = (next_width > total_width)
	}
	if value_2 {
		decision.Wraps = true
		decision.RowWidth = item_width
		return decision
	}
	decision.RowWidth = next_width
	return decision
}

func Rows_ButtonRowPlacementFor(x int32, width int32, row_count int32, gap int32) ButtonRowPlacement {
	var placement ButtonRowPlacement = ButtonRowPlacement{}
	var value_0 bool = (row_count <= 0)
	if !value_0 {
		value_0 = (width <= 0)
	}
	if value_0 {
		placement.StartX = x
		return placement
	}
	var value_1 int32 = int32(number_runtime_bits(uint64(gap), uint64((int32(number_runtime_bits(uint64(row_count), uint64(1), 32, true, 2)))), 32, true, 3))
	var usable int32 = (int32(number_runtime_bits(uint64(width), uint64(value_1), 32, true, 2)))
	placement.ButtonWidth = (int32(number_runtime_bits(uint64(usable), uint64(row_count), 32, true, 4)))
	if placement.ButtonWidth < 0 {
		placement.ButtonWidth = 0
	}
	var value_2 int32 = int32(number_runtime_bits(uint64(gap), uint64((int32(number_runtime_bits(uint64(row_count), uint64(1), 32, true, 2)))), 32, true, 3))
	var value_3 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(placement.ButtonWidth), uint64(row_count), 32, true, 3)))), uint64(value_2), 32, true, 1))
	placement.TotalWidth = value_3
	var value_4 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(width), uint64(placement.TotalWidth), 32, true, 2)))), uint64(2), 32, true, 4))
	placement.StartX = (int32(number_runtime_bits(uint64(x), uint64(value_4), 32, true, 1)))
	return placement
}

func Rows_ButtonRowTotalHeight(row_count int32, row_height int32, gap int32) int32 {
	if row_count <= 0 {
		return 0
	}
	if row_height < 0 {
		row_height = 0
	}
	if gap < 0 {
		gap = 0
	}
	var value_0 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(row_count), uint64(1), 32, true, 2)))), uint64(gap), 32, true, 3))
	var value_1 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(row_count), uint64(row_height), 32, true, 3)))), uint64(value_0), 32, true, 1))
	return value_1
}

func Rows_ButtonRowNextY(y int32, row_height int32, gap int32) int32 {
	if row_height < 0 {
		row_height = 0
	}
	if gap < 0 {
		gap = 0
	}
	var value_0 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(y), uint64(row_height), 32, true, 1)))), uint64(gap), 32, true, 1))
	return value_0
}

func Rows_SpinboxRowMetricsFor(row_height int32, control_width int32, scale float32, row StyleFrame, control StyleFrame) SpinboxRowMetrics {
	var metrics SpinboxRowMetrics = SpinboxRowMetrics{}
	var value_0 uint32 = row.Value.Fields
	var value_1 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_2 float32 = row.Value.OffsetY
	var value_3 float32 = 54.0
	var value_4 int32 = Rows_RowsRequestedMetric(row_height, value_0, value_1, value_2, value_3, scale, false)
	metrics.RowHeight = value_4
	var value_5 uint32 = control.Value.Fields
	var value_6 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_7 float32 = control.Value.OffsetX
	var value_8 float32 = 156.0
	var value_9 int32 = Rows_RowsRequestedMetric(control_width, value_5, value_6, value_7, value_8, scale, false)
	metrics.ControlWidth = value_9
	var value_10 uint32 = row.Value.Fields
	var value_11 uint32 = uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))
	var value_12 float32 = row.Value.Gap
	var value_13 float32 = 12.0
	var value_14 int32 = Rows_RowsMetric(value_10, value_11, value_12, value_13, scale, true)
	metrics.LabelGap = value_14
	var value_15 uint32 = control.Value.Fields
	var value_16 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0))
	var value_17 float32 = control.Value.PaddingY
	var value_18 float32 = 14.0
	var value_19 int32 = Rows_RowsMetric(value_15, value_16, value_17, value_18, scale, true)
	metrics.ControlHeightInset = value_19
	return metrics
}

func Rows_FormAdvanceY(cursor_y int32, height int32, gap int32) int32 {
	var next_y int32 = cursor_y
	if height > 0 {
		var value_0 int32 = next_y
		next_y = int32(number_runtime_bits(uint64(value_0), uint64(height), 32, true, 1))
	}
	if gap > 0 {
		var value_1 int32 = next_y
		next_y = int32(number_runtime_bits(uint64(value_1), uint64(gap), 32, true, 1))
	}
	return next_y
}

func Rows_FormRectFor(x int32, cursor_y int32, width int32, height int32, gap int32) FormRectResult {
	var result FormRectResult = FormRectResult{}
	var rect_h int32 = height
	if rect_h < 0 {
		rect_h = 0
	}
	result.Bounds.X = float32(x)
	result.Bounds.Y = float32(cursor_y)
	result.Bounds.Width = float32(width)
	result.Bounds.Height = float32(rect_h)
	var value_0 int32 = Rows_FormAdvanceY(cursor_y, height, gap)
	result.NextCursorY = value_0
	return result
}

func Rows_SpinboxRowLayoutFor(x int32, y int32, width int32, label_width int32, requested_bounds Rectangle, metrics SpinboxRowMetrics) SpinboxRowLayout {
	var layout SpinboxRowLayout = SpinboxRowLayout{}
	var height int32 = metrics.RowHeight
	var control_w int32 = metrics.ControlWidth
	if control_w > width {
		control_w = width
	}
	if control_w < 0 {
		control_w = 0
	}
	var label_w int32 = label_width
	if label_w <= 0 {
		var value_0 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(width), uint64(control_w), 32, true, 2)))), uint64(metrics.LabelGap), 32, true, 2))
		label_w = value_0
	}
	if label_w < 0 {
		label_w = 0
	}
	var value_1 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(requested_bounds.Width), 32, true)), uint64(0), 32, true, 0))
	var spinbox_w int32 = value_1
	var value_2 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(requested_bounds.Height), 32, true)), uint64(0), 32, true, 0))
	var spinbox_h int32 = value_2
	if spinbox_w <= 0 {
		spinbox_w = control_w
	}
	if spinbox_h <= 0 {
		spinbox_h = (int32(number_runtime_bits(uint64(height), uint64(metrics.ControlHeightInset), 32, true, 2)))
	}
	if spinbox_w < 0 {
		spinbox_w = 0
	}
	if spinbox_h < 0 {
		spinbox_h = 0
	}
	layout.LabelBounds.X = float32(x)
	layout.LabelBounds.Y = float32(y)
	layout.LabelBounds.Width = float32(label_w)
	layout.LabelBounds.Height = float32(height)
	var value_3 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(x), uint64(width), 32, true, 1)))), uint64(spinbox_w), 32, true, 2))
	layout.SpinboxBounds.X = float32(value_3)
	var value_4 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(height), uint64(spinbox_h), 32, true, 2)))), uint64(2), 32, true, 4))
	layout.SpinboxBounds.Y = float32((int32(number_runtime_bits(uint64(y), uint64(value_4), 32, true, 1))))
	layout.SpinboxBounds.Width = float32(spinbox_w)
	layout.SpinboxBounds.Height = float32(spinbox_h)
	layout.ControlWidth = control_w
	layout.LabelWidth = label_w
	return layout
}
