// Code generated by k2go from runtime/slider.kry. DO NOT EDIT.
package kryon

// #import button
// #import control_props
// #import drawing_props
// #import style
// #import surface
// #import theme
type SliderSpec struct {
	Bounds   Rectangle
	Ratio    float32
	Vertical bool
	Active   bool
	Hovered  bool
	Disabled bool
	Scale    float32
	Palette  Palette
	Metrics  Metrics
}

type SliderPaint struct {
	Bounds              Rectangle
	TrackBounds         Rectangle
	ActiveBounds        Rectangle
	ThumbX              float32
	ThumbY              float32
	ThumbRadius         float32
	GlowRadius          float32
	GlowColor           uint32
	ThumbFillColor      uint32
	ThumbEdgeColor      uint32
	ThumbShadowColor    uint32
	ThumbHighlightColor uint32
	Track               StyleFrame
	ActiveTrack         StyleFrame
}

func Slider_SliderMinimumLength(scale float32) int32 {
	var value_0 float32 = scale
	var value_1 float32 = 0.0
	var value_2 bool = value_0 <= value_1
	if value_2 {
		var value_3 float32 = 1.0
		scale = value_3
	}
	var value_4 float32 = 32.0
	var value_5 float32 = scale
	var value_6 float32 = value_4 * value_5
	var value_7 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_6), 32, true)), uint64(0), 32, true, 0))
	return value_7
}

func Slider_SliderThumbSize(scale float32) int32 {
	var value_0 float32 = scale
	var value_1 float32 = 0.0
	var value_2 bool = value_0 <= value_1
	if value_2 {
		var value_3 float32 = 1.0
		scale = value_3
	}
	var value_4 float32 = 22.0
	var value_5 float32 = scale
	var value_6 float32 = value_4 * value_5
	var value_7 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_6), 32, true)), uint64(0), 32, true, 0))
	return value_7
}

func Slider_SliderTrackSize(vertical bool, scale float32) int32 {
	var value_0 float32 = scale
	var value_1 float32 = 0.0
	var value_2 bool = value_0 <= value_1
	if value_2 {
		var value_3 float32 = 1.0
		scale = value_3
	}
	var value_4 bool = vertical
	if value_4 {
		var value_5 float32 = 8.0
		var value_6 float32 = scale
		var value_7 float32 = value_5 * value_6
		var value_8 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_7), 32, true)), uint64(0), 32, true, 0))
		return value_8
	}
	var value_9 float32 = 6.0
	var value_10 float32 = scale
	var value_11 float32 = value_9 * value_10
	var value_12 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_11), 32, true)), uint64(0), 32, true, 0))
	return value_12
}

func Slider_SliderPaintFor(spec SliderSpec) SliderPaint {
	var paint SliderPaint = SliderPaint{}
	var value_0 float32 = spec.Scale
	var scale float32 = value_0
	var value_1 float32 = scale
	var value_2 float32 = 0.0
	var value_3 bool = value_1 <= value_2
	if value_3 {
		var value_4 float32 = 1.0
		scale = value_4
	}
	var value_5 float32 = spec.Ratio
	var ratio float32 = value_5
	var value_6 float32 = ratio
	var value_7 float32 = 0.0
	var value_8 bool = value_6 < value_7
	if value_8 {
		var value_9 float32 = 0.0
		ratio = value_9
	}
	var value_10 float32 = ratio
	var value_11 float32 = 1.0
	var value_12 bool = value_10 > value_11
	if value_12 {
		var value_13 float32 = 1.0
		ratio = value_13
	}
	var value_14 Rectangle = spec.Bounds
	var bounds Rectangle = value_14
	var value_15 float32 = scale
	var value_16 int32 = Slider_SliderMinimumLength(value_15)
	var value_17 float32 = float32(value_16)
	var min_length float32 = value_17
	var value_18 float32 = scale
	var value_19 int32 = Slider_SliderThumbSize(value_18)
	var value_20 float32 = float32(value_19)
	var thumb_size float32 = value_20
	var value_21 bool = spec.Vertical
	var value_22 float32 = scale
	var value_23 int32 = Slider_SliderTrackSize(value_21, value_22)
	var value_24 float32 = float32(value_23)
	var track_size float32 = value_24
	var value_25 bool = spec.Vertical
	if value_25 {
		var value_26 float32 = bounds.Height
		var value_27 float32 = min_length
		var value_28 bool = value_26 < value_27
		if value_28 {
			var value_29 float32 = min_length
			bounds.Height = value_29
		}
		var value_30 float32 = bounds.Width
		var value_31 float32 = thumb_size
		var value_32 bool = value_30 < value_31
		if value_32 {
			var value_33 float32 = thumb_size
			bounds.Width = value_33
		}
		var value_34 float32 = bounds.X
		var value_35 float32 = bounds.Width
		var value_36 float32 = track_size
		var value_37 float32 = value_35 - value_36
		var value_38 float32 = 0.5
		var value_39 float32 = value_37 * value_38
		var value_40 float32 = value_34 + value_39
		paint.TrackBounds.X = value_40
		var value_41 float32 = bounds.Y
		paint.TrackBounds.Y = value_41
		var value_42 float32 = track_size
		paint.TrackBounds.Width = value_42
		var value_43 float32 = bounds.Height
		paint.TrackBounds.Height = value_43
		var value_44 float32 = paint.TrackBounds.Y
		var value_45 float32 = paint.TrackBounds.Height
		var value_46 float32 = 1.0
		var value_47 float32 = ratio
		var value_48 float32 = value_46 - value_47
		var value_49 float32 = value_45 * value_48
		var value_50 float32 = value_44 + value_49
		var position_y float32 = value_50
		var value_51 float32 = paint.TrackBounds.X
		paint.ActiveBounds.X = value_51
		var value_52 float32 = position_y
		paint.ActiveBounds.Y = value_52
		var value_53 float32 = paint.TrackBounds.Width
		paint.ActiveBounds.Width = value_53
		var value_54 float32 = paint.TrackBounds.Y
		var value_55 float32 = paint.TrackBounds.Height
		var value_56 float32 = value_54 + value_55
		var value_57 float32 = position_y
		var value_58 float32 = value_56 - value_57
		paint.ActiveBounds.Height = value_58
		var value_59 float32 = paint.TrackBounds.X
		var value_60 float32 = paint.TrackBounds.Width
		var value_61 float32 = 0.5
		var value_62 float32 = value_60 * value_61
		var value_63 float32 = value_59 + value_62
		paint.ThumbX = value_63
		var value_64 float32 = position_y
		paint.ThumbY = value_64
	} else {
		var value_65 float32 = bounds.Width
		var value_66 float32 = min_length
		var value_67 bool = value_65 < value_66
		if value_67 {
			var value_68 float32 = min_length
			bounds.Width = value_68
		}
		var value_69 float32 = bounds.Height
		var value_70 float32 = thumb_size
		var value_71 bool = value_69 < value_70
		if value_71 {
			var value_72 float32 = thumb_size
			bounds.Height = value_72
		}
		var value_73 float32 = bounds.X
		paint.TrackBounds.X = value_73
		var value_74 float32 = bounds.Y
		var value_75 float32 = bounds.Height
		var value_76 float32 = track_size
		var value_77 float32 = value_75 - value_76
		var value_78 float32 = 0.5
		var value_79 float32 = value_77 * value_78
		var value_80 float32 = value_74 + value_79
		paint.TrackBounds.Y = value_80
		var value_81 float32 = bounds.Width
		paint.TrackBounds.Width = value_81
		var value_82 float32 = track_size
		paint.TrackBounds.Height = value_82
		var value_83 float32 = paint.TrackBounds.X
		paint.ActiveBounds.X = value_83
		var value_84 float32 = paint.TrackBounds.Y
		paint.ActiveBounds.Y = value_84
		var value_85 float32 = paint.TrackBounds.Width
		var value_86 float32 = ratio
		var value_87 float32 = value_85 * value_86
		paint.ActiveBounds.Width = value_87
		var value_88 float32 = paint.TrackBounds.Height
		paint.ActiveBounds.Height = value_88
		var value_89 float32 = paint.TrackBounds.X
		var value_90 float32 = paint.TrackBounds.Width
		var value_91 float32 = ratio
		var value_92 float32 = value_90 * value_91
		var value_93 float32 = value_89 + value_92
		paint.ThumbX = value_93
		var value_94 float32 = paint.TrackBounds.Y
		var value_95 float32 = paint.TrackBounds.Height
		var value_96 float32 = 0.5
		var value_97 float32 = value_95 * value_96
		var value_98 float32 = value_94 + value_97
		paint.ThumbY = value_98
	}
	var value_99 Rectangle = bounds
	paint.Bounds = value_99
	var value_100 float32 = thumb_size
	var value_101 float32 = 0.5
	var value_102 float32 = value_100 * value_101
	paint.ThumbRadius = value_102
	var value_103 float32 = paint.ThumbRadius
	var value_104 float32 = 8.0
	var value_105 float32 = scale
	var value_106 float32 = value_104 * value_105
	var value_107 float32 = value_103 + value_106
	paint.GlowRadius = value_107
	var value_108 int32 = int32(ButtonStateNormal)
	var state int32 = value_108
	var value_109 bool = spec.Hovered
	if value_109 {
		var value_110 int32 = int32(ButtonStateHover)
		state = value_110
	}
	var value_111 bool = spec.Active
	if value_111 {
		var value_112 int32 = int32(ButtonStatePressed)
		state = value_112
	}
	var styles StyleStates = StyleStates{}
	var value_113 int32 = int32(ButtonToneNeutral)
	var value_114 int32 = int32(ButtonEmphasisSoft)
	var value_115 int32 = state
	var value_116 int32 = int32(ControlSizeMedium)
	var value_117 bool = true
	var value_118 bool = false
	var value_119 bool = spec.Disabled
	var value_120 bool = false
	var value_121 bool = false
	var value_122 Palette = spec.Palette
	var value_123 Metrics = spec.Metrics
	var value_124 StyleStates = styles
	var value_125 bool = false
	var value_126 float32 = 0.0
	var value_127 float32 = 0.0
	var value_128 float32 = 0.0
	var value_129 StyleFrame = Button_ResolveFrame(value_113, value_114, value_115, value_116, value_117, value_118, value_119, value_120, value_121, value_122, value_123, value_124, value_125, value_126, value_127, value_128)
	paint.Track = value_129
	var value_130 int32 = int32(ButtonToneAccent)
	var value_131 int32 = int32(ButtonEmphasisFilled)
	var value_132 int32 = state
	var value_133 int32 = int32(ControlSizeMedium)
	var value_134 bool = true
	var value_135 bool = false
	var value_136 bool = spec.Disabled
	var value_137 bool = false
	var value_138 bool = false
	var value_139 Palette = spec.Palette
	var value_140 Metrics = spec.Metrics
	var value_141 StyleStates = styles
	var value_142 bool = false
	var value_143 float32 = 0.0
	var value_144 float32 = 0.0
	var value_145 float32 = 0.0
	var value_146 StyleFrame = Button_ResolveFrame(value_130, value_131, value_132, value_133, value_134, value_135, value_136, value_137, value_138, value_139, value_140, value_141, value_142, value_143, value_144, value_145)
	paint.ActiveTrack = value_146
	var value_147 int32 = 16777215
	var value_148 uint32 = uint32(number_runtime_bits(uint64(value_147), uint64(0), 32, false, 0))
	var value_149 int32 = 255
	var value_150 uint32 = uint32(number_runtime_bits(uint64(value_149), uint64(0), 32, false, 0))
	var value_151 uint32 = Theme_PackedColor(value_148, value_150)
	var white uint32 = value_151
	var value_152 uint32 = paint.ActiveTrack.Value.Background
	paint.ThumbFillColor = value_152
	var value_153 uint32 = paint.ActiveTrack.Value.Background
	var value_154 uint32 = white
	var value_155 float32 = 0.50
	var value_156 uint32 = Surface_GradientColor(value_153, value_154, value_155)
	paint.ThumbEdgeColor = value_156
	var value_157 uint32 = spec.Palette.Shadow
	var value_158 bool = spec.Disabled
	var value_159 float32 = 0
	if value_158 {
		var value_160 float32 = 0.28
		value_159 = value_160
	} else {
		var value_161 float32 = 0.60
		value_159 = value_161
	}
	var value_162 uint32 = Surface_Opacity(value_157, value_159)
	paint.ThumbShadowColor = value_162
	var value_163 uint32 = white
	var value_164 bool = spec.Disabled
	var value_165 float32 = 0
	if value_164 {
		var value_166 float32 = 0.08
		value_165 = value_166
	} else {
		var value_167 float32 = 0.20
		value_165 = value_167
	}
	var value_168 uint32 = Surface_Opacity(value_163, value_165)
	paint.ThumbHighlightColor = value_168
	var value_169 uint32 = paint.ActiveTrack.Value.Background
	var value_170 bool = spec.Active
	var value_171 float32 = 0
	if value_170 {
		var value_172 float32 = 0.32
		value_171 = value_172
	} else {
		var value_173 bool = spec.Hovered
		var value_174 float32 = 0
		if value_173 {
			var value_175 float32 = 0.18
			value_174 = value_175
		} else {
			var value_176 float32 = 0.0
			value_174 = value_176
		}
		value_171 = value_174
	}
	var value_177 uint32 = Surface_Opacity(value_169, value_171)
	paint.GlowColor = value_177
	var value_178 bool = spec.Disabled
	if value_178 {
		var value_179 uint32 = paint.ThumbFillColor
		var value_180 float32 = 0.45
		var value_181 uint32 = Surface_Opacity(value_179, value_180)
		paint.ThumbFillColor = value_181
		var value_182 uint32 = paint.ThumbEdgeColor
		var value_183 float32 = 0.38
		var value_184 uint32 = Surface_Opacity(value_182, value_183)
		paint.ThumbEdgeColor = value_184
	}
	var value_185 SliderPaint = paint
	return value_185
}
