// Code generated by k2go from runtime/style_sheet.kry. DO NOT EDIT.
package kryon

// #import style
// #import control_props
type StyleFacts struct {
	Kind        int32
	Name        int32
	ClassName   int32
	Role        int32
	Tone        int32
	Emphasis    int32
	Size        int32
	State       int32
	Validation  int32
	Orientation int32
	Placement   int32
}

type StyleSelector struct {
	Kind        int32
	Name        int32
	ClassName   int32
	Role        int32
	Tone        int32
	Emphasis    int32
	Size        int32
	State       int32
	Validation  int32
	Orientation int32
	Placement   int32
}

type StyleRule struct {
	Selector StyleSelector
	State    int32
	Layer    int32
	Order    int32
	Style    StyleData
}

type StyleSheet struct {
	Rules     *StyleRule
	RuleCount int32
}

type StylePriority struct {
	Present     bool
	Layer       int32
	Specificity int32
	Order       int32
}

type StyleCascade struct {
	Result                StyleData
	BackgroundPriority    StylePriority
	ForegroundPriority    StylePriority
	BorderPriority        StylePriority
	FocusPriority         StylePriority
	RadiusPriority        StylePriority
	BorderWidthPriority   StylePriority
	OpacityPriority       StylePriority
	PaddingXPriority      StylePriority
	PaddingYPriority      StylePriority
	GapPriority           StylePriority
	FontSizePriority      StylePriority
	IconSizePriority      StylePriority
	ContentOffsetPriority StylePriority
	BackgroundEndPriority StylePriority
	MaterialPriority      StylePriority
	TypefacePriority      StylePriority
	LetterSpacingPriority StylePriority
}

type StyleFieldDecision struct {
	Matched            bool
	FieldPresent       bool
	Wins               bool
	Layer              int32
	Specificity        int32
	Order              int32
	CurrentPresent     bool
	CurrentLayer       int32
	CurrentSpecificity int32
	CurrentOrder       int32
}

func StyleSheet_StyleAny() int32 {
	return -1
}

func StyleSheet_StyleStateAny() int32 {
	return 0
}

func StyleSheet_StyleKindAny() int32 {
	return 0
}

func StyleSheet_StyleKindApp() int32 {
	return 1
}

func StyleSheet_StyleKindButton() int32 {
	return 2
}

func StyleSheet_StyleKindText() int32 {
	return 3
}

func StyleSheet_StyleKindTextField() int32 {
	return 4
}

func StyleSheet_StyleKindTextArea() int32 {
	return 5
}

func StyleSheet_StyleKindSurface() int32 {
	return 6
}

func StyleSheet_StyleKindDropdown() int32 {
	return 7
}

func StyleSheet_StyleKindCard() int32 {
	return 8
}

func StyleSheet_StyleKindSlider() int32 {
	return 9
}

func StyleSheet_StyleKindToggle() int32 {
	return 10
}

func StyleSheet_StyleKindCheckbox() int32 {
	return 11
}

func StyleSheet_StyleKindRadio() int32 {
	return 12
}

func StyleSheet_StyleKindProgress() int32 {
	return 13
}

func StyleSheet_StyleKindSeparator() int32 {
	return 14
}

func StyleSheet_StyleKindNavigationBar() int32 {
	return 15
}

func StyleSheet_StyleKindNavigationBarItem() int32 {
	return 16
}

func StyleSheet_StyleKindSelectable() int32 {
	return 17
}

func StyleSheet_StyleKindFieldset() int32 {
	return 18
}

func StyleSheet_StyleKindPlot() int32 {
	return 19
}

func StyleSheet_StyleKindPlotMark() int32 {
	return 20
}

func StyleSheet_StyleKindLink() int32 {
	return 21
}

func StyleSheet_StyleKindTabBar() int32 {
	return 22
}

func StyleSheet_StyleKindTab() int32 {
	return 23
}

func StyleSheet_StyleKindTabClose() int32 {
	return 24
}

func StyleSheet_StyleKindSegmentedControl() int32 {
	return 25
}

func StyleSheet_StyleKindSegment() int32 {
	return 26
}

func StyleSheet_StyleKindMenu() int32 {
	return 27
}

func StyleSheet_StyleKindMenuItem() int32 {
	return 28
}

func StyleSheet_StyleKindMenuSeparator() int32 {
	return 29
}

func StyleSheet_StyleKindListBox() int32 {
	return 30
}

func StyleSheet_StyleKindListBoxItem() int32 {
	return 31
}

func StyleSheet_StyleKindTreeView() int32 {
	return 32
}

func StyleSheet_StyleKindTreeViewItem() int32 {
	return 33
}

func StyleSheet_StyleKindListBoxMulti() int32 {
	return 34
}

func StyleSheet_StyleKindListBoxMultiItem() int32 {
	return 35
}

func StyleSheet_StyleKindDragDropTarget() int32 {
	return 36
}

func StyleSheet_StyleKindSpinbox() int32 {
	return 37
}

func StyleSheet_StyleKindSpinboxValue() int32 {
	return 38
}

func StyleSheet_StyleKindColorPickerSwatch() int32 {
	return 39
}

func StyleSheet_StyleKindColorPicker() int32 {
	return 62
}

func StyleSheet_StyleKindSliderThumb() int32 {
	return 40
}

func StyleSheet_StyleKindToggleThumb() int32 {
	return 41
}

func StyleSheet_StyleKindScroll() int32 {
	return 42
}

func StyleSheet_StyleKindScrollThumb() int32 {
	return 43
}

func StyleSheet_StyleKindPanedView() int32 {
	return 44
}

func StyleSheet_StyleKindToast() int32 {
	return 45
}

func StyleSheet_StyleKindCollapsible() int32 {
	return 46
}

func StyleSheet_StyleKindTitleBar() int32 {
	return 47
}

func StyleSheet_StyleKindToolbar() int32 {
	return 48
}

func StyleSheet_StyleKindModal() int32 {
	return 49
}

func StyleSheet_StyleKindTableView() int32 {
	return 50
}

func StyleSheet_StyleKindGuide() int32 {
	return 51
}

func StyleSheet_StyleKindImage() int32 {
	return 52
}

func StyleSheet_StyleKindFocus() int32 {
	return 53
}

func StyleSheet_StyleKindPopup() int32 {
	return 54
}

func StyleSheet_StyleKindCanvas() int32 {
	return 55
}

func StyleSheet_StyleKindDrag() int32 {
	return 56
}

func StyleSheet_StyleKindDragValue() int32 {
	return 57
}

func StyleSheet_StyleKindHeading() int32 {
	return 58
}

func StyleSheet_StyleKindParagraphText() int32 {
	return 59
}

func StyleSheet_StyleKindPage() int32 {
	return 60
}

func StyleSheet_StyleKindSection() int32 {
	return 61
}

func StyleSheet_StyleKindReorder() int32 {
	return 63
}

func StyleSheet_StyleDefaultFacts(kind int32) StyleFacts {
	var facts StyleFacts = StyleFacts{}
	facts.Kind = kind
	var value_0 int32 = StyleSheet_StyleAny()
	facts.Role = value_0
	var value_1 int32 = StyleSheet_StyleAny()
	facts.Tone = value_1
	var value_2 int32 = StyleSheet_StyleAny()
	facts.Emphasis = value_2
	var value_3 int32 = StyleSheet_StyleAny()
	facts.Size = value_3
	var value_4 int32 = StyleSheet_StyleAny()
	facts.State = value_4
	var value_5 int32 = StyleSheet_StyleAny()
	facts.Validation = value_5
	var value_6 int32 = StyleSheet_StyleAny()
	facts.Orientation = value_6
	var value_7 int32 = StyleSheet_StyleAny()
	facts.Placement = value_7
	return facts
}

func StyleSheet_StyleControlFacts(kind int32, name int32, class_name int32, tone int32, emphasis int32, size int32, state int32) StyleFacts {
	var value_0 StyleFacts = StyleSheet_StyleDefaultFacts(kind)
	var facts StyleFacts = value_0
	facts.Name = name
	facts.ClassName = class_name
	facts.Tone = tone
	facts.Emphasis = emphasis
	facts.Size = size
	facts.State = state
	return facts
}

func StyleSheet_StyleControlRoleFacts(kind int32, name int32, class_name int32, role int32, tone int32, emphasis int32, size int32, state int32) StyleFacts {
	var value_0 StyleFacts = StyleSheet_StyleControlFacts(kind, name, class_name, tone, emphasis, size, state)
	var facts StyleFacts = value_0
	facts.Role = role
	return facts
}

func StyleSheet_StyleTextFacts(name int32, class_name int32, role int32, state int32) StyleFacts {
	var value_0 int32 = StyleSheet_StyleKindText()
	var value_1 StyleFacts = StyleSheet_StyleDefaultFacts(value_0)
	var facts StyleFacts = value_1
	facts.Name = name
	facts.ClassName = class_name
	facts.Role = role
	facts.State = state
	return facts
}

func StyleSheet_StyleDefaultSelector() StyleSelector {
	var selector StyleSelector = StyleSelector{}
	var value_0 int32 = StyleSheet_StyleKindAny()
	selector.Kind = value_0
	var value_1 int32 = StyleSheet_StyleAny()
	selector.Role = value_1
	var value_2 int32 = StyleSheet_StyleAny()
	selector.Tone = value_2
	var value_3 int32 = StyleSheet_StyleAny()
	selector.Emphasis = value_3
	var value_4 int32 = StyleSheet_StyleAny()
	selector.Size = value_4
	var value_5 int32 = StyleSheet_StyleAny()
	selector.State = value_5
	var value_6 int32 = StyleSheet_StyleAny()
	selector.Validation = value_6
	var value_7 int32 = StyleSheet_StyleAny()
	selector.Orientation = value_7
	var value_8 int32 = StyleSheet_StyleAny()
	selector.Placement = value_8
	return selector
}

func StyleSheet_StyleMatchesOptional(selector_value int32, fact_value int32) bool {
	var value_0 int32 = StyleSheet_StyleAny()
	if selector_value == value_0 {
		return true
	}
	return (selector_value == fact_value)
}

func StyleSheet_StyleSelectorMatches(selector StyleSelector, facts StyleFacts) bool {
	var value_0 int32 = StyleSheet_StyleKindAny()
	var value_1 bool = (selector.Kind != value_0)
	if value_1 {
		value_1 = (selector.Kind != facts.Kind)
	}
	if value_1 {
		return false
	}
	var value_2 bool = (selector.Name != 0)
	if value_2 {
		value_2 = (selector.Name != facts.Name)
	}
	if value_2 {
		return false
	}
	var value_3 bool = (selector.ClassName != 0)
	if value_3 {
		value_3 = (selector.ClassName != facts.ClassName)
	}
	if value_3 {
		return false
	}
	var value_4 int32 = selector.Role
	var value_5 int32 = facts.Role
	var value_6 bool = StyleSheet_StyleMatchesOptional(value_4, value_5)
	if !value_6 {
		return false
	}
	var value_7 int32 = selector.Tone
	var value_8 int32 = facts.Tone
	var value_9 bool = StyleSheet_StyleMatchesOptional(value_7, value_8)
	if !value_9 {
		return false
	}
	var value_10 int32 = selector.Emphasis
	var value_11 int32 = facts.Emphasis
	var value_12 bool = StyleSheet_StyleMatchesOptional(value_10, value_11)
	if !value_12 {
		return false
	}
	var value_13 int32 = selector.Size
	var value_14 int32 = facts.Size
	var value_15 bool = StyleSheet_StyleMatchesOptional(value_13, value_14)
	if !value_15 {
		return false
	}
	var value_16 int32 = selector.State
	var value_17 int32 = facts.State
	var value_18 bool = StyleSheet_StyleMatchesOptional(value_16, value_17)
	if !value_18 {
		return false
	}
	var value_19 int32 = selector.Validation
	var value_20 int32 = facts.Validation
	var value_21 bool = StyleSheet_StyleMatchesOptional(value_19, value_20)
	if !value_21 {
		return false
	}
	var value_22 int32 = selector.Orientation
	var value_23 int32 = facts.Orientation
	var value_24 bool = StyleSheet_StyleMatchesOptional(value_22, value_23)
	if !value_24 {
		return false
	}
	var value_25 int32 = selector.Placement
	var value_26 int32 = facts.Placement
	var value_27 bool = StyleSheet_StyleMatchesOptional(value_25, value_26)
	if !value_27 {
		return false
	}
	return true
}

func StyleSheet_StyleSpecificity(kinds int32, attributes int32, classes int32, names int32) int32 {
	var value_0 int32 = int32(number_runtime_bits(uint64(kinds), uint64((int32(number_runtime_bits(uint64(attributes), uint64(10), 32, true, 3)))), 32, true, 1))
	var value_1 int32 = int32(number_runtime_bits(uint64(value_0), uint64((int32(number_runtime_bits(uint64(classes), uint64(20), 32, true, 3)))), 32, true, 1))
	var value_2 int32 = int32(number_runtime_bits(uint64(value_1), uint64((int32(number_runtime_bits(uint64(names), uint64(100), 32, true, 3)))), 32, true, 1))
	return value_2
}

func StyleSheet_StyleSelectorSpecificity(selector StyleSelector) int32 {
	var kinds int32 = 0
	var attributes int32 = 0
	var classes int32 = 0
	var names int32 = 0
	var value_0 int32 = StyleSheet_StyleKindAny()
	if selector.Kind != value_0 {
		kinds = 1
	}
	var value_1 int32 = StyleSheet_StyleAny()
	if selector.Role != value_1 {
		var value_2 int32 = attributes
		attributes = int32(number_runtime_bits(uint64(value_2), uint64(1), 32, true, 1))
	}
	var value_3 int32 = StyleSheet_StyleAny()
	if selector.Tone != value_3 {
		var value_4 int32 = attributes
		attributes = int32(number_runtime_bits(uint64(value_4), uint64(1), 32, true, 1))
	}
	var value_5 int32 = StyleSheet_StyleAny()
	if selector.Emphasis != value_5 {
		var value_6 int32 = attributes
		attributes = int32(number_runtime_bits(uint64(value_6), uint64(1), 32, true, 1))
	}
	var value_7 int32 = StyleSheet_StyleAny()
	if selector.Size != value_7 {
		var value_8 int32 = attributes
		attributes = int32(number_runtime_bits(uint64(value_8), uint64(1), 32, true, 1))
	}
	var value_9 int32 = StyleSheet_StyleAny()
	if selector.State != value_9 {
		var value_10 int32 = attributes
		attributes = int32(number_runtime_bits(uint64(value_10), uint64(1), 32, true, 1))
	}
	var value_11 int32 = StyleSheet_StyleAny()
	if selector.Validation != value_11 {
		var value_12 int32 = attributes
		attributes = int32(number_runtime_bits(uint64(value_12), uint64(1), 32, true, 1))
	}
	var value_13 int32 = StyleSheet_StyleAny()
	if selector.Orientation != value_13 {
		var value_14 int32 = attributes
		attributes = int32(number_runtime_bits(uint64(value_14), uint64(1), 32, true, 1))
	}
	var value_15 int32 = StyleSheet_StyleAny()
	if selector.Placement != value_15 {
		var value_16 int32 = attributes
		attributes = int32(number_runtime_bits(uint64(value_16), uint64(1), 32, true, 1))
	}
	if selector.ClassName != 0 {
		classes = 1
	}
	if selector.Name != 0 {
		names = 1
	}
	var value_17 int32 = StyleSheet_StyleSpecificity(kinds, attributes, classes, names)
	return value_17
}

func StyleSheet_StylePriorityScore(layer int32, specificity int32, order int32) int32 {
	var value_0 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(layer), uint64(1000000), 32, true, 3)))), uint64((int32(number_runtime_bits(uint64(specificity), uint64(1000), 32, true, 3)))), 32, true, 1))
	return (int32(number_runtime_bits(uint64(value_0), uint64(order), 32, true, 1)))
}

func StyleSheet_StyleRulePriority(rule StyleRule) StylePriority {
	var priority StylePriority = StylePriority{}
	priority.Present = true
	priority.Layer = rule.Layer
	var value_0 StyleSelector = rule.Selector
	var value_1 int32 = StyleSheet_StyleSelectorSpecificity(value_0)
	priority.Specificity = value_1
	priority.Order = rule.Order
	return priority
}

func StyleSheet_StyleRuleMatchesState(rule_state int32, active_state int32) bool {
	var value_0 int32 = StyleSheet_StyleStateAny()
	if rule_state == value_0 {
		return true
	}
	if rule_state == int32(ButtonStateNormal) {
		return true
	}
	return (rule_state == active_state)
}

func StyleSheet_StyleRuleMatches(rule StyleRule, facts StyleFacts, active_state int32) bool {
	var value_0 int32 = rule.State
	var value_1 bool = StyleSheet_StyleRuleMatchesState(value_0, active_state)
	if !value_1 {
		return false
	}
	var value_2 StyleSelector = rule.Selector
	var value_3 bool = StyleSheet_StyleSelectorMatches(value_2, facts)
	return value_3
}

func StyleSheet_StyleHasField(style StyleData, field uint32) bool {
	var value_0 bool = (uint32(number_runtime_bits(uint64(style.Fields), uint64(field), 32, false, 8))) != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0))
	return value_0
}

func StyleSheet_StyleCascadeFieldPriority(cascade StyleCascade, field uint32) StylePriority {
	if field == uint32(number_runtime_bits(uint64(int32(StyleBackground)), uint64(0), 32, false, 0)) {
		return cascade.BackgroundPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleForeground)), uint64(0), 32, false, 0)) {
		return cascade.ForegroundPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleBorder)), uint64(0), 32, false, 0)) {
		return cascade.BorderPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleFocus)), uint64(0), 32, false, 0)) {
		return cascade.FocusPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleRadius)), uint64(0), 32, false, 0)) {
		return cascade.RadiusPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleBorderWidth)), uint64(0), 32, false, 0)) {
		return cascade.BorderWidthPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleOpacity)), uint64(0), 32, false, 0)) {
		return cascade.OpacityPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0)) {
		return cascade.PaddingXPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0)) {
		return cascade.PaddingYPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0)) {
		return cascade.GapPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleFontSize)), uint64(0), 32, false, 0)) {
		return cascade.FontSizePriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleLetterSpacing)), uint64(0), 32, false, 0)) {
		return cascade.LetterSpacingPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0)) {
		return cascade.IconSizePriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0)) {
		return cascade.ContentOffsetPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleBackgroundEnd)), uint64(0), 32, false, 0)) {
		return cascade.BackgroundEndPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleMaterial)), uint64(0), 32, false, 0)) {
		return cascade.MaterialPriority
	}
	if field == uint32(number_runtime_bits(uint64(int32(StyleTypeface)), uint64(0), 32, false, 0)) {
		return cascade.TypefacePriority
	}
	var priority StylePriority = StylePriority{}
	return priority
}

func StyleSheet_StyleRuleFieldDecision(current StylePriority, rule StyleRule, facts StyleFacts, active_state int32, field uint32) StyleFieldDecision {
	var decision StyleFieldDecision = StyleFieldDecision{}
	decision.CurrentPresent = current.Present
	decision.CurrentLayer = current.Layer
	decision.CurrentSpecificity = current.Specificity
	decision.CurrentOrder = current.Order
	var value_0 bool = StyleSheet_StyleRuleMatches(rule, facts, active_state)
	if !value_0 {
		return decision
	}
	decision.Matched = true
	var value_1 StyleData = rule.Style
	var value_2 bool = StyleSheet_StyleHasField(value_1, field)
	if !value_2 {
		return decision
	}
	decision.FieldPresent = true
	var value_3 StylePriority = StyleSheet_StyleRulePriority(rule)
	var priority StylePriority = value_3
	decision.Layer = priority.Layer
	decision.Specificity = priority.Specificity
	decision.Order = priority.Order
	var value_4 bool = StyleSheet_StylePriorityWins(priority, current)
	decision.Wins = value_4
	return decision
}

func StyleSheet_StylePriorityWins(priority StylePriority, current StylePriority) bool {
	if !priority.Present {
		return false
	}
	if !current.Present {
		return true
	}
	if priority.Layer != current.Layer {
		return (priority.Layer > current.Layer)
	}
	if priority.Specificity != current.Specificity {
		return (priority.Specificity > current.Specificity)
	}
	return (priority.Order >= current.Order)
}

func StyleSheet_BeginStyleCascade(base StyleData) StyleCascade {
	var cascade StyleCascade = StyleCascade{}
	cascade.Result = base
	return cascade
}

func StyleSheet_ApplyStyleRule(cascade StyleCascade, rule StyleRule, facts StyleFacts, active_state int32) StyleCascade {
	var value_0 bool = StyleSheet_StyleRuleMatches(rule, facts, active_state)
	if !value_0 {
		return cascade
	}
	var value_1 StylePriority = StyleSheet_StyleRulePriority(rule)
	var priority StylePriority = value_1
	var style StyleData = rule.Style
	var value_2 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleBackground)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_3 bool = (value_2 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_3 {
		var value_4 StylePriority = cascade.BackgroundPriority
		var value_5 bool = StyleSheet_StylePriorityWins(priority, value_4)
		value_3 = value_5
	}
	if value_3 {
		cascade.Result.Background = style.Background
		var value_6 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleBackground)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_6
		cascade.BackgroundPriority = priority
	}
	var value_7 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleForeground)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_8 bool = (value_7 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_8 {
		var value_9 StylePriority = cascade.ForegroundPriority
		var value_10 bool = StyleSheet_StylePriorityWins(priority, value_9)
		value_8 = value_10
	}
	if value_8 {
		cascade.Result.Foreground = style.Foreground
		var value_11 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleForeground)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_11
		cascade.ForegroundPriority = priority
	}
	var value_12 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleBorder)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_13 bool = (value_12 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_13 {
		var value_14 StylePriority = cascade.BorderPriority
		var value_15 bool = StyleSheet_StylePriorityWins(priority, value_14)
		value_13 = value_15
	}
	if value_13 {
		cascade.Result.Border = style.Border
		var value_16 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleBorder)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_16
		cascade.BorderPriority = priority
	}
	var value_17 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleFocus)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_18 bool = (value_17 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_18 {
		var value_19 StylePriority = cascade.FocusPriority
		var value_20 bool = StyleSheet_StylePriorityWins(priority, value_19)
		value_18 = value_20
	}
	if value_18 {
		cascade.Result.Focus = style.Focus
		var value_21 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleFocus)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_21
		cascade.FocusPriority = priority
	}
	var value_22 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleRadius)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_23 bool = (value_22 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_23 {
		var value_24 StylePriority = cascade.RadiusPriority
		var value_25 bool = StyleSheet_StylePriorityWins(priority, value_24)
		value_23 = value_25
	}
	if value_23 {
		cascade.Result.Radius = style.Radius
		var value_26 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleRadius)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_26
		cascade.RadiusPriority = priority
	}
	var value_27 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleBorderWidth)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_28 bool = (value_27 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_28 {
		var value_29 StylePriority = cascade.BorderWidthPriority
		var value_30 bool = StyleSheet_StylePriorityWins(priority, value_29)
		value_28 = value_30
	}
	if value_28 {
		cascade.Result.BorderWidth = style.BorderWidth
		var value_31 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleBorderWidth)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_31
		cascade.BorderWidthPriority = priority
	}
	var value_32 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleOpacity)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_33 bool = (value_32 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_33 {
		var value_34 StylePriority = cascade.OpacityPriority
		var value_35 bool = StyleSheet_StylePriorityWins(priority, value_34)
		value_33 = value_35
	}
	if value_33 {
		cascade.Result.Opacity = style.Opacity
		var value_36 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleOpacity)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_36
		cascade.OpacityPriority = priority
	}
	var value_37 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_38 bool = (value_37 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_38 {
		var value_39 StylePriority = cascade.PaddingXPriority
		var value_40 bool = StyleSheet_StylePriorityWins(priority, value_39)
		value_38 = value_40
	}
	if value_38 {
		cascade.Result.PaddingX = style.PaddingX
		var value_41 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_41
		cascade.PaddingXPriority = priority
	}
	var value_42 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_43 bool = (value_42 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_43 {
		var value_44 StylePriority = cascade.PaddingYPriority
		var value_45 bool = StyleSheet_StylePriorityWins(priority, value_44)
		value_43 = value_45
	}
	if value_43 {
		cascade.Result.PaddingY = style.PaddingY
		var value_46 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_46
		cascade.PaddingYPriority = priority
	}
	var value_47 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_48 bool = (value_47 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_48 {
		var value_49 StylePriority = cascade.GapPriority
		var value_50 bool = StyleSheet_StylePriorityWins(priority, value_49)
		value_48 = value_50
	}
	if value_48 {
		cascade.Result.Gap = style.Gap
		var value_51 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_51
		cascade.GapPriority = priority
	}
	var value_52 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleFontSize)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_53 bool = (value_52 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_53 {
		var value_54 StylePriority = cascade.FontSizePriority
		var value_55 bool = StyleSheet_StylePriorityWins(priority, value_54)
		value_53 = value_55
	}
	if value_53 {
		cascade.Result.FontSize = style.FontSize
		var value_56 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleFontSize)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_56
		cascade.FontSizePriority = priority
	}
	var value_57 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleLetterSpacing)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_58 bool = (value_57 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_58 {
		var value_59 StylePriority = cascade.LetterSpacingPriority
		var value_60 bool = StyleSheet_StylePriorityWins(priority, value_59)
		value_58 = value_60
	}
	if value_58 {
		cascade.Result.LetterSpacing = style.LetterSpacing
		var value_61 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleLetterSpacing)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_61
		cascade.LetterSpacingPriority = priority
	}
	var value_62 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_63 bool = (value_62 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_63 {
		var value_64 StylePriority = cascade.IconSizePriority
		var value_65 bool = StyleSheet_StylePriorityWins(priority, value_64)
		value_63 = value_65
	}
	if value_63 {
		cascade.Result.IconSize = style.IconSize
		var value_66 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_66
		cascade.IconSizePriority = priority
	}
	var value_67 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_68 bool = (value_67 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_68 {
		var value_69 StylePriority = cascade.ContentOffsetPriority
		var value_70 bool = StyleSheet_StylePriorityWins(priority, value_69)
		value_68 = value_70
	}
	if value_68 {
		cascade.Result.OffsetX = style.OffsetX
		cascade.Result.OffsetY = style.OffsetY
		var value_71 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_71
		cascade.ContentOffsetPriority = priority
	}
	var value_72 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleBackgroundEnd)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_73 bool = (value_72 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_73 {
		var value_74 StylePriority = cascade.BackgroundEndPriority
		var value_75 bool = StyleSheet_StylePriorityWins(priority, value_74)
		value_73 = value_75
	}
	if value_73 {
		cascade.Result.BackgroundEnd = style.BackgroundEnd
		var value_76 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleBackgroundEnd)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_76
		cascade.BackgroundEndPriority = priority
	}
	var value_77 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleMaterial)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_78 bool = (value_77 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_78 {
		var value_79 StylePriority = cascade.MaterialPriority
		var value_80 bool = StyleSheet_StylePriorityWins(priority, value_79)
		value_78 = value_80
	}
	if value_78 {
		cascade.Result.Material = MaterialKind(style.Material)
		var value_81 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleMaterial)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_81
		cascade.MaterialPriority = priority
	}
	var value_82 uint32 = uint32(number_runtime_bits(uint64(style.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleTypeface)), uint64(0), 32, false, 0))), 32, false, 8))
	var value_83 bool = (value_82 != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0)))
	if value_83 {
		var value_84 StylePriority = cascade.TypefacePriority
		var value_85 bool = StyleSheet_StylePriorityWins(priority, value_84)
		value_83 = value_85
	}
	if value_83 {
		cascade.Result.Typeface = style.Typeface
		var value_86 uint32 = uint32(number_runtime_bits(uint64(cascade.Result.Fields), uint64(uint32(number_runtime_bits(uint64(int32(StyleTypeface)), uint64(0), 32, false, 0))), 32, false, 9))
		cascade.Result.Fields = value_86
		cascade.TypefacePriority = priority
	}
	return cascade
}

func StyleSheet_FinishStyleCascade(cascade StyleCascade) StyleData {
	return cascade.Result
}

func StyleSheet_ResolveStyleRule(base StyleData, facts StyleFacts, rule StyleRule, active_state int32) StyleData {
	var value_0 StyleCascade = StyleSheet_BeginStyleCascade(base)
	var cascade StyleCascade = value_0
	var value_1 StyleCascade = StyleSheet_ApplyStyleRule(cascade, rule, facts, active_state)
	cascade = value_1
	var value_2 StyleData = StyleSheet_FinishStyleCascade(cascade)
	return value_2
}
