// Code generated by k2go from runtime/style_picker_props.kry. DO NOT EDIT.
package kryon

// #import kryon_compat.generated.h
type StylePackOption struct {
	ID          string
	Label       string
	Description string
	Active      bool
}

type StylePickerProps struct {
	Bounds    Rectangle
	ID        int32
	ClassName int32
	Disabled  bool
}
