// Code generated by k2go from runtime/text.kry. DO NOT EDIT.
package kryon

// #import style
type TextAppearance struct {
	Font          int32
	Color         uint32
	LetterSpacing int32
}

func Text_ResolveTextStyle(font int32, inherited_font int32, default_font int32, color uint32, inherited_color uint32, theme_color uint32, inherited_color_set bool, color_set bool, disabled bool, inherited_disabled bool, letter_spacing int32) TextAppearance {
	var style TextAppearance = TextAppearance{}
	var value_0 int32 = font
	var value_1 int32 = inherited_font
	var value_2 int32 = default_font
	var value_3 int32 = Style_ResolveFont(value_0, value_1, value_2)
	style.Font = value_3
	var value_4 uint32 = color
	style.Color = value_4
	var value_5 bool = color_set
	var value_6 bool = !value_5
	if value_6 {
		var value_7 uint32 = theme_color
		style.Color = value_7
		var value_8 bool = inherited_color_set
		if value_8 {
			var value_9 uint32 = inherited_color
			style.Color = value_9
		}
	}
	var value_10 bool = disabled
	var value_11 bool = value_10
	if !value_11 {
		var value_12 bool = inherited_disabled
		value_11 = value_12
	}
	var value_13 bool = value_11
	if value_13 {
		var value_14 bool = color_set
		var value_15 bool = value_14
		if !value_15 {
			var value_16 bool = inherited_color_set
			var value_17 bool = !value_16
			value_15 = value_17
		}
		var value_18 bool = value_15
		if !value_18 {
			var value_19 bool = inherited_disabled
			var value_20 bool = !value_19
			value_18 = value_20
		}
		value_13 = value_18
	}
	if value_13 {
		var value_21 uint32 = style.Color
		var value_22 int32 = 255
		var value_23 uint32 = uint32(number_runtime_bits(uint64(value_22), uint64(0), 32, false, 0))
		var value_24 uint32 = uint32(number_runtime_bits(uint64(value_21), uint64(value_23), 32, false, 8))
		var value_25 float32 = float32(value_24)
		var value_26 float32 = 0.45
		var value_27 float32 = value_25 * value_26
		var value_28 uint32 = uint32(number_runtime_bits(uint64(number_runtime_float(float64(value_27), 32, false)), uint64(0), 32, false, 0))
		var alpha uint32 = value_28
		var value_29 uint32 = style.Color
		var value_30 int32 = 8
		var value_31 uint32 = uint32(number_runtime_bits(uint64(value_30), uint64(0), 32, false, 0))
		var value_32 uint32 = uint32(number_runtime_bits(uint64(value_29), uint64(value_31), 32, false, 7))
		var value_33 int32 = 8
		var value_34 uint32 = uint32(number_runtime_bits(uint64(value_33), uint64(0), 32, false, 0))
		var value_35 uint32 = uint32(number_runtime_bits(uint64(value_32), uint64(value_34), 32, false, 6))
		var value_36 uint32 = alpha
		var value_37 uint32 = uint32(number_runtime_bits(uint64(value_35), uint64(value_36), 32, false, 9))
		style.Color = value_37
	}
	var value_38 int32 = letter_spacing
	style.LetterSpacing = value_38
	var value_39 int32 = style.LetterSpacing
	var value_40 int32 = 0
	var value_41 bool = value_39 < value_40
	if value_41 {
		var value_42 int32 = 0
		style.LetterSpacing = value_42
	}
	var value_43 TextAppearance = style
	return value_43
}

func Text_TextExtent(requested float32, measured float32) float32 {
	var value_0 float32 = requested
	var value_1 float32 = 0.0
	var value_2 bool = value_0 > value_1
	if value_2 {
		var value_3 float32 = requested
		return value_3
	}
	var value_4 float32 = measured
	return value_4
}

func Text_TextWrapPolicy(width float32, requested int32) int32 {
	var value_0 float32 = width
	var value_1 float32 = 0.0
	var value_2 bool = value_0 <= value_1
	if value_2 {
		var value_3 int32 = 1
		return value_3
	}
	var value_4 int32 = requested
	return value_4
}

func Text_TextAlignmentOffset(available float32, measured float32, alignment int32) float32 {
	var value_0 int32 = alignment
	var value_1 int32 = 1
	var value_2 bool = value_0 == value_1
	if value_2 {
		var value_3 float32 = available
		var value_4 float32 = measured
		var value_5 float32 = value_3 - value_4
		var value_6 float32 = 0.5
		var value_7 float32 = value_5 * value_6
		return value_7
	}
	var value_8 int32 = alignment
	var value_9 int32 = 2
	var value_10 bool = value_8 == value_9
	if value_10 {
		var value_11 float32 = available
		var value_12 float32 = measured
		var value_13 float32 = value_11 - value_12
		return value_13
	}
	var value_14 float32 = 0.0
	return value_14
}
