// Code generated by k2go from runtime/text_input_props.kry. DO NOT EDIT.
package kryon

// #import kryon_compat.generated.h
type SyntaxMode int32

const (
	SyntaxNone SyntaxMode = 0
	SyntaxKry  SyntaxMode = 1
	SyntaxC    SyntaxMode = 2
	SyntaxMake SyntaxMode = 3
)

type TextInputProps struct {
	Bounds         Rectangle
	Text           string
	CursorPosition int32
	Focused        bool
	CursorVisible  bool
	FocusID        int32
	ClassName      int32
}

type TextFieldProps struct {
	Bounds         Rectangle
	Text           []byte
	CursorPosition *int32
	Focused        *bool
	MaxCodepoints  int32
	FocusID        int32
	CommitPressed  *bool
	Secure         bool
	ReadOnly       bool
	ClassName      int32
}

type TextAreaProps struct {
	Bounds         Rectangle
	Text           []byte
	CursorPosition *int32
	Focused        *bool
	ScrollY        *int32
	MaxCodepoints  int32
	FocusID        int32
	Placeholder    string
	Syntax         SyntaxMode
	ContentVersion int32
	ReadOnly       bool
	Wrap           bool
	ClassName      int32
}
