// Code generated by k2go from runtime/text_input_props.kry. DO NOT EDIT.
package kryon

// #import kryon_compat.generated.h
type SyntaxMode int32

const (
	SyntaxNone SyntaxMode = 0
	SyntaxKry  SyntaxMode = 1
	SyntaxC    SyntaxMode = 2
	SyntaxMake SyntaxMode = 3
)

type TextInputStyle struct {
	Background  Color
	Border      Color
	FocusBorder Color
	Text        Color
	Cursor      Color
	Radius      float32
	PaddingX    int32
	PaddingY    int32
}

type TextInputProps struct {
	Bounds         Rectangle
	Text           string
	CursorPosition int32
	Focused        bool
	CursorVisible  bool
	Font           int32
	FocusID        int32
	Style          TextInputStyle
}

type TextFieldProps struct {
	Bounds         Rectangle
	Text           []byte
	CursorPosition *int32
	Focused        *bool
	MaxCodepoints  int32
	Font           int32
	FocusID        int32
	Style          TextInputStyle
	CommitPressed  *bool
	Secure         bool
	ReadOnly       bool
}

type TextAreaProps struct {
	Bounds         Rectangle
	Text           []byte
	CursorPosition *int32
	Focused        *bool
	ScrollY        *int32
	MaxCodepoints  int32
	Font           int32
	LineGap        int32
	FocusID        int32
	Placeholder    string
	Syntax         SyntaxMode
	Style          TextInputStyle
	ContentVersion int32
	ReadOnly       bool
	Wrap           bool
}
