// Code generated by k2go from runtime/title_bar.kry. DO NOT EDIT.
package kryon

// #import control_props
// #import drawing_props
// #import style
type TitleBarMetrics struct {
	SideMargin             int32
	LeadingReserved        int32
	LeadingIconSize        int32
	LeadingPadding         int32
	LeadingX               int32
	DropdownGap            int32
	DropdownDefaultHeight  int32
	TitleMinWidth          int32
	TitleHorizontalPadding int32
}

type TitleBarLayout struct {
	Bounds         Rectangle
	LeadingBounds  Rectangle
	TitleBounds    Rectangle
	DropdownBounds Rectangle
	SideReserved   int32
}

type TitleBarPaint struct {
	Bounds  Rectangle
	Divider Rectangle
}

type TitleBarTitlePaint struct {
	X int32
	Y int32
}

type TitleBarState struct {
	Height      int32
	HasLeading  bool
	HasDropdown bool
}

func TitleBar_TitleBarMetric(fields uint32, field uint32, value float32, fallback float32, scale float32) int32 {
	var value_0 bool = (uint32(number_runtime_bits(uint64(fields), uint64(field), 32, false, 8))) == uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0))
	var value_1 bool = value_0
	if !value_1 {
		value_1 = (value < 0.0)
	}
	if value_1 {
		value = fallback
	}
	var value_2 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((value*scale)), 32, true)), uint64(0), 32, true, 0))
	return value_2
}

func TitleBar_TitleBarBarRole() int32 {
	return 1
}

func TitleBar_TitleBarTitleRole() int32 {
	return 16
}

func TitleBar_TitleBarActionRole() int32 {
	return 17
}

func TitleBar_TitleBarActionRadius() float32 {
	return 0.50
}

func TitleBar_TitleBarMetricsFor(scale float32, bar StyleFrame, title StyleFrame, action StyleFrame) TitleBarMetrics {
	if scale <= 0.0 {
		scale = 1.0
	}
	var metrics TitleBarMetrics = TitleBarMetrics{}
	var value_0 uint32 = bar.Value.Fields
	var value_1 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))
	var value_2 float32 = bar.Value.PaddingX
	var value_3 float32 = 12.0
	var value_4 int32 = TitleBar_TitleBarMetric(value_0, value_1, value_2, value_3, scale)
	metrics.SideMargin = value_4
	var value_5 uint32 = bar.Value.Fields
	var value_6 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_7 float32 = bar.Value.OffsetX
	var value_8 float32 = 60.0
	var value_9 int32 = TitleBar_TitleBarMetric(value_5, value_6, value_7, value_8, scale)
	metrics.LeadingReserved = value_9
	var value_10 uint32 = action.Value.Fields
	var value_11 uint32 = uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))
	var value_12 float32 = action.Value.IconSize
	var value_13 float32 = 20.0
	var value_14 int32 = TitleBar_TitleBarMetric(value_10, value_11, value_12, value_13, scale)
	metrics.LeadingIconSize = value_14
	var value_15 uint32 = action.Value.Fields
	var value_16 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))
	var value_17 float32 = action.Value.PaddingX
	var value_18 float32 = 10.0
	var value_19 int32 = TitleBar_TitleBarMetric(value_15, value_16, value_17, value_18, scale)
	metrics.LeadingPadding = value_19
	metrics.LeadingX = metrics.SideMargin
	var value_20 uint32 = bar.Value.Fields
	var value_21 uint32 = uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))
	var value_22 float32 = bar.Value.Gap
	var value_23 float32 = 4.0
	var value_24 int32 = TitleBar_TitleBarMetric(value_20, value_21, value_22, value_23, scale)
	metrics.DropdownGap = value_24
	var value_25 uint32 = bar.Value.Fields
	var value_26 uint32 = uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))
	var value_27 float32 = bar.Value.IconSize
	var value_28 float32 = 32.0
	var value_29 int32 = TitleBar_TitleBarMetric(value_25, value_26, value_27, value_28, scale)
	metrics.DropdownDefaultHeight = value_29
	var value_30 uint32 = title.Value.Fields
	var value_31 uint32 = uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))
	var value_32 float32 = title.Value.IconSize
	var value_33 float32 = 48.0
	var value_34 int32 = TitleBar_TitleBarMetric(value_30, value_31, value_32, value_33, scale)
	metrics.TitleMinWidth = value_34
	var value_35 uint32 = title.Value.Fields
	var value_36 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))
	var value_37 float32 = title.Value.PaddingX
	var value_38 float32 = 16.0
	var value_39 int32 = TitleBar_TitleBarMetric(value_35, value_36, value_37, value_38, scale)
	metrics.TitleHorizontalPadding = value_39
	return metrics
}

func TitleBar_TitleBarDefaultHeightFor(scale float32, bar StyleFrame) int32 {
	if scale <= 0.0 {
		scale = 1.0
	}
	var value_0 uint32 = bar.Value.Fields
	var value_1 uint32 = uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))
	var value_2 float32 = bar.Value.IconSize
	var value_3 float32 = 32.0
	var value_4 int32 = TitleBar_TitleBarMetric(value_0, value_1, value_2, value_3, scale)
	return value_4
}

func TitleBar_TitleBarStateFor(requested_height int32, fallback_height int32, has_leading bool, has_dropdown bool) TitleBarState {
	var state TitleBarState = TitleBarState{}
	state.Height = requested_height
	if state.Height <= 0 {
		state.Height = fallback_height
	}
	if state.Height < 0 {
		state.Height = 0
	}
	state.HasLeading = has_leading
	state.HasDropdown = has_dropdown
	return state
}

func TitleBar_TitleBarLayoutFor(view_width int32, height int32, has_leading bool, has_dropdown bool, dropdown_height int32, dropdown_min_width int32, metrics TitleBarMetrics) TitleBarLayout {
	var layout TitleBarLayout = TitleBarLayout{}
	layout.Bounds.Width = float32(view_width)
	layout.Bounds.Height = float32(height)
	layout.SideReserved = metrics.SideMargin
	if has_leading {
		var value_0 int32 = int32(number_runtime_bits(uint64(metrics.LeadingIconSize), uint64((int32(number_runtime_bits(uint64(metrics.LeadingPadding), uint64(2), 32, true, 3)))), 32, true, 1))
		var button_size int32 = value_0
		var value_1 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(height), uint64(button_size), 32, true, 2)))), uint64(2), 32, true, 4))
		var y int32 = value_1
		if y < 0 {
			y = 0
		}
		layout.LeadingBounds.X = float32(metrics.LeadingX)
		layout.LeadingBounds.Y = float32(y)
		layout.LeadingBounds.Width = float32(button_size)
		layout.LeadingBounds.Height = float32(button_size)
		layout.SideReserved = metrics.LeadingReserved
	}
	var value_2 int32 = int32(number_runtime_bits(uint64(view_width), uint64((int32(number_runtime_bits(uint64(layout.SideReserved), uint64(2), 32, true, 3)))), 32, true, 2))
	var max_width int32 = value_2
	if max_width < metrics.TitleMinWidth {
		max_width = (int32(number_runtime_bits(uint64(view_width), uint64(metrics.TitleHorizontalPadding), 32, true, 2)))
	}
	if max_width < 1 {
		max_width = 1
	}
	var value_3 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(view_width), uint64(max_width), 32, true, 2)))), uint64(2), 32, true, 4))
	layout.TitleBounds.X = float32(value_3)
	layout.TitleBounds.Y = 0.0
	layout.TitleBounds.Width = float32(max_width)
	layout.TitleBounds.Height = float32(height)
	if has_dropdown {
		var dropdown_x int32 = metrics.SideMargin
		if has_leading {
			var value_4 int32 = dropdown_x
			var value_5 int32 = int32(number_runtime_bits(uint64(metrics.LeadingIconSize), uint64((int32(number_runtime_bits(uint64(metrics.LeadingPadding), uint64(2), 32, true, 3)))), 32, true, 1))
			dropdown_x = int32(number_runtime_bits(uint64(value_4), uint64((int32(number_runtime_bits(uint64(value_5), uint64(metrics.DropdownGap), 32, true, 1)))), 32, true, 1))
		}
		var dropdown_h int32 = dropdown_height
		if dropdown_h <= 0 {
			dropdown_h = metrics.DropdownDefaultHeight
		}
		var value_6 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(height), uint64(dropdown_h), 32, true, 2)))), uint64(2), 32, true, 4))
		var dropdown_y int32 = value_6
		if dropdown_y < 0 {
			dropdown_y = 0
		}
		var value_7 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(view_width), uint64(dropdown_x), 32, true, 2)))), uint64(metrics.SideMargin), 32, true, 2))
		var dropdown_w int32 = value_7
		var value_8 bool = (dropdown_min_width > 0)
		if value_8 {
			value_8 = (dropdown_w < dropdown_min_width)
		}
		if value_8 {
			dropdown_w = (int32(number_runtime_bits(uint64(view_width), uint64(dropdown_x), 32, true, 2)))
		}
		if dropdown_w < 1 {
			dropdown_w = 1
		}
		layout.DropdownBounds.X = float32(dropdown_x)
		layout.DropdownBounds.Y = float32(dropdown_y)
		layout.DropdownBounds.Width = float32(dropdown_w)
		layout.DropdownBounds.Height = float32(dropdown_h)
	}
	return layout
}

func TitleBar_TitleBarReservedHasLeading(side_reserved int32, metrics TitleBarMetrics) bool {
	return (side_reserved > metrics.SideMargin)
}

func TitleBar_TitleBarPaintFor(view_width int32, height int32) TitleBarPaint {
	var paint TitleBarPaint = TitleBarPaint{}
	paint.Bounds.Width = float32(view_width)
	paint.Bounds.Height = float32(height)
	paint.Divider.X = 0.0
	paint.Divider.Y = float32((int32(number_runtime_bits(uint64(height), uint64(1), 32, true, 2))))
	paint.Divider.Width = float32(view_width)
	paint.Divider.Height = 1.0
	return paint
}

func TitleBar_TitleBarTitlePaintFor(layout TitleBarLayout, title_width int32, title_line_height int32) TitleBarTitlePaint {
	var paint TitleBarTitlePaint = TitleBarTitlePaint{}
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((layout.TitleBounds.X+((layout.TitleBounds.Width-float32(title_width))/2.0))), 32, true)), uint64(0), 32, true, 0))
	paint.X = value_0
	var value_1 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((layout.TitleBounds.Y+((layout.TitleBounds.Height-float32(title_line_height))/2.0))), 32, true)), uint64(0), 32, true, 0))
	paint.Y = value_1
	return paint
}

func TitleBar_TitleBarShouldShrinkTitleFont(title_width int32, max_width int32, font int32, min_font int32) bool {
	var value_0 bool = (font > min_font)
	if value_0 {
		value_0 = (title_width > max_width)
	}
	return value_0
}

func TitleBar_TitleBarShrinkTitleFontStep(title_width int32, max_width int32, font int32, min_font int32) int32 {
	var value_0 bool = TitleBar_TitleBarShouldShrinkTitleFont(title_width, max_width, font, min_font)
	if value_0 {
		return (int32(number_runtime_bits(uint64(font), uint64(1), 32, true, 2)))
	}
	return font
}
