// Code generated by k2go from runtime/tree_view.kry. DO NOT EDIT.
package kryon

// #import drawing_props
type TreeViewMetrics struct {
	DefaultRowHeight int32
	IndentX          int32
	DepthIndent      int32
	MarkerWidth      int32
	TextGap          int32
}

type TreeViewScrollLayout struct {
	First   int32
	YOffset int32
}

type TreeViewTextPaint struct {
	MarkerX int32
	MarkerY int32
	TextX   int32
	TextY   int32
}

func TreeView_TreeViewMetricsFor(scale float32) TreeViewMetrics {
	var value_0 float32 = scale
	var value_1 float32 = 0.0
	var value_2 bool = value_0 <= value_1
	if value_2 {
		var value_3 float32 = 1.0
		scale = value_3
	}
	var metrics TreeViewMetrics = TreeViewMetrics{}
	var value_4 float32 = 28.0
	var value_5 float32 = scale
	var value_6 float32 = value_4 * value_5
	var value_7 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_6), 32, true)), uint64(0), 32, true, 0))
	metrics.DefaultRowHeight = value_7
	var value_8 float32 = 8.0
	var value_9 float32 = scale
	var value_10 float32 = value_8 * value_9
	var value_11 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_10), 32, true)), uint64(0), 32, true, 0))
	metrics.IndentX = value_11
	var value_12 float32 = 18.0
	var value_13 float32 = scale
	var value_14 float32 = value_12 * value_13
	var value_15 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_14), 32, true)), uint64(0), 32, true, 0))
	metrics.DepthIndent = value_15
	var value_16 float32 = 16.0
	var value_17 float32 = scale
	var value_18 float32 = value_16 * value_17
	var value_19 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_18), 32, true)), uint64(0), 32, true, 0))
	metrics.MarkerWidth = value_19
	var value_20 float32 = 2.0
	var value_21 float32 = scale
	var value_22 float32 = value_20 * value_21
	var value_23 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_22), 32, true)), uint64(0), 32, true, 0))
	metrics.TextGap = value_23
	var value_24 TreeViewMetrics = metrics
	return value_24
}

func TreeView_TreeViewRowHeight(requested_row_height int32, scale float32, metrics TreeViewMetrics) int32 {
	var value_0 float32 = scale
	var value_1 float32 = 0.0
	var value_2 bool = value_0 <= value_1
	if value_2 {
		var value_3 float32 = 1.0
		scale = value_3
	}
	var value_4 int32 = requested_row_height
	var value_5 int32 = 0
	var value_6 bool = value_4 > value_5
	if value_6 {
		var value_7 int32 = requested_row_height
		var value_8 float32 = float32(value_7)
		var value_9 float32 = scale
		var value_10 float32 = value_8 * value_9
		var value_11 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_10), 32, true)), uint64(0), 32, true, 0))
		var height int32 = value_11
		var value_12 int32 = height
		var value_13 int32 = 0
		var value_14 bool = value_12 > value_13
		if value_14 {
			var value_15 int32 = height
			return value_15
		}
	}
	var value_16 int32 = metrics.DefaultRowHeight
	return value_16
}

func TreeView_TreeViewContentHeight(item_count int32, row_height int32) int32 {
	var value_0 int32 = item_count
	var value_1 int32 = 0
	var value_2 bool = value_0 <= value_1
	var value_3 bool = value_2
	if !value_3 {
		var value_4 int32 = row_height
		var value_5 int32 = 0
		var value_6 bool = value_4 <= value_5
		value_3 = value_6
	}
	if value_3 {
		var value_7 int32 = 0
		return value_7
	}
	var value_8 int32 = item_count
	var value_9 int32 = row_height
	var value_10 int32 = int32(number_runtime_bits(uint64(value_8), uint64(value_9), 32, true, 3))
	return value_10
}

func TreeView_TreeViewMaxScroll(viewport_height int32, content_height int32) int32 {
	var value_0 int32 = content_height
	var value_1 int32 = viewport_height
	var value_2 int32 = int32(number_runtime_bits(uint64(value_0), uint64(value_1), 32, true, 2))
	var max_scroll int32 = value_2
	var value_3 int32 = max_scroll
	var value_4 int32 = 0
	var value_5 bool = value_3 < value_4
	if value_5 {
		var value_6 int32 = 0
		return value_6
	}
	var value_7 int32 = max_scroll
	return value_7
}

func TreeView_TreeViewScrollFor(scroll_y int32, row_height int32) TreeViewScrollLayout {
	var layout TreeViewScrollLayout = TreeViewScrollLayout{}
	var value_0 int32 = scroll_y
	var value_1 int32 = 0
	var value_2 bool = value_0 < value_1
	if value_2 {
		var value_3 int32 = 0
		scroll_y = value_3
	}
	var value_4 int32 = row_height
	var value_5 int32 = 0
	var value_6 bool = value_4 <= value_5
	if value_6 {
		var value_7 int32 = 1
		row_height = value_7
	}
	var value_8 int32 = scroll_y
	var value_9 int32 = row_height
	var value_10 int32 = int32(number_runtime_bits(uint64(value_8), uint64(value_9), 32, true, 4))
	layout.First = value_10
	var value_11 int32 = scroll_y
	var value_12 int32 = row_height
	var value_13 int32 = int32(number_runtime_bits(uint64(value_11), uint64(value_12), 32, true, 5))
	layout.YOffset = value_13
	var value_14 TreeViewScrollLayout = layout
	return value_14
}

func TreeView_TreeViewVisibleRows(viewport_height int32, row_height int32) int32 {
	var value_0 int32 = viewport_height
	var value_1 int32 = 0
	var value_2 bool = value_0 <= value_1
	if value_2 {
		var value_3 int32 = 0
		return value_3
	}
	var value_4 int32 = row_height
	var value_5 int32 = 0
	var value_6 bool = value_4 <= value_5
	if value_6 {
		var value_7 int32 = 1
		row_height = value_7
	}
	var value_8 int32 = viewport_height
	var value_9 int32 = row_height
	var value_10 int32 = int32(number_runtime_bits(uint64(value_8), uint64(value_9), 32, true, 4))
	var value_11 int32 = 1
	var value_12 int32 = int32(number_runtime_bits(uint64(value_10), uint64(value_11), 32, true, 1))
	return value_12
}

func TreeView_TreeViewRowBounds(bounds Rectangle, visible_index int32, row_height int32, y_offset int32) Rectangle {
	var row Rectangle = Rectangle{}
	var value_0 float32 = bounds.X
	row.X = value_0
	var value_1 float32 = bounds.Y
	var value_2 int32 = visible_index
	var value_3 int32 = row_height
	var value_4 int32 = int32(number_runtime_bits(uint64(value_2), uint64(value_3), 32, true, 3))
	var value_5 int32 = y_offset
	var value_6 int32 = int32(number_runtime_bits(uint64(value_4), uint64(value_5), 32, true, 2))
	var value_7 float32 = float32(value_6)
	var value_8 float32 = value_1 + value_7
	row.Y = value_8
	var value_9 float32 = bounds.Width
	row.Width = value_9
	var value_10 int32 = row_height
	var value_11 float32 = float32(value_10)
	row.Height = value_11
	var value_12 Rectangle = row
	return value_12
}

func TreeView_TreeViewIndent(depth int32, metrics TreeViewMetrics) int32 {
	var value_0 int32 = depth
	var value_1 int32 = 0
	var value_2 bool = value_0 < value_1
	if value_2 {
		var value_3 int32 = 0
		depth = value_3
	}
	var value_4 int32 = metrics.IndentX
	var value_5 int32 = depth
	var value_6 int32 = metrics.DepthIndent
	var value_7 int32 = int32(number_runtime_bits(uint64(value_5), uint64(value_6), 32, true, 3))
	var value_8 int32 = int32(number_runtime_bits(uint64(value_4), uint64(value_7), 32, true, 1))
	return value_8
}

func TreeView_TreeViewMarkerBounds(row Rectangle, depth int32, metrics TreeViewMetrics) Rectangle {
	var marker Rectangle = Rectangle{}
	var value_0 int32 = depth
	var value_1 TreeViewMetrics = metrics
	var value_2 int32 = TreeView_TreeViewIndent(value_0, value_1)
	var indent int32 = value_2
	var value_3 float32 = row.X
	var value_4 int32 = indent
	var value_5 float32 = float32(value_4)
	var value_6 float32 = value_3 + value_5
	marker.X = value_6
	var value_7 float32 = row.Y
	marker.Y = value_7
	var value_8 int32 = metrics.MarkerWidth
	var value_9 float32 = float32(value_8)
	marker.Width = value_9
	var value_10 float32 = row.Height
	marker.Height = value_10
	var value_11 Rectangle = marker
	return value_11
}

func TreeView_TreeViewTextBounds(row Rectangle, depth int32, metrics TreeViewMetrics) Rectangle {
	var text Rectangle = Rectangle{}
	var value_0 int32 = depth
	var value_1 TreeViewMetrics = metrics
	var value_2 int32 = TreeView_TreeViewIndent(value_0, value_1)
	var indent int32 = value_2
	var value_3 float32 = row.X
	var value_4 int32 = indent
	var value_5 int32 = metrics.MarkerWidth
	var value_6 int32 = int32(number_runtime_bits(uint64(value_4), uint64(value_5), 32, true, 1))
	var value_7 int32 = metrics.TextGap
	var value_8 int32 = int32(number_runtime_bits(uint64(value_6), uint64(value_7), 32, true, 1))
	var value_9 float32 = float32(value_8)
	var value_10 float32 = value_3 + value_9
	var x float32 = value_10
	var value_11 float32 = x
	text.X = value_11
	var value_12 float32 = row.Y
	text.Y = value_12
	var value_13 float32 = row.Width
	var value_14 float32 = x
	var value_15 float32 = row.X
	var value_16 float32 = value_14 - value_15
	var value_17 float32 = value_13 - value_16
	text.Width = value_17
	var value_18 float32 = text.Width
	var value_19 float32 = 0.0
	var value_20 bool = value_18 < value_19
	if value_20 {
		var value_21 float32 = 0.0
		text.Width = value_21
	}
	var value_22 float32 = row.Height
	text.Height = value_22
	var value_23 Rectangle = text
	return value_23
}

func TreeView_TreeViewTextPaintFor(marker Rectangle, text Rectangle, text_line_height int32) TreeViewTextPaint {
	var paint TreeViewTextPaint = TreeViewTextPaint{}
	var value_0 float32 = marker.X
	var value_1 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_0), 32, true)), uint64(0), 32, true, 0))
	paint.MarkerX = value_1
	var value_2 float32 = marker.Y
	var value_3 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_2), 32, true)), uint64(0), 32, true, 0))
	var value_4 float32 = marker.Height
	var value_5 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_4), 32, true)), uint64(0), 32, true, 0))
	var value_6 int32 = text_line_height
	var value_7 int32 = int32(number_runtime_bits(uint64(value_5), uint64(value_6), 32, true, 2))
	var value_8 int32 = 2
	var value_9 int32 = int32(number_runtime_bits(uint64(value_7), uint64(value_8), 32, true, 4))
	var value_10 int32 = int32(number_runtime_bits(uint64(value_3), uint64(value_9), 32, true, 1))
	paint.MarkerY = value_10
	var value_11 float32 = text.X
	var value_12 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_11), 32, true)), uint64(0), 32, true, 0))
	paint.TextX = value_12
	var value_13 float32 = text.Y
	var value_14 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_13), 32, true)), uint64(0), 32, true, 0))
	var value_15 float32 = text.Height
	var value_16 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(value_15), 32, true)), uint64(0), 32, true, 0))
	var value_17 int32 = text_line_height
	var value_18 int32 = int32(number_runtime_bits(uint64(value_16), uint64(value_17), 32, true, 2))
	var value_19 int32 = 2
	var value_20 int32 = int32(number_runtime_bits(uint64(value_18), uint64(value_19), 32, true, 4))
	var value_21 int32 = int32(number_runtime_bits(uint64(value_14), uint64(value_20), 32, true, 1))
	paint.TextY = value_21
	var value_22 TreeViewTextPaint = paint
	return value_22
}

func TreeView_TreeViewScrollbarBoundsFor(bounds Rectangle, scrollbar_width int32) Rectangle {
	var bar Rectangle = Rectangle{}
	var value_0 int32 = scrollbar_width
	var value_1 int32 = 0
	var value_2 bool = value_0 <= value_1
	if value_2 {
		var value_3 int32 = 8
		scrollbar_width = value_3
	}
	var value_4 float32 = bounds.X
	var value_5 float32 = bounds.Width
	var value_6 float32 = value_4 + value_5
	var value_7 int32 = scrollbar_width
	var value_8 float32 = float32(value_7)
	var value_9 float32 = value_6 - value_8
	bar.X = value_9
	var value_10 float32 = bounds.Y
	bar.Y = value_10
	var value_11 int32 = scrollbar_width
	var value_12 float32 = float32(value_11)
	bar.Width = value_12
	var value_13 float32 = bounds.Height
	bar.Height = value_13
	var value_14 Rectangle = bar
	return value_14
}
