// Code generated by k2go from runtime/tree_view.kry. DO NOT EDIT.
package kryon

// #import drawing_props
// #import style
// #import control_props
type TreeViewMetrics struct {
	DefaultRowHeight int32
	IndentX          int32
	DepthIndent      int32
	MarkerWidth      int32
	TextGap          int32
	ScrollbarWidth   int32
}

type TreeViewScrollLayout struct {
	First   int32
	YOffset int32
}

type TreeViewTextPaint struct {
	MarkerX int32
	MarkerY int32
	TextX   int32
	TextY   int32
}

type TreeViewRowDecision struct {
	Select         bool
	SelectedID     int32
	ConsumeRelease bool
	Changed        bool
}

func TreeView_TreeViewHas(fields uint32, field uint32) bool {
	var value_0 bool = (uint32(number_runtime_bits(uint64(fields), uint64(field), 32, false, 8))) != uint32(number_runtime_bits(uint64(0), uint64(0), 32, false, 0))
	return value_0
}

func TreeView_TreeViewMetric(fields uint32, field uint32, value float32, fallback float32, scale float32, allow_zero bool) int32 {
	var value_0 bool = TreeView_TreeViewHas(fields, field)
	var value_1 bool = !value_0
	if !value_1 {
		value_1 = (value < 0.0)
	}
	var value_2 bool = value_1
	if !value_2 {
		var value_3 bool = !allow_zero
		if value_3 {
			value_3 = (value <= 0.0)
		}
		value_2 = value_3
	}
	if value_2 {
		value = fallback
	}
	var value_4 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((value*scale)), 32, true)), uint64(0), 32, true, 0))
	return value_4
}

func TreeView_TreeViewMetricsFor(scale float32, panel StyleFrame, item StyleFrame) TreeViewMetrics {
	if scale <= 0.0 {
		scale = 1.0
	}
	var metrics TreeViewMetrics = TreeViewMetrics{}
	var row_height float32 = 28.0
	var value_0 uint32 = item.Value.Fields
	var value_1 uint32 = uint32(number_runtime_bits(uint64(int32(StyleFontSize)), uint64(0), 32, false, 0))
	var value_2 bool = TreeView_TreeViewHas(value_0, value_1)
	var value_3 bool = value_2
	if value_3 {
		var value_4 uint32 = item.Value.Fields
		var value_5 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingY)), uint64(0), 32, false, 0))
		var value_6 bool = TreeView_TreeViewHas(value_4, value_5)
		value_3 = value_6
	}
	if value_3 {
		row_height = (item.Value.FontSize + (item.Value.PaddingY * 2.0))
	}
	var value_7 uint32 = item.Value.Fields
	var value_8 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_9 float32 = item.Value.OffsetY
	var value_10 int32 = TreeView_TreeViewMetric(value_7, value_8, value_9, row_height, scale, false)
	metrics.DefaultRowHeight = value_10
	var value_11 uint32 = panel.Value.Fields
	var value_12 uint32 = uint32(number_runtime_bits(uint64(int32(StylePaddingX)), uint64(0), 32, false, 0))
	var value_13 float32 = panel.Value.PaddingX
	var value_14 float32 = 8.0
	var value_15 int32 = TreeView_TreeViewMetric(value_11, value_12, value_13, value_14, scale, true)
	metrics.IndentX = value_15
	var value_16 uint32 = item.Value.Fields
	var value_17 uint32 = uint32(number_runtime_bits(uint64(int32(StyleContentOffset)), uint64(0), 32, false, 0))
	var value_18 float32 = item.Value.OffsetX
	var value_19 float32 = 18.0
	var value_20 int32 = TreeView_TreeViewMetric(value_16, value_17, value_18, value_19, scale, false)
	metrics.DepthIndent = value_20
	var value_21 uint32 = item.Value.Fields
	var value_22 uint32 = uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))
	var value_23 float32 = item.Value.IconSize
	var value_24 float32 = 16.0
	var value_25 int32 = TreeView_TreeViewMetric(value_21, value_22, value_23, value_24, scale, false)
	metrics.MarkerWidth = value_25
	var value_26 uint32 = item.Value.Fields
	var value_27 uint32 = uint32(number_runtime_bits(uint64(int32(StyleGap)), uint64(0), 32, false, 0))
	var value_28 float32 = item.Value.Gap
	var value_29 float32 = 2.0
	var value_30 int32 = TreeView_TreeViewMetric(value_26, value_27, value_28, value_29, scale, true)
	metrics.TextGap = value_30
	var value_31 uint32 = panel.Value.Fields
	var value_32 uint32 = uint32(number_runtime_bits(uint64(int32(StyleIconSize)), uint64(0), 32, false, 0))
	var value_33 float32 = panel.Value.IconSize
	var value_34 float32 = 8.0
	var value_35 int32 = TreeView_TreeViewMetric(value_31, value_32, value_33, value_34, scale, true)
	metrics.ScrollbarWidth = value_35
	return metrics
}

func TreeView_TreeViewRowHeight(requested_row_height int32, scale float32, metrics TreeViewMetrics) int32 {
	if scale <= 0.0 {
		scale = 1.0
	}
	if requested_row_height > 0 {
		var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64((float32(requested_row_height)*scale)), 32, true)), uint64(0), 32, true, 0))
		var height int32 = value_0
		if height > 0 {
			return height
		}
	}
	return metrics.DefaultRowHeight
}

func TreeView_TreeViewContentHeight(item_count int32, row_height int32) int32 {
	var value_0 bool = (item_count <= 0)
	if !value_0 {
		value_0 = (row_height <= 0)
	}
	if value_0 {
		return 0
	}
	return (int32(number_runtime_bits(uint64(item_count), uint64(row_height), 32, true, 3)))
}

func TreeView_TreeViewMaxScroll(viewport_height int32, content_height int32) int32 {
	var max_scroll int32 = (int32(number_runtime_bits(uint64(content_height), uint64(viewport_height), 32, true, 2)))
	if max_scroll < 0 {
		return 0
	}
	return max_scroll
}

func TreeView_TreeViewScrollFor(scroll_y int32, row_height int32) TreeViewScrollLayout {
	var layout TreeViewScrollLayout = TreeViewScrollLayout{}
	if scroll_y < 0 {
		scroll_y = 0
	}
	if row_height <= 0 {
		row_height = 1
	}
	layout.First = (int32(number_runtime_bits(uint64(scroll_y), uint64(row_height), 32, true, 4)))
	layout.YOffset = (int32(number_runtime_bits(uint64(scroll_y), uint64(row_height), 32, true, 5)))
	return layout
}

func TreeView_TreeViewVisibleRows(viewport_height int32, row_height int32) int32 {
	if viewport_height <= 0 {
		return 0
	}
	if row_height <= 0 {
		row_height = 1
	}
	var value_0 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(viewport_height), uint64(row_height), 32, true, 4)))), uint64(1), 32, true, 1))
	return value_0
}

func TreeView_TreeViewRowBounds(bounds Rectangle, visible_index int32, row_height int32, y_offset int32) Rectangle {
	var row Rectangle = Rectangle{}
	row.X = bounds.X
	var value_0 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(visible_index), uint64(row_height), 32, true, 3)))), uint64(y_offset), 32, true, 2))
	row.Y = (bounds.Y + float32(value_0))
	row.Width = bounds.Width
	row.Height = float32(row_height)
	return row
}

func TreeView_TreeViewIndent(depth int32, metrics TreeViewMetrics) int32 {
	if depth < 0 {
		depth = 0
	}
	var value_0 int32 = int32(number_runtime_bits(uint64(metrics.IndentX), uint64((int32(number_runtime_bits(uint64(depth), uint64(metrics.DepthIndent), 32, true, 3)))), 32, true, 1))
	return value_0
}

func TreeView_TreeViewMarkerBounds(row Rectangle, depth int32, metrics TreeViewMetrics) Rectangle {
	var marker Rectangle = Rectangle{}
	var value_0 int32 = TreeView_TreeViewIndent(depth, metrics)
	var indent int32 = value_0
	marker.X = (row.X + float32(indent))
	marker.Y = row.Y
	marker.Width = float32(metrics.MarkerWidth)
	marker.Height = row.Height
	return marker
}

func TreeView_TreeViewTextBounds(row Rectangle, depth int32, metrics TreeViewMetrics) Rectangle {
	var text Rectangle = Rectangle{}
	var value_0 int32 = TreeView_TreeViewIndent(depth, metrics)
	var indent int32 = value_0
	var value_1 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(indent), uint64(metrics.MarkerWidth), 32, true, 1)))), uint64(metrics.TextGap), 32, true, 1))
	var x float32 = (row.X + float32(value_1))
	text.X = x
	text.Y = row.Y
	text.Width = (row.Width - (x - row.X))
	if text.Width < 0.0 {
		text.Width = 0.0
	}
	text.Height = row.Height
	return text
}

func TreeView_TreeViewTextPaintFor(marker Rectangle, text Rectangle, text_line_height int32) TreeViewTextPaint {
	var paint TreeViewTextPaint = TreeViewTextPaint{}
	var value_0 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(marker.X), 32, true)), uint64(0), 32, true, 0))
	paint.MarkerX = value_0
	var value_1 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(marker.Y), 32, true)), uint64(0), 32, true, 0))
	var value_2 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(marker.Height), 32, true)), uint64(0), 32, true, 0))
	var value_3 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(value_2), uint64(text_line_height), 32, true, 2)))), uint64(2), 32, true, 4))
	paint.MarkerY = (int32(number_runtime_bits(uint64(value_1), uint64(value_3), 32, true, 1)))
	var value_4 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(text.X), 32, true)), uint64(0), 32, true, 0))
	paint.TextX = value_4
	var value_5 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(text.Y), 32, true)), uint64(0), 32, true, 0))
	var value_6 int32 = int32(number_runtime_bits(uint64(number_runtime_float(float64(text.Height), 32, true)), uint64(0), 32, true, 0))
	var value_7 int32 = int32(number_runtime_bits(uint64((int32(number_runtime_bits(uint64(value_6), uint64(text_line_height), 32, true, 2)))), uint64(2), 32, true, 4))
	paint.TextY = (int32(number_runtime_bits(uint64(value_5), uint64(value_7), 32, true, 1)))
	return paint
}

func TreeView_TreeViewMarkerText(expanded bool) string {
	if expanded {
		return "v"
	}
	return ">"
}

func TreeView_TreeViewRowDecisionFor(hot bool, released bool, selectable bool, has_selection bool, item_id int32) TreeViewRowDecision {
	var decision TreeViewRowDecision = TreeViewRowDecision{}
	decision.SelectedID = item_id
	var value_0 bool = hot
	if value_0 {
		value_0 = released
	}
	var value_1 bool = value_0
	if value_1 {
		value_1 = selectable
	}
	var value_2 bool = value_1
	if value_2 {
		value_2 = has_selection
	}
	if value_2 {
		decision.Select = true
		decision.ConsumeRelease = true
		decision.Changed = true
	}
	return decision
}

func TreeView_TreeViewScrollbarBoundsFor(bounds Rectangle, scrollbar_width int32) Rectangle {
	var bar Rectangle = Rectangle{}
	if scrollbar_width < 0 {
		scrollbar_width = 0
	}
	bar.X = ((bounds.X + bounds.Width) - float32(scrollbar_width))
	bar.Y = bounds.Y
	bar.Width = float32(scrollbar_width)
	bar.Height = bounds.Height
	return bar
}
