// Code generated by k2go from runtime/window_props.kry. DO NOT EDIT.
package kryon

type NativeWindowFlags int32

const (
	NATIVEWINDOWBORDERLESS  NativeWindowFlags = 1
	NATIVEWINDOWALWAYSONTOP NativeWindowFlags = 2
	NATIVEWINDOWSKIPTASKBAR NativeWindowFlags = 4
	NATIVEWINDOWTOPRIGHT    NativeWindowFlags = 8
	NATIVEWINDOWCENTER      NativeWindowFlags = 16
	NATIVEWINDOWSTICKY      NativeWindowFlags = 32
)
