# Kryon IR Library (TaijiOS mkfile)
#
# Builds the core IR library for TaijiOS/Inferno
# Uses custom build script due to deep directory structure

<../../mkconfig

LIB=libkryon_ir.a

# List all source files (used for dependency tracking)
SRCS=\
	src/ir_builder.c\
	src/core/ir_component_types.c\
	src/core/ir_component_factory.c\
	src/core/ir_component_handler.c\
	src/core/ir_capability.c\
	src/core/ir_property_registry.c\
	src/core/ir_lifecycle_hooks.c\
	src/components/button.c\
	src/components/text.c\
	src/components/flexbox.c\
	src/components/input.c\
	src/components/image.c\
	src/components/canvas.c\
	src/components/tabs.c\
	src/components/table.c\
	src/components/modal.c\
	src/components/dropdown.c\
	src/components/checkbox.c\
	src/components/misc.c\
	src/components/registry.c\
	src/style/ir_style_builder.c\
	src/style/ir_style_types.c\
	src/style/ir_stylesheet.c\
	src/style/ir_style_vars.c\
	src/style/ir_gradient.c\
	src/layout/ir_layout.c\
	src/layout/ir_layout_builder.c\
	src/layout/ir_layout_debug.c\
	src/layout/ir_layout_strategy.c\
	src/layout/layout_helpers.c\
	src/layout/strategies/strategy_container.c\
	src/layout/strategies/strategy_row.c\
	src/layout/strategies/strategy_column.c\
	src/layout/strategies/strategy_text.c\
	src/layout/strategies/strategy_image.c\
	src/layout/strategies/strategy_canvas.c\
	src/layout/strategies/strategy_for.c\
	src/logic/ir_logic.c\
	src/logic/ir_executor.c\
	src/logic/ir_expression.c\
	src/logic/ir_expression_parser.c\
	src/logic/ir_expression_compiler.c\
	src/logic/ir_expression_cache.c\
	src/logic/ir_builtin_registry.c\
	src/logic/ir_for.c\
	src/logic/ir_for_expand.c\
	src/events/ir_event_builder.c\
	src/events/ir_event_types.c\
	src/events/ir_input.c\
	src/events/ir_hit_test.c\
	src/serialization/ir_serialization.c\
	src/serialization/ir_json_serialize.c\
	src/serialization/ir_json_deserialize.c\
	src/serialization/ir_json_context.c\
	src/serialization/ir_serialize_types.c\
	src/state/ir_state_manager.c\
	src/state/ir_instance.c\
	src/state/ir_hot_reload.c\
	src/state/ir_reactive_manifest.c\
	src/state/ir_module_refs.c\
	src/features/ir_tabgroup.c\
	src/features/ir_table.c\
	src/features/ir_markdown.c\
	src/features/ir_native_canvas.c\
	src/features/ir_text_shaping.c\
	src/utils/ir_string_builder.c\
	src/utils/ir_buffer.c\
	src/utils/ir_log.c\
	src/utils/ir_json_helpers.c\
	src/utils/ir_hashmap.c\
	src/utils/ir_memory.c\
	src/utils/ir_color_utils.c\
	src/utils/ir_validation.c\
	src/utils/ir_format_detect.c\
	src/utils/ir_asset.c\
	src/utils/ir_krb.c\
	src/utils/ir_source_structures.c\
	src/utils/ir_json.c\
	parsers/kry/kry_allocator.c\
	parsers/kry/kry_lexer.c\
	parsers/kry/kry_ast_factory.c\
	parsers/kry/kry_tokens.c\
	parsers/kry/kry_to_ir_context.c\
	parsers/kry/kry_to_ir_expressions.c\
	parsers/kry/kry_to_ir_properties.c\
	parsers/kry/kry_to_ir_functions.c\
	parsers/kry/kry_parser.c\
	parsers/kry/kry_to_ir.c\
	parsers/kry/kry_expression.c\
	parsers/kry/kry_arrow_registry.c\
	parsers/kry/kry_struct_parser.c\
	parsers/kry/kry_struct_to_ir.c\
	parsers/kry/kry_ir_validator.c\
	parsers/markdown/markdown_ast.c\
	parsers/markdown/markdown_parser.c\
	parsers/markdown/markdown_to_ir.c\
	parsers/html/html_ast.c\
	parsers/html/html_to_ir.c\
	parsers/html/html_parser.c\
	parsers/html/css_parser.c\
	parsers/html/css_stylesheet.c\
	parsers/c/c_parser.c\
	parsers/tcl/tcl_lexer.c\
	parsers/tcl/tcl_parser.c\
	parsers/tcl/tcl_to_ir.c\
	parsers/tcl/tcl_widget_registry.c\
	parsers/parser_utils.c\
	parsers/common/parser_io_utils.c\
	../bindings/c/kryon.c\

# Compiler flags
CFLAGS=$CFLAGS\
	-Iinclude\
	-I../include\
	-I../third_party/cJSON\
	-I../third_party/tomlc99\
	-I../bindings/c\
	-Isrc/utils\
	-DIR_USE_SINGLE_PASS_LAYOUT\
	-D__TAIJIOS__\

LIBRARY=$ROOT/$OBJDIR/lib/$LIB

default:V: all

all install:V: $LIBRARY

# Build the library by compiling all sources and archiving
$LIBRARY:V: $SRCS
	for i in $SRCS
	do
		echo "  Compiling $i..."
		$CC $CFLAGS $i || exit 1
	done
	echo "  Archiving into $LIBRARY..."
	$AR $ARFLAGS $LIBRARY *.o
	echo "  Installed $LIB"

clean:V:
	rm -f *.o
	rm -f src/*.o src/*/*.o src/*/*/*.o
	rm -f parsers/*.o parsers/*/*.o
	rm -f ../bindings/c/*.o

nuke:V: clean
	rm -f $LIBRARY
