# Tcl/Tk Codegen Makefile
# Uses shared template from common.mk

include ../common.mk

# Additional flags
CFLAGS += -std=c11

# Test target
test: $(STATIC_LIB)
	@echo "Testing Tcl/Tk codegen..."
	# TODO: Add test harness

.PHONY: test
