# Kry Codegen (TaijiOS mkfile)
# Generates Kry source code from Kryon IR (for code formatting/roundtrip)

<../../../mkconfig

LIB=libkryon_codegen_kry.a

OFILES=\
	kry_codegen.$O\

HFILES=\
	../codegen_common.h\

CFLAGS=$CFLAGS\
	-I../../include\
	-I../../ir/include\
	-I../../third_party/cJSON\
	-I..\

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
