# Codegens Build Orchestration (TaijiOS mkfile)
# Builds all code generators in order

<../../mkconfig

# Build codegen_common first, then TKIR, then all codegens
all:V: codegen_common tkir tcltk limbo web c android kry markdown

# Build codegen_common as a library
codegen_common:V:
	$CC $CFLAGS -I../include -I../ir/include -I../third_party/cJSON -c codegen_common.c
	ar ruvs $ROOT/$OBJDIR/lib/libkryon_codegen_common.a codegen_common.o

# Build TKIR (Toolkit Intermediate Representation)
tkir:V: codegen_common
	(cd tkir && mk install)

# Build individual codegens
limbo:V: tkir
	(cd limbo && mk install)

web:V: codegen_common
	(cd web && mk install)

tcltk:V: tkir
	(cd tcltk && mk install)

c:V: tkir
	(cd c && mk install)

android:V: codegen_common
	(cd android && mk install)

kry:V: codegen_common
	(cd kry && mk install)

markdown:V: codegen_common
	(cd markdown && mk install)

clean:V:
	rm -f codegen_common.o codegen_common.$O
	(cd tkir && mk clean)
	(cd tcltk && mk clean)
	(cd limbo && mk clean)
	(cd web && mk clean)
	(cd c && mk clean)
	(cd android && mk clean)
	(cd kry && mk clean)
	(cd markdown && mk clean)

install:V: all

nuke:V:
	rm -f $ROOT/$OBJDIR/lib/libkryon_codegen_common.a
	rm -f $ROOT/$OBJDIR/lib/libkryon_tkir.a
	(cd tkir && mk nuke)
	(cd tcltk && mk nuke)
	(cd limbo && mk nuke)
	(cd web && mk nuke)
	(cd c && mk nuke)
	(cd android && mk nuke)
	(cd kry && mk nuke)
	(cd markdown && mk nuke)
