#!/usr/bin/env python3
import re
import sys
from pathlib import Path

ICON_TYPES = {
    "backward": "FLINT_ICON_TYPE_BACKWARD",
    "check": "FLINT_ICON_TYPE_CHECK",
    "droid": "FLINT_ICON_TYPE_DROID",
    "edit": "FLINT_ICON_TYPE_EDIT",
    "eye-closed": "FLINT_ICON_TYPE_EYE_CLOSED",
    "fdroid": "FLINT_ICON_TYPE_FDROID",
    "forward": "FLINT_ICON_TYPE_FORWARD",
    "gear": "FLINT_ICON_TYPE_GEAR",
    "github": "FLINT_ICON_TYPE_GITHUB",
    "globe": "FLINT_ICON_TYPE_GLOBE",
    "habits": "FLINT_ICON_TYPE_HABITS",
    "home": "FLINT_ICON_TYPE_HOME",
    "itch": "FLINT_ICON_TYPE_ITCH",
    "jupiter": "FLINT_ICON_TYPE_JUPITER",
    "lightoff": "FLINT_ICON_TYPE_LIGHTOFF",
    "lighton": "FLINT_ICON_TYPE_LIGHTON",
    "link": "FLINT_ICON_TYPE_LINK",
    "manual": "FLINT_ICON_TYPE_MANUAL",
    "mars": "FLINT_ICON_TYPE_MARS",
    "mercury": "FLINT_ICON_TYPE_MERCURY",
    "monero": "FLINT_ICON_TYPE_MONERO",
    "moon": "FLINT_ICON_TYPE_MOON",
    "mute": "FLINT_ICON_TYPE_MUTE",
    "pause": "FLINT_ICON_TYPE_PAUSE",
    "pencil": "FLINT_ICON_TYPE_PENCIL",
    "play": "FLINT_ICON_TYPE_PLAY",
    "playstore": "FLINT_ICON_TYPE_PLAYSTORE",
    "quest": "FLINT_ICON_TYPE_QUEST",
    "ray": "FLINT_ICON_TYPE_RAY",
    "return": "FLINT_ICON_TYPE_RETURN",
    "rocket": "FLINT_ICON_TYPE_ROCKET",
    "routine": "FLINT_ICON_TYPE_ROUTINE",
    "saturn": "FLINT_ICON_TYPE_SATURN",
    "save": "FLINT_ICON_TYPE_SAVE",
    "sound": "FLINT_ICON_TYPE_SOUND",
    "sound0": "FLINT_ICON_TYPE_SOUND0",
    "sound1": "FLINT_ICON_TYPE_SOUND1",
    "sound2": "FLINT_ICON_TYPE_SOUND2",
    "sound3": "FLINT_ICON_TYPE_SOUND3",
    "srht": "FLINT_ICON_TYPE_SRHT",
    "stat": "FLINT_ICON_TYPE_STAT",
    "stripe": "FLINT_ICON_TYPE_STRIPE",
    "sun": "FLINT_ICON_TYPE_SUN",
    "tcl": "FLINT_ICON_TYPE_TCL",
    "telegram": "FLINT_ICON_TYPE_TELEGRAM",
    "text": "FLINT_ICON_TYPE_TEXT",
    "tile": "FLINT_ICON_TYPE_TILE",
    "tile2": "FLINT_ICON_TYPE_TILE2",
    "tile3": "FLINT_ICON_TYPE_TILE3",
    "tile4": "FLINT_ICON_TYPE_TILE4",
    "timeline": "FLINT_ICON_TYPE_TIMELINE",
    "todos": "FLINT_ICON_TYPE_TODOS",
    "trash": "FLINT_ICON_TYPE_TRASH",
    "tux": "FLINT_ICON_TYPE_TUX",
    "uxn": "FLINT_ICON_TYPE_UXN",
    "venus": "FLINT_ICON_TYPE_VENUS",
    "wasm": "FLINT_ICON_TYPE_WASM",
    "wasm4": "FLINT_ICON_TYPE_WASM4",
    "win": "FLINT_ICON_TYPE_WIN",
    "x": "FLINT_ICON_TYPE_X",
}


def c_name(stem):
    return "flint_icon_" + re.sub(r"[^A-Za-z0-9_]", "_", stem)


def write_bytes(out, data):
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        out.write("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",\n")


def main():
    if len(sys.argv) != 3:
        print("usage: embed_icons.py <icons-dir> <output.c>", file=sys.stderr)
        return 2

    icons_dir = Path(sys.argv[1])
    output = Path(sys.argv[2])
    icons = sorted(icons_dir.glob("*.png"))
    output.parent.mkdir(parents=True, exist_ok=True)

    with output.open("w", encoding="utf-8") as out:
        out.write("/* Generated by scripts/embed_icons.py. Do not edit. */\n")
        out.write('#include "flint_icons.h"\n\n')

        entries = []
        for icon in icons:
            stem = icon.stem
            icon_type = ICON_TYPES.get(stem)
            if icon_type is None:
                continue
            symbol = c_name(stem)
            data = icon.read_bytes()
            out.write(f"static const unsigned char {symbol}[] = {{\n")
            write_bytes(out, data)
            out.write("};\n\n")
            entries.append((icon_type, stem, symbol, len(data)))

        out.write("const FlintIconAsset flint_icon_assets[] = {\n")
        for icon_type, stem, symbol, size in entries:
            out.write(f'    {{{icon_type}, "{stem}", {symbol}, {size}u}},\n')
        out.write("};\n\n")
        out.write(f"const unsigned int flint_icon_asset_count = {len(entries)}u;\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
