#!/usr/bin/env python3
"""Embed generated icon sheets and regenerate the public icon catalog."""

import argparse
import json
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SHEETS = (
    ("ui", "UI_ICON_SHEET_UI", "ui_icon_atlas_png"),
    ("pfp", "UI_ICON_SHEET_PFP", "ui_pfp_atlas_png"),
    ("platforms", "UI_ICON_SHEET_PLATFORMS", "ui_platforms_atlas_png"),
    ("payments", "UI_ICON_SHEET_PAYMENTS", "ui_payments_atlas_png"),
    ("language", "UI_ICON_SHEET_LANGUAGE", "ui_language_atlas_png"),
    ("tiles", "UI_ICON_SHEET_TILES", "ui_tiles_atlas_png"),
    ("logos", "UI_ICON_SHEET_LOGOS", "ui_logos_atlas_png"),
)


def enum_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", name).upper()


def byte_array(symbol: str, data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 32):
        chunk = data[offset:offset + 32]
        lines.append("   " + "".join(f" 0x{value:02x}," for value in chunk))
    return (
        f"const unsigned char {symbol}[] = {{\n" + "\n".join(lines) +
        f"\n}};\nconst unsigned int {symbol}_size = {len(data)}u;\n"
    )


def replace_if_changed(path: Path, text: str) -> None:
    if path.is_file() and path.read_text() == text:
        return
    path.write_text(text)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("icon_dir", nargs="?", default="icons")
    parser.add_argument("output", nargs="?", default="src/ui/ui_icon_assets.c")
    args = parser.parse_args()
    icon_dir = ROOT / args.icon_dir

    records = []
    arrays = []
    for sheet_name, sheet_enum, symbol in SHEETS:
        manifest = json.loads((icon_dir / f"{sheet_name}.json").read_text())
        arrays.append(byte_array(symbol, (icon_dir / manifest["image"]).read_bytes()))
        for icon in manifest["icons"]:
            records.append({**icon, "sheet": sheet_enum})
    records.sort(key=lambda icon: icon["name"])

    assets = [
        "/* Generated by scripts/embed-icon-sheets.py. DO NOT EDIT MANUALLY. */",
        '#include "ui_icons.h"',
        "",
        *arrays,
        "const UIIconAsset ui_icon_assets[] = {",
    ]
    for icon in records:
        assets.append(
            f'    {{UI_ICON_TYPE_{enum_name(icon["name"])}, "{icon["name"].replace("/", "_")}", '
            f'{icon["sheet"]}, {{{icon["x"]}, {icon["y"]}, '
            f'{icon["width"]}, {icon["height"]}}}}},'
        )
    assets.extend(("};", "", f"const unsigned int ui_icon_asset_count = {len(records)}u;", ""))
    replace_if_changed(ROOT / args.output, "\n".join(assets))

    enum_lines = [
        "/* Generated by scripts/embed-icon-sheets.py. DO NOT EDIT MANUALLY. */",
        "#ifndef UI_ICON_TYPES_H",
        "#define UI_ICON_TYPES_H",
        "",
        "typedef enum {",
        "    UI_ICON_TYPE_NONE = 0,",
        "",
    ]
    enum_lines.extend(f"    UI_ICON_TYPE_{enum_name(icon['name'])}," for icon in records)
    enum_lines.extend(("", f"    UI_ICON_TYPE_COUNT = {len(records) + 1}", "} UIIconType;", "", "#endif /* UI_ICON_TYPES_H */", ""))
    replace_if_changed(ROOT / "include/ui_icon_types.h", "\n".join(enum_lines))

    name_lines = [
        "/* Generated by scripts/embed-icon-sheets.py. DO NOT EDIT MANUALLY. */",
        "#include <stddef.h>",
        '#include "ui_icon_types.h"',
        "",
        "const char *ui_icon_names[] = {",
        "    NULL,  /* UI_ICON_TYPE_NONE */",
    ]
    name_lines.extend(
        f'    "{icon["name"].replace("/", "_")}.png",  /* UI_ICON_TYPE_{enum_name(icon["name"])} */'
        for icon in records
    )
    name_lines.extend(("};", ""))
    replace_if_changed(ROOT / "src/ui/ui_icon_names.c", "\n".join(name_lines))
    print(f"embedded {len(SHEETS)} icon sheets, {len(records)} catalog entries")


if __name__ == "__main__":
    main()
