#ifndef FLINT_VERSION_H
#define FLINT_VERSION_H

#define FLINT_VERSION_MAJOR 0
#define FLINT_VERSION_MINOR 1
#define FLINT_VERSION_PATCH 3
#define FLINT_VERSION_STRING "v0.1.3"

#endif /* FLINT_VERSION_H */
