#ifndef FLINT_VERSION_H
#define FLINT_VERSION_H

#define FLINT_VERSION_MAJOR 0
#define FLINT_VERSION_MINOR 1
#define FLINT_VERSION_PATCH 0
#define FLINT_VERSION_STRING "0.1.0"

#endif /* FLINT_VERSION_H */
