#ifndef KRYON_VERSION_H
#define KRYON_VERSION_H

#define KRYON_VERSION_MAJOR 0
#define KRYON_VERSION_MINOR 1
#define KRYON_VERSION_PATCH 6
#define KRYON_VERSION_STRING "v0.1.6"

#endif /* KRYON_VERSION_H */
