#ifndef KRYON_VERSION_H
#define KRYON_VERSION_H

#define KRYON_VERSION_MAJOR 0
#define KRYON_VERSION_MINOR 1
#define KRYON_VERSION_PATCH 16
#define KRYON_VERSION_STRING "v0.1.16"

#endif /* KRYON_VERSION_H */
