/* Generated by k2c from runtime/accessibility_node.kry. */
#ifndef K_RUNTIME_ACCESSIBILITY_NODE_H
#define K_RUNTIME_ACCESSIBILITY_NODE_H

#include <stdint.h>
#include <stdbool.h>
#include "kry_bounds.h"

#ifndef KIR_STRING_VALUE_DEFINED
#define KIR_STRING_VALUE_DEFINED
#include <stddef.h>
#include <string.h>
/* Immutable borrowed UTF-8 bytes; length preserves embedded nulls. */
typedef struct String { const char *data; size_t length; } String;
static inline String StringView(const char *data, size_t length) {
    String value = {data, length};
    return value;
}
static inline bool StringEqual(String a, String b) {
    return a.length == b.length && (a.length == 0 || memcmp(a.data, b.data, a.length) == 0);
}
#endif
#include "kryon_compat.generated.h"

typedef struct AccessibilityNode {
    Rectangle bounds;
    const char* role;
    const char* label;
    bool focused;
    bool disabled;
    bool checked;
    int32_t focus_id;
    const char* value;
    bool read_only;
    bool secure;
    bool multiline;
    uint64_t generation;
    unsigned actions;
    int32_t selection_anchor;
    int32_t selection_cursor;
    uint64_t key;
    unsigned parent;
    bool selected;
    bool multi_select;
    int32_t item_index;
    bool offscreen;
} AccessibilityNode;

#endif /* K_RUNTIME_ACCESSIBILITY_NODE_H */
