/* Generated by k2c from runtime/core_props.kry. */
#ifndef K_RUNTIME_CORE_PROPS_H
#define K_RUNTIME_CORE_PROPS_H

#include <stdint.h>
#include <stdbool.h>
#include "kry_bounds.h"

#ifndef KIR_STRING_VALUE_DEFINED
#define KIR_STRING_VALUE_DEFINED
#include <stddef.h>
#include <string.h>
/* Immutable borrowed UTF-8 bytes; length preserves embedded nulls. */
typedef struct String { const char *data; size_t length; } String;
static inline String StringView(const char *data, size_t length) {
    String value = {data, length};
    return value;
}
static inline bool StringEqual(String a, String b) {
    return a.length == b.length && (a.length == 0 || memcmp(a.data, b.data, a.length) == 0);
}
#endif
#include "kryon_compat.generated.h"
#include "ui_input_props.generated.h"

typedef void (*TextInputPlatformCallback)(int active);

typedef struct FrameState { int view_width; int view_height; Camera2D camera; int input_clip_count; Rectangle input_clips[16]; int input_capture_count; struct { Rectangle bounds; int allow_inside; } input_captures[16]; int cursor_priority; int cursor_had_intent; int pointer_down; int pointer_dragging; int pointer_dragged_this_click; int pointer_start_x; int pointer_start_y; int pointer_owner; int release_consumed; int focus_active_id; int focus_ids[256]; int focus_count; int focus_tab_dir; int focus_frame_open; int focus_text_input_active; int text_input_requested; int text_input_show_requested; int mouse_world_override_enabled; Vector2 mouse_world_override; unsigned long frame_serial; int auto_focus_id; float ui_scale; } FrameState;
extern int32_t ui_view_width;
extern int32_t ui_view_height;
void InitInterface(int32_t width, int32_t  height, float  dpi);
void SetDefaultFontAutoLoad(int32_t enabled);
void ApplyCurrentTheme(void);
int32_t IsDesktopMode(void);
Camera2D GetDefaultCamera(void);
void BeginInterfaceFrame(int32_t width, int32_t  height, float  dpi);
void EndInterfaceFrame(void);
int32_t ResolveFocusID(int32_t id);
void SetFrameCamera(Camera2D camera);
FrameState SaveFrameState(void);
void RestoreFrameState(FrameState state);
void SetMouseWorldOverride(int32_t enabled, Vector2  position);
int32_t SetKeyboardInputEnabled(int32_t enabled);
int32_t IsKeyboardInputEnabled(void);
void ClearInputCaptures(void);
void PushInputCapture(Rectangle bounds, int32_t  allow_inside);
void PopInputCapture(void);
void BeginModalLayer(void);
void PushInputClip(Rectangle bounds);
void PopInputClip(void);
void SetModalCapture(Rectangle bounds);
void SetTextInputPlatformCallback(TextInputPlatformCallback callback);
void SetCursorClickable(int32_t* cursor_clickable);
void SetCursorDisabled(int32_t* cursor_disabled);
void MarkCursor(int32_t cursor);
void MarkClickable(void);
void MarkDisabled(void);
int32_t GetMouseCursorIntent(void);
void SetInterfaceIcons(Texture2D gear_icon, Texture2D  x_icon);
int32_t HandleClick(Rectangle bounds, int32_t  disabled, int32_t*  hover);
Activation ReadActivation(Rectangle bounds, int32_t  id, bool  enabled);
int32_t HandleCircleClick(Vector2 center, float  radius, int32_t  disabled, int32_t*  hover);
int32_t InputCapturesClick(Vector2 point);
int32_t ReleaseConsumed(void);
void ConsumeRelease(void);
int32_t HoverEffectsEnabled(void);
void SetTransitionCuesEnabled(int32_t enabled);
int32_t TransitionCuesEnabled(void);
int32_t FocusFrameOpen(void);
int32_t RegisterFocus(int32_t id, Rectangle  bounds);
void BeginFocusScope(void);
void EndFocusScope(void);
int32_t IsFocusActive(int32_t id);
int32_t IsFocusActivatePressed(int32_t id);
void KryonSetFocus(int32_t id);
int32_t KryonGetFocus(void);
void ClearFocus(void);
void SetFocusTextInputActive(int32_t active);
int32_t TextInputActive(void);

#endif /* K_RUNTIME_CORE_PROPS_H */
