/* Generated by k2c from runtime/drag_drop_props.kry. */
#ifndef K_RUNTIME_DRAG_DROP_PROPS_H
#define K_RUNTIME_DRAG_DROP_PROPS_H

#include <stdint.h>
#include <stdbool.h>
#include "kry_bounds.h"

#ifndef KIR_STRING_VALUE_DEFINED
#define KIR_STRING_VALUE_DEFINED
#include <stddef.h>
#include <string.h>
/* Immutable borrowed UTF-8 bytes; length preserves embedded nulls. */
typedef struct String { const char *data; size_t length; } String;
static inline String StringView(const char *data, size_t length) {
    String value = {data, length};
    return value;
}
static inline bool StringEqual(String a, String b) {
    return a.length == b.length && (a.length == 0 || memcmp(a.data, b.data, a.length) == 0);
}
#endif
#include "kryon_compat.generated.h"

typedef enum DragDropRole {
    DragDropRoleSource = 0,
    DragDropRoleTarget = 1,
} DragDropRole;

typedef struct DragDropProps {
    Rectangle bounds;
    int32_t id;
    int32_t class_name;
    DragDropRole role;
    const char* type;
    const void* data;
    int32_t data_size;
    void* output;
    int32_t output_size;
    int32_t* accepted_size;
    bool disabled;
} DragDropProps;

#endif /* K_RUNTIME_DRAG_DROP_PROPS_H */
