/* Generated by k2c from runtime/modal_props.kry. */
#ifndef K_RUNTIME_MODAL_PROPS_H
#define K_RUNTIME_MODAL_PROPS_H

#include <stdint.h>
#include <stdbool.h>

#ifndef KIR_STRING_VALUE_DEFINED
#define KIR_STRING_VALUE_DEFINED
#include <stddef.h>
#include <string.h>
/* Immutable borrowed UTF-8 bytes; length preserves embedded nulls. */
typedef struct String { const char *data; size_t length; } String;
static inline String StringView(const char *data, size_t length) {
    String value = {data, length};
    return value;
}
static inline bool StringEqual(String a, String b) {
    return a.length == b.length && (a.length == 0 || memcmp(a.data, b.data, a.length) == 0);
}
#endif
#include "ui_control_props.generated.h"

typedef struct ModalAction {
    const char* label;
    ButtonTone tone;
    ButtonEmphasis emphasis;
    bool disabled;
} ModalAction;

typedef struct ModalProps {
    const char* title;
    int32_t class_name;
    const char* message;
    const ModalAction* actions;
    int32_t action_count;
    Texture2D close_icon;
    int32_t max_width;
    char* text;
    int32_t text_size;
    int32_t* cursor_position;
    bool* focused;
    int32_t focus_id;
} ModalProps;

#endif /* K_RUNTIME_MODAL_PROPS_H */
