/* Generated by k2c from runtime/menu_props.kry. */
#ifndef K_RUNTIME_MENU_PROPS_H
#define K_RUNTIME_MENU_PROPS_H

#include <stdint.h>
#include <stdbool.h>

#ifndef KIR_STRING_VALUE_DEFINED
#define KIR_STRING_VALUE_DEFINED
#include <stddef.h>
#include <string.h>
/* Immutable borrowed UTF-8 bytes; length preserves embedded nulls. */
typedef struct String { const char *data; size_t length; } String;
static inline String StringView(const char *data, size_t length) {
    String value = {data, length};
    return value;
}
static inline bool StringEqual(String a, String b) {
    return a.length == b.length && (a.length == 0 || memcmp(a.data, b.data, a.length) == 0);
}
#endif
#include "ui_menu_types.h"

typedef struct MenuProps {
    int32_t id;
    MenuMode mode;
    Rectangle bounds;
    Rectangle trigger;
    const MenuGroup* menus;
    int32_t menu_count;
    const MenuItem* items;
    int32_t item_count;
    int32_t* open_index;
    int32_t* open;
    int32_t* x;
    int32_t* y;
} MenuProps;

#endif /* K_RUNTIME_MENU_PROPS_H */
