#ifndef UI_PROFILE_H
#define UI_PROFILE_H

#include "kryon_compat.generated.h"
#include "ui_icon_types.h"

typedef enum {
    UI_SYNC_PROFILE_ICON_NONE = 0,
    UI_SYNC_PROFILE_ICON_BIRD = 1,
    UI_SYNC_PROFILE_ICON_BOWL = 2,
    UI_SYNC_PROFILE_ICON_CACTUS = 3,
    UI_SYNC_PROFILE_ICON_HEART = 4,
    UI_SYNC_PROFILE_ICON_INCENSE = 5,
    UI_SYNC_PROFILE_ICON_LOTUS = 6,
    UI_SYNC_PROFILE_ICON_TREE1 = 7,
    UI_SYNC_PROFILE_ICON_TREE2 = 8,
    UI_SYNC_PROFILE_ICON_TREE3 = 9,
    UI_SYNC_PROFILE_ICON_TREE4 = 10,
    UI_SYNC_PROFILE_ICON_TREE5 = 11,
    UI_SYNC_PROFILE_ICON_BAMBUS = 12,
    UI_SYNC_PROFILE_ICON_BUSH = 13,
    UI_SYNC_PROFILE_ICON_COFFEE = 14,
    UI_SYNC_PROFILE_ICON_FLOWER1 = 15,
    UI_SYNC_PROFILE_ICON_FLOWER2 = 16,
    UI_SYNC_PROFILE_ICON_MOUNTAIN = 17,
    UI_SYNC_PROFILE_ICON_MUSHROOM = 18,
    UI_SYNC_PROFILE_ICON_PERSON1 = 19,
    UI_SYNC_PROFILE_ICON_RAINBOW = 20,
    UI_SYNC_PROFILE_ICON_TENT = 21,
    UI_SYNC_PROFILE_ICON_BUTTERFLY = 22,
    UI_SYNC_PROFILE_ICON_DRAGONFLY = 23,
    UI_SYNC_PROFILE_ICON_FIREPLACE = 24,
    UI_SYNC_PROFILE_ICON_FOX = 25,
    UI_SYNC_PROFILE_ICON_PALM = 26
} UISyncProfileIcon;

int GetUIProfilePictureIconCount(void);
UIIconType GetUIProfilePictureIconType(int index);
const char *GetUIProfilePictureIconName(int index);
UIIconType GetUIProfilePictureIconTypeForSyncID(int sync_id);
int GetUISyncIDForProfilePictureIconType(UIIconType type);

#endif
