/* Generated by k2c from runtime/reorder_props.kry. */
#ifndef K_RUNTIME_REORDER_PROPS_H
#define K_RUNTIME_REORDER_PROPS_H

#include <stdint.h>
#include <stdbool.h>

#ifndef KIR_STRING_VALUE_DEFINED
#define KIR_STRING_VALUE_DEFINED
#include <stddef.h>
#include <string.h>
/* Immutable borrowed UTF-8 bytes; length preserves embedded nulls. */
typedef struct String { const char *data; size_t length; } String;
static inline String StringView(const char *data, size_t length) {
    String value = {data, length};
    return value;
}
static inline bool StringEqual(String a, String b) {
    return a.length == b.length && (a.length == 0 || memcmp(a.data, b.data, a.length) == 0);
}
#endif
#include "ui_drawing_props.generated.h"

typedef struct ReorderItem {
    int32_t id;
    Rectangle bounds;
    int32_t disabled;
} ReorderItem;

typedef struct ReorderList {
    int32_t id;
    Rectangle bounds;
    const ReorderItem* items;
    int32_t item_count;
    int32_t handle_width;
    int32_t handle_height;
    int32_t drag_threshold;
    int32_t* scroll_offset;
    int32_t max_scroll;
    int32_t viewport_top;
    int32_t viewport_bottom;
    int32_t auto_scroll_margin;
    int32_t auto_scroll_step;
} ReorderList;

typedef struct ReorderState {
    int32_t list_id;
    int32_t item_id;
    int32_t from_index;
    int32_t press_y;
    int32_t press_offset_y;
    int32_t scroll_start;
    int32_t dragging;
} ReorderState;

typedef struct ReorderMetrics {
    int32_t handle_width;
    int32_t drag_threshold;
    int32_t auto_scroll_margin;
    int32_t auto_scroll_step;
} ReorderMetrics;

typedef struct ReorderHandlePaint {
    Rectangle dot0;
    Rectangle dot1;
    Rectangle dot2;
    Rectangle dot3;
    Rectangle dot4;
    Rectangle dot5;
    int32_t dot_count;
} ReorderHandlePaint;

typedef struct ReorderPlaceholderPaint {
    Rectangle slot_bounds;
    Rectangle line_bounds;
    float stroke_width;
    float radius;
    int32_t segments;
    float fill_alpha;
    int32_t use_slot;
} ReorderPlaceholderPaint;

typedef struct ReorderListResult {
    int32_t active;
    int32_t dragging;
    int32_t committed;
    int32_t from_index;
    int32_t to_index;
    int32_t active_index;
    int32_t target_index;
    int32_t active_id;
    int32_t pointer_y;
    int32_t drag_delta_y;
} ReorderListResult;

#endif /* K_RUNTIME_REORDER_PROPS_H */
