/* Generated by k2c from runtime/segmented_control_props.kry. */
#ifndef K_RUNTIME_SEGMENTED_CONTROL_PROPS_H
#define K_RUNTIME_SEGMENTED_CONTROL_PROPS_H

#include <stdint.h>
#include <stdbool.h>

#ifndef KIR_STRING_VALUE_DEFINED
#define KIR_STRING_VALUE_DEFINED
#include <stddef.h>
#include <string.h>
/* Immutable borrowed UTF-8 bytes; length preserves embedded nulls. */
typedef struct String { const char *data; size_t length; } String;
static inline String StringView(const char *data, size_t length) {
    String value = {data, length};
    return value;
}
static inline bool StringEqual(String a, String b) {
    return a.length == b.length && (a.length == 0 || memcmp(a.data, b.data, a.length) == 0);
}
#endif
#include "kryon_compat.generated.h"

typedef struct SegmentOption {
    const char* label;
    bool disabled;
} SegmentOption;

typedef struct SegmentedControlProps {
    Rectangle bounds;
    int32_t id;
    const SegmentOption* options;
    int32_t option_count;
    int32_t* selected_index;
    int32_t font;
    int32_t gap;
    int32_t height;
    int32_t min_item_width;
    int32_t max_item_width;
    bool wrap;
} SegmentedControlProps;

typedef struct SegmentedControlResult {
    int32_t selected_index;
    int32_t clicked_index;
    int32_t changed;
    int32_t height;
} SegmentedControlResult;

#endif /* K_RUNTIME_SEGMENTED_CONTROL_PROPS_H */
