/* Generated by k2c from runtime/tab_bar_props.kry. */
#ifndef K_RUNTIME_TAB_BAR_PROPS_H
#define K_RUNTIME_TAB_BAR_PROPS_H

#include <stdint.h>
#include <stdbool.h>
#include "kry_bounds.h"

#ifndef KIR_STRING_VALUE_DEFINED
#define KIR_STRING_VALUE_DEFINED
#include <stddef.h>
#include <string.h>
/* Immutable borrowed UTF-8 bytes; length preserves embedded nulls. */
typedef struct String { const char *data; size_t length; } String;
static inline String StringView(const char *data, size_t length) {
    String value = {data, length};
    return value;
}
static inline bool StringEqual(String a, String b) {
    return a.length == b.length && (a.length == 0 || memcmp(a.data, b.data, a.length) == 0);
}
#endif
#include "kryon_compat.generated.h"

typedef struct Tab {
    const char* label;
    Texture2D icon;
    bool disabled;
    bool closeable;
} Tab;

typedef struct TabBarProps {
    Rectangle bounds;
    int32_t class_name;
    const Tab* tabs;
    int32_t count;
    int32_t selected_index;
    int32_t min_tab_width;
    int32_t max_tab_width;
    int32_t* scroll_offset;
    bool focus_selected;
    int32_t* closed_index;
    int32_t* double_clicked_index;
    int32_t* reordered_from_index;
    int32_t* reordered_to_index;
    Rectangle* selected_tab_bounds;
    int32_t* middle_clicked_index;
    int32_t id;
    bool disabled;
} TabBarProps;
int32_t GetTabBarHeight(void);
int32_t TabBarHeight(void);

#endif /* K_RUNTIME_TAB_BAR_PROPS_H */
