import Base
import ./LAWS.bend as Laws

def Laws.select_item_returns_item(selected, item):
  {==}

def Laws.clear_selection_returns_none(selected, item):
  {==}

def Laws.deselect_matching_minus():
  {==}

def Laws.deselect_matching_zero():
  {==}

def Laws.deselect_matching_one():
  {==}

def Laws.deselect_distinct_preserves_minus_zero():
  {==}

def Laws.deselect_distinct_preserves_zero_one():
  {==}

def Laws.deselect_distinct_preserves_one_minus():
  {==}

def Laws.other_actions_preserve(selected, item):
  {==}
