#!/bin/sh
set -eu

raylib_header=${1:-vendor/raylib/src/raylib.h}
public_header=${2:-include/kryon_compat.generated.h}
rename_header=${3:-build/generated/raylib_backend_rename.h}
wrapper_source=${4:-build/generated/kryon_raylib_wrappers.c}
null_backend_source=${5:-build/generated/kryon_null_backend.c}
backend_prefix=${KRYON_RAYLIB_BACKEND_PREFIX:-KryonRaylibBackend_}

# Input symbols owned by the shared front-end (src/backend/kry_input.c,
# include/kry_input.h): the public names are defined there once for every
# backend, merging injection, the modal input override, and the keyboard
# platform callbacks. Backends only provide KryonBackendRaw_<name> hooks -
# the raylib wrapper file emits forwarders, the null backend emits zero
# stubs - so a new backend inherits the full input behavior for free.
input_symbols="IsKeyPressed IsKeyDown IsKeyReleased GetKeyPressed GetCharPressed IsMouseButtonPressed IsMouseButtonDown IsMouseButtonReleased IsMouseButtonUp GetMouseX GetMouseY GetMousePosition GetMouseDelta GetMouseWheelMove GetMouseWheelMoveV"

# Surface symbols defined once for every backend in kryon front-end sources;
# neither generated file defines them. The pure-math ones live in
# src/backend/kry_surface_math.c (color/collision/camera-transform/UTF-8
# arithmetic with no backend state); TakeScreenshot lives in
# src/backend/kry_screenshot.c (absolute paths must bypass the backend's
# basePath prefixing).
shared_symbols="Fade ColorLerp CheckCollisionPointRec CheckCollisionRecs GetWorldToScreen2D GetScreenToWorld2D GetCodepointNext TakeScreenshot LoadImageFromScreen InitWindow CloseWindow WindowShouldClose EndDrawing EnableEventWaiting DisableEventWaiting OpenURL"

if [ ! -f "$raylib_header" ]; then
    echo "raylib header not found: $raylib_header" >&2
    exit 1
fi

mkdir -p "$(dirname "$public_header")" "$(dirname "$rename_header")" "$(dirname "$wrapper_source")" "$(dirname "$null_backend_source")"

{
    echo "/* Generated by tools/generate-kryon-compat.sh; do not edit. */"
    cat <<'EOF'
/*
 * Kryon graphics/input API surface.
 *
 * This header defines kryon's public graphics, input, and asset API. It
 * currently tracks raylib's surface verbatim so that existing raylib-style
 * code (DrawRectangle, Font, BeginDrawing, ...) compiles unchanged, and so
 * the raylib backend (build/generated/kryon_raylib_wrappers.c) can implement
 * every symbol by forwarding to raylib.
 *
 * Kryon owns this surface. It is not "raylib that kryon happens to use":
 * other backends implement these same function and type names without raylib
 * (for example an HTML5 canvas backend). Selection is link-time, via the
 * KRYON_BACKEND make variable. The raylib version tracked below is the
 * baseline; kryon may evolve this surface independently over time.
 */
EOF
    cat <<'EOF'

#ifndef KRYON_KEY_PLATFORM_CALLBACKS_DEFINED
#define KRYON_KEY_PLATFORM_CALLBACKS_DEFINED

typedef void (*KeyInputPlatformCallback)(void);
typedef int (*KeyPlatformCallback)(int key);

int SetKeyboardInputEnabled(int enabled);
int KeyboardInputEnabled(void);
void SetKeyPlatformCallbacks(KeyInputPlatformCallback update,
                             KeyPlatformCallback key_pressed,
                             KeyPlatformCallback key_down);
void UpdateKeyPlatformState(void);

#endif

EOF
    awk '
        function begin_skip() {
            skip_depth = 1
        }

        skip_depth > 0 {
            if($0 ~ /^[[:space:]]*#if/)
                skip_depth++
            else if($0 ~ /^[[:space:]]*#endif/)
                skip_depth--
            next
        }

        /^[[:space:]]*#include[[:space:]]+<stdarg.h>/ {
            print "#ifndef KRYON_NATIVE_PLAN9"
            print $0
            print "#endif"
            next
        }
        /^[[:space:]]*#if[[:space:]]+defined\(_WIN32\)/ {
            print "#ifdef _WIN32"
            print "    #ifdef __TINYC__"
            print "        #define __declspec(x) __attribute__((x))"
            print "    #endif"
            print "    #ifdef BUILD_LIBTYPE_SHARED"
            print "        #define RLAPI __declspec(dllexport)     // Building the library as a Win32 shared library (.dll)"
            print "    #else"
            print "        #ifdef USE_LIBTYPE_SHARED"
            print "            #define RLAPI __declspec(dllimport)     // Using the library as a Win32 shared library (.dll)"
            print "        #endif"
            print "    #endif"
            print "#else"
            print "    #ifdef BUILD_LIBTYPE_SHARED"
            print "        #define RLAPI __attribute__((visibility(\"default\"))) // Building as a Unix shared library (.so/.dylib)"
            print "    #endif"
            print "#endif"
            begin_skip()
            next
        }
        /^[[:space:]]*#if[[:space:]]+defined\(__cplusplus\)/ {
            print "#ifdef __cplusplus"
            next
        }
        /^[[:space:]]*#if[[:space:]]+!defined\(_MSC_VER\)/ {
            begin_skip()
            next
        }
        /^[[:space:]]*#if[[:space:]]+!defined\(__cplusplus\)/ {
            print "#ifdef KRYON_NATIVE_PLAN9"
            print "#ifndef bool"
            print "    typedef enum bool { false = 0, true = !false } bool;"
            print "    #define RL_BOOL_TYPE"
            print "#endif"
            print "#else"
            print "#ifndef __cplusplus"
            print "    #include <stdbool.h>"
            print "#endif"
            print "#endif"
            begin_skip()
            next
        }
        { print }
    ' "$raylib_header"
} > "$public_header"

{
    echo "/* Generated by tools/generate-kryon-compat.sh; do not edit. */"
    echo "#ifndef KRYON_RAYLIB_BACKEND_RENAME_H"
    echo "#define KRYON_RAYLIB_BACKEND_RENAME_H"
    echo
    awk -v emit_audio="${KRYON_COMPAT_AUDIO:-1}" '
        /^\/\/ Audio Loading and Playing Functions/ { in_audio_section = 1 }
        /^[[:space:]]*(RLAPI|RMAPI)[[:space:]]/ {
            if(emit_audio == "0" && in_audio_section)
                next
            line = $0
            sub(/\(.*/, "", line)
            n = split(line, parts, /[[:space:]\*]+/)
            if(n > 0 && parts[n] ~ /^[A-Za-z_][A-Za-z0-9_]*$/)
                print parts[n]
        }
    ' "$raylib_header" | sort -u | while IFS= read -r symbol; do
        [ -n "$symbol" ] || continue
        printf '#define %s %s%s\n' "$symbol" "$backend_prefix" "$symbol"
    done
    echo
    echo "#endif"
} > "$rename_header"

awk -v prefix="$backend_prefix" -v input_symbols="$input_symbols" -v shared_symbols="$shared_symbols" -v emit_audio="${KRYON_COMPAT_AUDIO:-1}" '
function trim(s) {
    sub(/^[[:space:]]+/, "", s)
    sub(/[[:space:]]+$/, "", s)
    return s
}

function function_name_from_prefix(prefix_text, parts, n) {
    n = split(prefix_text, parts, /[[:space:]\*]+/)
    return parts[n]
}

function return_type_from_prefix(prefix_text, name) {
    sub(/^[[:space:]]*(RLAPI|RMAPI)[[:space:]]+/, "", prefix_text)
    sub("[[:space:]]*" name "$", "", prefix_text)
    return trim(prefix_text)
}

function arg_name(arg, parts, n, name) {
    arg = trim(arg)
    sub(/=.*/, "", arg)
    gsub(/\[[^]]*\]/, "", arg)
    n = split(arg, parts, /[[:space:]\*]+/)
    name = parts[n]
    gsub(/[^A-Za-z0-9_]/, "", name)
    return name
}

function call_args(args, parts, count, i, name, out) {
    args = trim(args)
    if(args == "void" || args == "")
        return ""
    count = split(args, parts, /,[[:space:]]*/)
    out = ""
    for(i = 1; i <= count; i++) {
        if(parts[i] == "...")
            continue
        name = arg_name(parts[i])
        if(name == "")
            continue
        out = out (out == "" ? "" : ", ") name
    }
    return out
}

function emit_regular_wrapper(return_type, name, args, backend_args, returns_void) {
    print "extern " return_type " " prefix name "(" args ");"
    print return_type " " name "(" args ")"
    print "    {"
    if(returns_void) {
        print "    " prefix name "(" backend_args ");"
    } else {
        print "    return " prefix name "(" backend_args ");"
    }
    print "}"
    print ""
}

# Input symbols defined publicly by src/backend/kry_input.c; the wrapper
# file provides only the raw hook the front-end calls into.
function emit_input_raw_wrapper(return_type, name, args, backend_args, returns_void) {
    print "extern " return_type " " prefix name "(" args ");"
    print return_type " KryonBackendRaw_" name "(" args ")"
    print "    {"
    if(returns_void) {
        print "    " prefix name "(" backend_args ");"
    } else {
        print "    return " prefix name "(" backend_args ");"
    }
    print "}"
    print ""
}

function emit_variadic_wrapper(return_type, name, args, fixed_args, backend_args) {
    print "extern " return_type " " prefix name "(" args ");"
    print return_type " " name "(" args ")"
    print "    {"
    if(name == "TextFormat")
        print "    static char text_buffer[4096];"
    else
        print "    char text_buffer[4096];"
    print "    va_list ap;"
    print "    va_start(ap, text);"
    print "    vsnprintf(text_buffer, sizeof(text_buffer), text, ap);"
    print "    va_end(ap);"
    if(name == "TraceLog") {
        print "    " prefix name "(logLevel, \"%s\", text_buffer);"
    } else {
        print "    (void)" prefix name ";"
        print "    return text_buffer;"
    }
    print "}"
    print ""
}

BEGIN {
    split(input_symbols, isym, " ")
    for(i in isym)
        input_owned[isym[i]] = 1
    split(shared_symbols, ssym, " ")
    for(i in ssym)
        shared_owned[ssym[i]] = 1
    print "/* Generated by tools/generate-kryon-compat.sh; do not edit. */"
    print "/* Input queries are defined by src/backend/kry_input.c; this file"
    print " * only provides their KryonBackendRaw_* hooks. Pure-math symbols"
    print " * live in src/backend/kry_surface_math.c. */"
    print "#include \"kryon.h\""
    print "#include <stdarg.h>"
    print "#include <stdio.h>"
    print "#if defined(__GNUC__) || defined(__clang__)"
    print "#define KRYON_NULL_WEAK __attribute__((weak))"
    print "#else"
    print "#define KRYON_NULL_WEAK"
    print "#endif"
    print ""
}

/^\/\/ Audio Loading and Playing Functions/ { in_audio_section = 1 }

/^[[:space:]]*(RLAPI|RMAPI)[[:space:]]/ {
    line = $0
    sub(/\/\/.*$/, "", line)
    line = trim(line)
    sub(/;$/, "", line)
    prefix_text = line
    sub(/\(.*/, "", prefix_text)
    name = function_name_from_prefix(prefix_text)
    return_type = return_type_from_prefix(prefix_text, name)
    args = line
    sub(/^[^(]*\(/, "", args)
    sub(/\)$/, "", args)
    # Apps that build raylib without the audio module (uku-style
    # SUPPORT_MODULE_RAUDIO=0) must not get forwarders for symbols that
    # no longer exist. Audio is the last module section in raylib.h.
    if(emit_audio == "0" && in_audio_section)
        next
    if(name in shared_owned)
        next
    if(args ~ /\.\.\./) {
        emit_variadic_wrapper(return_type, name, args)
    } else if(name in input_owned) {
        emit_input_raw_wrapper(return_type, name, args, call_args(args), return_type == "void")
    } else {
        emit_regular_wrapper(return_type, name, args, call_args(args), return_type == "void")
    }
}
' "$raylib_header" > "$wrapper_source"

# Null backend: a link-time backend (KRYON_BACKEND=null) that provides a
# zero-return no-op stub for every public-surface symbol so libkryon.a links
# and runs headless with no GPU/window. Generated from the same raylib.h so it
# stays in sync with the surface automatically. Used for widget unit tests.
awk -v prefix="$backend_prefix" -v input_symbols="$input_symbols" -v shared_symbols="$shared_symbols" '
function trim(s) {
    sub(/^[[:space:]]+/, "", s)
    sub(/[[:space:]]+$/, "", s)
    return s
}

function function_name_from_prefix(prefix_text, parts, n) {
    n = split(prefix_text, parts, /[[:space:]\*]+/)
    return parts[n]
}

function return_type_from_prefix(prefix_text, name) {
    sub(/^[[:space:]]*(RLAPI|RMAPI)[[:space:]]+/, "", prefix_text)
    sub("[[:space:]]*" name "$", "", prefix_text)
    return trim(prefix_text)
}

function is_pointer_return(return_type) {
    return return_type ~ /\*$/
}

function arg_name(arg, parts, n, name) {
    arg = trim(arg)
    sub(/=.*/, "", arg)
    gsub(/\[[^]]*\]/, "", arg)
    n = split(arg, parts, /[[:space:]\*]+/)
    name = parts[n]
    gsub(/[^A-Za-z0-9_]/, "", name)
    return name
}

BEGIN {
    split(input_symbols, isym, " ")
    for(i in isym)
        input_owned[isym[i]] = 1
    split(shared_symbols, ssym, " ")
    for(i in ssym)
        shared_owned[ssym[i]] = 1
    print "/* Generated by tools/generate-kryon-compat.sh; do not edit. */"
    print "/* Null backend: zero-return no-op stubs for the kryon surface."
    print " * Selected via KRYON_BACKEND=null for headless links (tests)."
    print " * Input queries are defined by src/backend/kry_input.c; this file"
    print " * only provides their KryonBackendRaw_* hooks, so injected input"
    print " * works on the null backend too. Pure-math symbols live in"
    print " * src/backend/kry_surface_math.c. */"
    print "#include \"kryon.h\""
    print "#include <stdarg.h>"
    print "#include <stdio.h>"
    print "#if defined(__GNUC__) || defined(__clang__)"
    print "#define KRYON_NULL_WEAK __attribute__((weak))"
    print "#else"
    print "#define KRYON_NULL_WEAK"
    print "#endif"
    print ""
}

/^[[:space:]]*(RLAPI|RMAPI)[[:space:]]/ {
    line = $0
    sub(/\/\/.*$/, "", line)
    line = trim(line)
    sub(/;$/, "", line)
    prefix_text = line
    sub(/\(.*/, "", prefix_text)
    name = function_name_from_prefix(prefix_text)
    return_type = return_type_from_prefix(prefix_text, name)
    args = line
    sub(/^[^(]*\(/, "", args)
    sub(/\)$/, "", args)

    if(name in shared_owned)
        next

    # Input queries are public only via src/backend/kry_input.c; emit the
    # raw hook the front-end calls instead of the public name.
    if(name in input_owned)
        name = "KryonBackendRaw_" name

    # Variadic stubs: TextFormat returns "", TraceLog is a no-op.
    if(name == "TextFormat") {
        print "KRYON_NULL_WEAK const char *TextFormat(const char *text, ...) { (void)text; return \"\"; }"
        print ""
        next
    }
    if(name == "TraceLog") {
        print "KRYON_NULL_WEAK void TraceLog(int logLevel, const char *text, ...) { (void)logLevel; (void)text; }"
        print ""
        next
    }

    print "KRYON_NULL_WEAK " return_type " " name "(" args ")"
    print "    {"
    # Cast every named parameter to void to suppress -Wunused-parameter.
    n_args = split(args, arg_parts, /,[[:space:]]*/)
    for(ai = 1; ai <= n_args; ai++) {
        an = arg_name(arg_parts[ai])
        if(an != "" && an != "void")
            print "    (void)" an ";"
    }
    if(return_type == "void") {
        # nothing
    } else if(is_pointer_return(return_type)) {
        print "    return 0;"
    } else if(return_type ~ /^(int|long|short|char|bool|unsigned|float|double|size_t|[us]int8_t|[us]int16_t|[us]int32_t|[us]int64_t|GLenum|GLuint|GLint|GLfloat)/ ||
             return_type ~ /(_t|Flags|Key|MouseButton|Cursor|Gesture|BlendMode|TextureFilter|CubemapLayout|ShaderLocationIndex|ShaderUniformDataType|ShaderAttributeDataType|PixelFormat|BlendMode|Tex2D|MaterialMapIndex|NPatchLayout|KeyboardKey|GamepadButton|GamepadAxis)$/ ) {
        print "    return 0;"
    } else {
        # struct return (Color, Rectangle, Vector2, Image, Texture2D, Font, ...) -> zero-init
        print "    " return_type " r = {0};"
        print "    return r;"
    }
    print "}"
    print ""
}
' "$raylib_header" > "$null_backend_source"
