#ifndef ACCESSIBILITY_PROTOCOL_H
#define ACCESSIBILITY_PROTOCOL_H

#define ATSPI_ACCESSIBLE "org.a11y.atspi.Accessible"
#define ATSPI_COMPONENT "org.a11y.atspi.Component"
#define ATSPI_ACTION "org.a11y.atspi.Action"
#define ATSPI_TEXT "org.a11y.atspi.Text"
#define ATSPI_EDITABLE "org.a11y.atspi.EditableText"
#define ATSPI_APPLICATION "org.a11y.atspi.Application"
#define ATSPI_CACHE "org.a11y.atspi.Cache"
#define ATSPI_SELECTION "org.a11y.atspi.Selection"
#define ATSPI_CACHE_PATH "/org/a11y/atspi/cache"
#define ATSPI_ROOT "/org/a11y/atspi/accessible/root"
#define ATSPI_WINDOW "/org/a11y/atspi/accessible/window"
#define ATSPI_NULL "/org/a11y/atspi/null"

static const char accessibility_protocol[] =
    "<node>"
    "<interface name='" ATSPI_ACCESSIBLE "'>"
    "<property name='version' type='u' access='read'/>"
    "<property name='Name' type='s' access='read'/>"
    "<property name='Description' type='s' access='read'/>"
    "<property name='HelpText' type='s' access='read'/>"
    "<property name='Locale' type='s' access='read'/>"
    "<property name='AccessibleId' type='s' access='read'/>"
    "<property name='Parent' type='(so)' access='read'/>"
    "<property name='ChildCount' type='i' access='read'/>"
    "<method name='GetChildren'><arg type='a(so)' direction='out'/></method>"
    "<method name='GetChildAtIndex'><arg type='i' direction='in'/><arg type='(so)' direction='out'/></method>"
    "<method name='GetIndexInParent'><arg type='i' direction='out'/></method>"
    "<method name='GetRole'><arg type='u' direction='out'/></method>"
    "<method name='GetRoleName'><arg type='s' direction='out'/></method>"
    "<method name='GetLocalizedRoleName'><arg type='s' direction='out'/></method>"
    "<method name='GetState'><arg type='au' direction='out'/></method>"
    "<method name='GetAttributes'><arg type='a{ss}' direction='out'/></method>"
    "<method name='GetRelationSet'><arg type='a(ua(so))' direction='out'/></method>"
    "<method name='GetApplication'><arg type='(so)' direction='out'/></method>"
    "<method name='GetInterfaces'><arg type='as' direction='out'/></method>"
    "</interface>"
    "<interface name='" ATSPI_APPLICATION "'>"
    "<property name='ToolkitName' type='s' access='read'/>"
    "<property name='Version' type='s' access='read'/>"
    "<property name='ToolkitVersion' type='s' access='read'/>"
    "<property name='AtspiVersion' type='s' access='read'/>"
    "<property name='InterfaceVersion' type='u' access='read'/>"
    "<property name='Id' type='i' access='readwrite'/>"
    "<method name='GetLocale'><arg type='u' direction='in'/><arg type='s' direction='out'/></method>"
    "<method name='GetApplicationBusAddress'><arg type='s' direction='out'/></method>"
    "</interface>"
    "<interface name='" ATSPI_COMPONENT "'>"
    "<property name='version' type='u' access='read'/>"
    "<method name='GetExtents'><arg type='u' direction='in'/><arg type='(iiii)' direction='out'/></method>"
    "<method name='GetPosition'><arg type='u' direction='in'/><arg type='i' direction='out'/><arg type='i' direction='out'/></method>"
    "<method name='GetSize'><arg type='i' direction='out'/><arg type='i' direction='out'/></method>"
    "<method name='Contains'><arg type='i' direction='in'/><arg type='i' direction='in'/><arg type='u' direction='in'/><arg type='b' direction='out'/></method>"
    "<method name='GetAccessibleAtPoint'><arg type='i' direction='in'/><arg type='i' direction='in'/><arg type='u' direction='in'/><arg type='(so)' direction='out'/></method>"
    "<method name='GrabFocus'><arg type='b' direction='out'/></method>"
    "<method name='GetLayer'><arg type='u' direction='out'/></method>"
    "<method name='GetMDIZOrder'><arg type='n' direction='out'/></method>"
    "<method name='GetAlpha'><arg type='d' direction='out'/></method>"
    "</interface>"
    "<interface name='" ATSPI_ACTION "'>"
    "<property name='NActions' type='i' access='read'/>"
    "<method name='GetName'><arg type='i' direction='in'/><arg type='s' direction='out'/></method>"
    "<method name='GetLocalizedName'><arg type='i' direction='in'/><arg type='s' direction='out'/></method>"
    "<method name='GetDescription'><arg type='i' direction='in'/><arg type='s' direction='out'/></method>"
    "<method name='GetKeyBinding'><arg type='i' direction='in'/><arg type='s' direction='out'/></method>"
    "<method name='GetActions'><arg type='a(sss)' direction='out'/></method>"
    "<method name='DoAction'><arg type='i' direction='in'/><arg type='b' direction='out'/></method>"
    "</interface>"
    "<interface name='" ATSPI_TEXT "'>"
    "<property name='version' type='u' access='read'/>"
    "<property name='CharacterCount' type='i' access='read'/>"
    "<property name='CaretOffset' type='i' access='read'/>"
    "<method name='GetText'><arg type='i' direction='in'/><arg type='i' direction='in'/><arg type='s' direction='out'/></method>"
    "<method name='GetCharacterAtOffset'><arg type='i' direction='in'/><arg type='i' direction='out'/></method>"
    "<method name='GetStringAtOffset'><arg type='i' direction='in'/><arg type='u' direction='in'/><arg type='s' direction='out'/><arg type='i' direction='out'/><arg type='i' direction='out'/></method>"
    "<method name='SetCaretOffset'><arg type='i' direction='in'/><arg type='b' direction='out'/></method>"
    "<method name='GetNSelections'><arg type='i' direction='out'/></method>"
    "<method name='GetSelection'><arg type='i' direction='in'/><arg type='i' direction='out'/><arg type='i' direction='out'/></method>"
    "<method name='SetSelection'><arg type='i' direction='in'/><arg type='i' direction='in'/><arg type='i' direction='in'/><arg type='b' direction='out'/></method>"
    "<method name='AddSelection'><arg type='i' direction='in'/><arg type='i' direction='in'/><arg type='b' direction='out'/></method>"
    "<method name='RemoveSelection'><arg type='i' direction='in'/><arg type='b' direction='out'/></method>"
    "<method name='GetDefaultAttributes'><arg type='a{ss}' direction='out'/></method>"
    "</interface>"
    "<interface name='" ATSPI_EDITABLE "'>"
    "<method name='SetTextContents'><arg type='s' direction='in'/><arg type='b' direction='out'/></method>"
    "</interface>"
    "<interface name='" ATSPI_CACHE "'>"
    "<property name='version' type='u' access='read'/>"
    "<method name='GetItems'><arg type='a((so)(so)(so)iiassusau)' direction='out'/></method>"
    "<signal name='AddAccessible'><arg type='((so)(so)(so)iiassusau)'/></signal>"
    "<signal name='RemoveAccessible'><arg type='(so)'/></signal>"
    "</interface>"
    "<interface name='" ATSPI_SELECTION "'>"
    "<property name='version' type='u' access='read'/>"
    "<property name='NSelectedChildren' type='i' access='read'/>"
    "<method name='GetSelectedChild'><arg type='i' direction='in'/><arg type='(so)' direction='out'/></method>"
    "<method name='SelectChild'><arg type='i' direction='in'/><arg type='b' direction='out'/></method>"
    "<method name='DeselectChild'><arg type='i' direction='in'/><arg type='b' direction='out'/></method>"
    "<method name='DeselectSelectedChild'><arg type='i' direction='in'/><arg type='b' direction='out'/></method>"
    "<method name='IsChildSelected'><arg type='i' direction='in'/><arg type='b' direction='out'/></method>"
    "<method name='SelectAll'><arg type='b' direction='out'/></method>"
    "<method name='ClearSelection'><arg type='b' direction='out'/></method>"
    "</interface>"
    "</node>";

#endif
